import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
let playwright;try{playwright=await import('playwright');}catch{playwright=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE||path.resolve(root,'../../../../pingtan/node_modules/playwright/index.mjs')));}
const executable=process.env.CHROMIUM_PATH||'C:/Users/YUE/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe';
const {chromium}=playwright,errors=[],requests=[],checks=[],failures=[],base=process.env.TEST_URL||'http://127.0.0.1:5191/',report={dateLocal:'2026-10-07 Asia/Shanghai',timestampUTC:new Date().toISOString(),device:{os:os.type()+' '+os.release(),cpu:os.cpus()[0]?.model,ramGB:+(os.totalmem()/2**30).toFixed(1)},browser:'',viewport:[1440,960],pixelRatio:1,base,checks,errors,failedRequests:requests,failures,performance:[],limitations:'Headless Chromium desktop rendering. 390x844 mobile is touch emulation on the same PC, not a physical phone. FPS is measured requestAnimationFrame throughput; software checks do not establish geographic accuracy.'};
const browser=await chromium.launch({headless:true,executablePath:fs.existsSync(executable)?executable:undefined,args:['--enable-webgl','--ignore-gpu-blocklist']}),context=await browser.newContext({viewport:{width:1440,height:960},deviceScaleFactor:1}),page=await context.newPage();report.browser=await browser.version();
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>requests.push(r.url()+': '+r.failure()?.errorText));
const assert=(value,name)=>{checks.push({name,passed:!!value});if(!value)failures.push(name);},settle=async()=>{await page.waitForFunction(()=>window.__mawei&&!window.__mawei.nav.transitioning);await page.waitForTimeout(450);},shot=async name=>page.screenshot({path:path.join(root,'evidence',name)});
async function canvasShot(name){const data=await page.evaluate(()=>{const s=window.__mawei;s.renderer.info.reset();s.renderer.render(s.scene,s.camera);return s.renderer.domElement.toDataURL('image/png');});fs.writeFileSync(path.join(root,'evidence',name),Buffer.from(data.split(',')[1],'base64'));}
async function perf(label){report.performance.push(await page.evaluate(async label=>{const values=[],s=window.__mawei;let previous=performance.now(),start=previous;await new Promise(resolve=>{const frame=now=>{values.push(now-previous);previous=now;if(now-start<3000)requestAnimationFrame(frame);else resolve();};requestAnimationFrame(frame);});values.shift();values.sort((a,b)=>a-b);const mean=values.reduce((a,b)=>a+b,0)/values.length;return {label,sampleSeconds:3,frames:values.length,meanFrameMs:+mean.toFixed(2),observedRafFps:+(1000/mean).toFixed(1),p95FrameMs:+values[Math.floor(values.length*.95)].toFixed(2),drawCallsAllPasses:s.renderer.info.render.calls,trianglesAllPasses:s.renderer.info.render.triangles,textures:s.renderer.info.memory.textures,geometries:s.renderer.info.memory.geometries,quality:s.quality(),pixelRatio:s.renderer.getPixelRatio(),reflectionVisible:s.world.reflections.filter(r=>r.visible).length};},label));}
try{
 const start=Date.now();await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__mawei?.ready,null,{timeout:90000});await settle();report.readyMs=Date.now()-start;
 report.scene=await page.evaluate(()=>{const s=window.__mawei,gl=s.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),threeRevision:'180',buildings:s.data.summary.buildings,treeLocations:s.data.summary.trees,eyeHeight:1.65};});
 assert(await page.locator('#loading').isHidden(),'local resources load without blank screen');assert(await page.evaluate(()=>window.__mawei.camera.position.toArray().every(Number.isFinite)),'zero-duration initial camera is finite');
 assert(await page.evaluate(()=>{const s=window.__mawei,g=s.world.buildingGroups.find(g=>g.userData.id==='huyuan'),roof=g.children.find(n=>n.material===s.world.m.roof);if(!roof)return false;const normal=roof.geometry.attributes.normal;for(let i=0;i<normal.count;i++)if(normal.getY(i)<=0)return false;return true;}),'sample exterior roof slopes face upward');
 await shot('01-overview.png');await canvasShot('overview-scene.png');await perf('均衡 · 五大片区鸟瞰');assert(await page.evaluate(()=>window.__mawei.world.reflections.every(r=>!r.visible)),'aerial skips unnecessary reflection passes');
 assert(await page.locator('[data-zone]').count()===5,'five precinct shortcuts visible');assert(await page.locator('#labels .label:not([hidden])').count()===5,'overview labels show five precincts without full landmark clutter');assert(await page.evaluate(()=>__mawei.renderer.capabilities.logarithmicDepthBuffer),'wide-area depth buffer supports metre-scale separation');
 await page.locator('#core').click();await settle();await canvasShot('core-overview-scene.png');assert(await page.evaluate(()=>__mawei.camera.position.y<300),'factory detail overview remains available');
 const q0=await page.evaluate(()=>window.__mawei.camera.position.toArray());await page.mouse.move(780,340);await page.mouse.down();await page.mouse.move(850,390,{steps:8});await page.mouse.up();await page.waitForTimeout(350);const q1=await page.evaluate(()=>window.__mawei.camera.position.toArray());assert(Math.hypot(...q1.map((v,i)=>v-q0[i]))>1,'orbit drag rotates view');await page.mouse.wheel(0,-250);await page.waitForTimeout(400);const q2=await page.evaluate(()=>window.__mawei.camera.position.toArray());assert(Math.hypot(...q2.map((v,i)=>v-q1[i]))>1,'orbit wheel zoom works');
 await page.locator('#walk').click();await settle();assert(await page.evaluate(()=>Math.abs(window.__mawei.camera.position.y-1.65)<1e-6),'walking eye height 1.65m');assert(await page.evaluate(()=>{const s=window.__mawei;return !s.collision.blocked(s.camera.position.x,s.camera.position.z);}), 'walking start outside walls and pools');await shot('02-huyuan-walk.png');await canvasShot('huyuan-walk-scene.png');await perf('均衡 · 绘事院步行');
 const before=await page.evaluate(()=>window.__mawei.camera.position.toArray());await page.locator('#view').focus();await page.keyboard.down('w');await page.waitForTimeout(800);await page.keyboard.up('w');const after=await page.evaluate(()=>window.__mawei.camera.position.toArray());assert(Math.hypot(after[0]-before[0],after[2]-before[2])>.4,'W moves at walking speed');
 await page.locator('#reference-camera').click();await settle();await shot('03-huyuan-reference.png');await canvasShot('huyuan-reference-scene.png');await perf('均衡 · 绘事院近似实景机位');
 for(const id of ['engine','iron','library','museum','theatre','quay','guanjie','yamen','frontSchool','tianhou','zhaozhong','consulate','hospitalA','dock2','luoxing']){await page.evaluate(id=>window.__mawei.jump(id,'walk',true),id);await settle();assert(await page.evaluate(()=>{const s=window.__mawei;return s.camera.position.toArray().every(Number.isFinite)&&!s.collision.blocked(s.camera.position.x,s.camera.position.z);}),id+' jump safe and finite');assert(await page.evaluate(()=>{const s=__mawei;return Math.abs(s.camera.position.y-s.collision.height(s.camera.position.x,s.camera.position.z)-1.65)<.00001;}),id+' eye follows local ground');if(['engine','iron','museum','luoxing','zhaozhong','consulate','dock2','guanjie'].includes(id)){await shot(id+'-walk.png');await canvasShot(id+'-scene.png');}}
 for(const id of ['luoxing','zhaozhong','consulate','yamen','frontSchool','tianhou','dock2']){await page.evaluate(id=>__mawei.jump(id,'aerial',true),id);await settle();await shot(id+'-aerial.png');await canvasShot(id+'-aerial-scene.png');}
 await perf('均衡 · 旧港近景');await page.locator('[data-zone="luoxing"]').click();await settle();assert(await page.evaluate(()=>__mawei.nav.orbit.target.distanceTo({x:__mawei.data.places.find(p=>p.id==='luoxing').target[0],y:__mawei.nav.orbit.target.y,z:__mawei.data.places.find(p=>p.id==='luoxing').target[1]})<.001),'precinct shortcut targets Luoxing tower');await perf('均衡 · 罗星塔公园');
 assert(await page.evaluate(()=>{const s=__mawei;return s.collision.blocked(0,500)&&s.data.city.pools.every(p=>{const c=p.polygon.reduce((a,v)=>[a[0]+v[0]/p.polygon.length,a[1]+v[1]/p.polygon.length],[0,0]);return s.collision.blocked(...c);});}),'expanded river and ponds block walking');
 await page.evaluate(()=>__mawei.jump('consulate','walk',true));await settle();const mountainStart=await page.evaluate(()=>__mawei.camera.position.toArray());await page.locator('#view').focus();await page.keyboard.down('d');await page.waitForTimeout(850);await page.keyboard.up('d');assert(await page.evaluate(start=>{const s=__mawei;return Math.hypot(s.camera.position.x-start[0],s.camera.position.z-start[2])>.4&&s.camera.position.y>25&&Math.abs(s.camera.position.y-s.collision.height(s.camera.position.x,s.camera.position.z)-1.65)<.00001;},mountainStart),'mountain walk remains above elevated ground');
 // Real camera locomotion into a wall across animation frames, not a duplicate formula.
 const wall=await page.evaluate(()=>{const s=window.__mawei,b=s.data.buildings.find(b=>b.id==='huyuan'),p=s.planWorld(b.frame.x,b.frame.y-b.frame.depth/s.data.planRegistration.scale/2-8),t=s.planWorld(b.frame.x,b.frame.y);s.nav.fly([p[0],1.65,p[1]],[t[0],1.65,t[1]],'walk',0);return p;});await page.locator('#view').focus();await page.keyboard.down('w');await page.waitForTimeout(2900);await page.keyboard.up('w');report.wallCollision=await page.evaluate(()=>{const s=window.__mawei;return {position:s.camera.position.toArray(),blocked:s.collision.blocked(s.camera.position.x,s.camera.position.z)};});assert(!report.wallCollision.blocked,'walking stops outside actual rendered wall');assert(Math.hypot(report.wallCollision.position[0]-wall[0],report.wallCollision.position[2]-wall[1])<2,'wall prevents continued forward movement');
 const pTest=await page.evaluate(()=>{const s=window.__mawei,p=s.world.platforms[0];s.nav.fly([p.center[0],1.65,p.center[1]],[p.center[0]+1,1.65,p.center[1]],'walk',0);return p.height;});await settle();assert(await page.evaluate(h=>Math.abs(window.__mawei.camera.position.y-(1.65+h))<1e-6,pTest),'platform ground height raises eye correctly');
 await page.locator('#labels-toggle').click();assert(await page.locator('#labels').isHidden(),'place label toggle');await page.locator('#labels-toggle').click();await page.locator('#evidence-toggle').click();assert(await page.evaluate(()=>window.__mawei.world.evidence.visible),'geographic outline evidence toggle');await page.locator('#evidence-toggle').click();
 await page.locator('#quality').selectOption('low');await page.evaluate(()=>window.__mawei.jump('huyuan','walk',true));await settle();await perf('节能 · 绘事院');assert(await page.evaluate(()=>!window.__mawei.renderer.shadowMap.enabled&&window.__mawei.world.reflections.every(r=>!r.visible)),'low profile disables shadows and reflection');await page.locator('#quality').selectOption('high');await settle();await perf('精细 · 绘事院');
 const downloadWait=page.waitForEvent('download');await page.locator('#capture').click();const download=await downloadWait;await download.saveAs(path.join(root,'evidence/export.png'));assert(fs.statSync(path.join(root,'evidence/export.png')).size>20000,'PNG export includes rendered canvas');
 await page.locator('#aerial').click();await settle();const oldTarget=await page.evaluate(()=>window.__mawei.nav.orbit.target.toArray());await page.locator('#minimap').click({position:{x:110,y:125}});await settle();const newTarget=await page.evaluate(()=>window.__mawei.nav.orbit.target.toArray());assert(Math.hypot(...newTarget.map((v,i)=>v-oldTarget[i]))>2,'minimap click moves destination');await page.locator('#info-toggle').click();assert(await page.locator('#info').isVisible(),'source and boundary dialog opens');await page.locator('#info-close').click();
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true}),phone=await mobileContext.newPage();await phone.goto(base);await phone.waitForFunction(()=>window.__mawei?.ready);assert(await phone.evaluate(()=>window.__mawei.quality()==='low'),'touch defaults to low quality');await phone.locator('#walk').tap();await phone.waitForFunction(()=>!window.__mawei.nav.transitioning);assert(await phone.locator('#touch-controls').isVisible(),'touch movement pad visible');const b=await phone.locator('[data-move="right"]').boundingBox(),cdp=await mobileContext.newCDPSession(phone),p0=await phone.evaluate(()=>window.__mawei.camera.position.toArray());await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await phone.waitForTimeout(900);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const p1=await phone.evaluate(()=>window.__mawei.camera.position.toArray());assert(Math.hypot(p1[0]-p0[0],p1[2]-p0[2])>.3,'touch pad moves camera');assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390px viewport has no horizontal overflow');await phone.screenshot({path:path.join(root,'evidence/mobile-touch.png')});await mobileContext.close();
 const failed=await context.newPage();await failed.route('**/data/site.json',r=>r.fulfill({status:404,body:'missing'}));await failed.goto(base);await failed.waitForSelector('#error:not([hidden])');assert((await failed.locator('#error-message').textContent()).includes('site.json'),'missing geographic data produces named error');await failed.screenshot({path:path.join(root,'evidence/resource-failure.png')});await failed.close();
 const missingTexture=await context.newPage();await missingTexture.route('**/textures/brick-color.jpg',r=>r.fulfill({status:404,body:'missing'}));await missingTexture.goto(base);await missingTexture.waitForFunction(()=>window.__mawei?.ready);assert(await missingTexture.evaluate(()=>window.__maweiWarnings?.includes('textures/brick-color.jpg')),'optional texture has explicit procedural fallback');await missingTexture.close();
 const missingModule=await context.newPage();await missingModule.route('**/vendor/three.core.min.js',r=>r.fulfill({status:404,body:'missing'}));await missingModule.goto(base);await missingModule.waitForSelector('#error:not([hidden])');assert(await missingModule.locator('#loading').isHidden(),'failed dependency displays error instead of permanent loader');await missingModule.close();
 assert(errors.length===0,'no normal-run JS or console errors');assert(requests.length===0,'no normal-run failed requests');
}catch(e){failures.push(e.stack||e.message);}finally{fs.writeFileSync(path.join(root,'evidence/test-results.json'),JSON.stringify(report,null,2));await browser.close();}
console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
