import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {toLocal,toLonLat,inside,collision,groundHeight} from '../geo.js';
const root=fileURLToPath(new URL('../',import.meta.url)),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8')),data=read('data/site.json'),source=read('data/sources.json'),failures=[],checks=[];
const check=(value,name)=>{checks.push({name,passed:!!value});if(!value)failures.push(name);};
for(const f of ['index.html','app.js','scene.js','buildings.js','materials.js','navigation.js','geo.js','style.css','viewer.css','vendor/three.module.js','vendor/three.core.min.js','vendor/OrbitControls.js','vendor/BufferGeometryUtils.js','vendor/Reflector.js','vendor/THREE-LICENSE.txt','data/osm-context.json','data/osm-poi.json','data/site.json','data/layout.geojson','data/sources.json'])check(fs.existsSync(path.join(root,f)),f+' exists');
for(const f of fs.readdirSync(root).filter(f=>f.endsWith('.js'))){const r=spawnSync(process.execPath,['--check',path.join(root,f)],{encoding:'utf8'});check(r.status===0,f+' parses');if(r.status!==0)console.error(r.stderr);}
check(data.unit==='metre','metre unit declared');check(data.buildings.length===62,'62 sourced building or compound records');check(data.buildings.every(b=>b.evidence&&b.footprint.length>=4),'every building has footprint and provenance');check(source.every(s=>s.date&&s.license&&s.coverage&&s.use),'source coverage/date/licence recorded');
check(data.zones.length===5&&data.places.length===16,'five precinct shortcuts and 16 destinations');check(data.city.extentMetres[0]>1700&&data.city.extentMetres[1]>1500,'expanded window spans all five precinct anchors');check(data.city.water.length===2&&data.city.roads.length===127,'source river polygons and city roads retained');check(data.heightGrid.values.length===data.heightGrid.cols*data.heightGrid.rows&&data.heightGrid.values.every(Number.isFinite),'finite terrain grid');check(groundHeight(data,...data.buildings.find(b=>b.id==='consulate').frame.centre)>25,'Maxian hill supported by archived DEM');check(groundHeight(data,...data.buildings.find(b=>b.id==='luoxing').frame.centre)>15,'Luoxing hill supported by archived DEM');
const local=toLocal(...data.origin);check(Math.hypot(...local)<1e-6,'WGS84 local origin');for(const p of data.boundary){const ll=toLonLat(...p),q=toLocal(...ll);check(Math.hypot(q[0]-p[0],q[1]-p[1])<.006,'ENU round-trip <6mm mathematical error');}
const coll=collision(data);for(const p of data.places){const safe=coll.safe(...p.eye);check(!coll.blocked(...safe),p.name+' has safe walking destination');}
// Independent, manually read plan centres are not the two fit anchors.
const points={engine:[573,848],iron:[1328,842],library:[795,846],theatre:[1114,500],pipe15:[649,602],pipe18:[589,395]},r=data.planRegistration;
const registration=Object.entries(points).map(([id,p])=>{const x=p[0]-r.anchor[0],z=p[1]-r.anchor[1],plan=[r.a*x+r.b*z,-r.b*x+r.a*z],b=data.buildings.find(b=>b.id===id),actual=b.footprint.reduce((a,v)=>[a[0]+v[0]/b.footprint.length,a[1]+v[1]/b.footprint.length],[0,0]);return {id,planCentrePixels:p,planCentreMetres:plan,osmVertexMeanMetres:actual,differenceMetres:+Math.hypot(plan[0]-actual[0],plan[1]-actual[1]).toFixed(2)};});
const report={date:'2026-10-07 Asia/Shanghai',checks,failures,registration,registrationLimit:'These differences compare two non-survey sources and manually read centres; not absolute geolocation accuracy or as-built dimension errors.'};
fs.writeFileSync(path.join(root,'evidence/data-checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:checks.filter(x=>x.passed).length,failed:failures,registration},null,2));if(failures.length)process.exitCode=1;
