import fs from 'node:fs';
import {toLocal,toLonLat,inside,distance,groundHeight} from '../geo.js';
const root=new URL('../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,root),'utf8')),data=read('data/site.json'),raw=read('data/osm-city-context.json'),poi=read('data/osm-expansion-poi.json'),dem=read('data/terrain.json'),rivers=read('data/osm-river-polygons.json');
if(data.coreBoundary)throw Error('Run data:prepare before expanding; expansion is not additive twice.');
const bbox=[119.438,25.9818,119.4557,25.996],sw=toLocal(bbox[0],bbox[1]),ne=toLocal(bbox[2],bbox[3]),limits=[sw[0],ne[1],ne[0],sw[1]];
data.coreBoundary=data.boundary;data.coreBoundaryLonLat=data.boundaryLonLat;data.boundary=[[limits[0],limits[1]],[limits[2],limits[1]],[limits[2],limits[3]],[limits[0],limits[3]]];data.boundaryLonLat=data.boundary.map(p=>toLonLat(...p));data.title='福州马尾船政 · 五大片区';
const fromGeo=g=>g.map(n=>toLocal(n.lon,n.lat));
const centre=p=>p.reduce((a,v)=>[a[0]+v[0]/p.length,a[1]+v[1]/p.length],[0,0]);
const frame=p=>{let best=-1,heading=0;for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length],len=Math.hypot(q[0]-p[i][0],q[1]-p[i][1]);if(len>best){best=len;heading=-Math.atan2(q[1]-p[i][1],q[0]-p[i][0]);}}const c=Math.cos(heading),s=Math.sin(heading),q=p.map(v=>[c*v[0]-s*v[1],s*v[0]+c*v[1]]),xs=q.map(v=>v[0]),zs=q.map(v=>v[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),u=(minX+maxX)/2,v=(minZ+maxZ)/2,x=c*u+s*v,z=-s*u+c*v,{a,b,scale,anchor}=data.planRegistration;return {x:(a*x-b*z)/(scale*scale)+anchor[0],y:(b*x+a*z)/(scale*scale)+anchor[1],width:maxX-minX,depth:maxZ-minZ,angle:heading,centre:[x,z]};};
function clip(points){let p=points;for(const [axis,value,lower] of [[0,limits[0],true],[0,limits[2],false],[1,limits[1],true],[1,limits[3],false]]){const next=[];for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],ia=lower?a[axis]>=value:a[axis]<=value,ib=lower?b[axis]>=value:b[axis]<=value;if(ia)next.push(a);if(ia!==ib){const t=(value-a[axis])/(b[axis]-a[axis]);next.push([a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t]);}}p=next;}return p;}
function rings(members,role){const unused=members.filter(m=>m.role===role&&m.geometry?.length).map(m=>m.geometry.map(n=>[n.lon,n.lat])),out=[];while(unused.length){let p=unused.shift(),joined=true;const same=(a,b)=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1])<1e-9;while(joined&&!same(p[0],p.at(-1))){joined=false;for(let i=0;i<unused.length;i++){let q=unused[i];if(same(p.at(-1),q.at(-1)))q=[...q].reverse();if(same(p.at(-1),q[0])){p.push(...q.slice(1));unused.splice(i,1);joined=true;break;}if(same(p[0],q[0]))q=[...q].reverse();if(same(p[0],q.at(-1))){p=[...q.slice(0,-1),...p];unused.splice(i,1);joined=true;break;}}}if(same(p[0],p.at(-1)))out.push(p.slice(0,-1).map(q=>toLocal(...q)));else throw Error('Unclosed river source ring');}return out;}
const water=[];for(const r of rivers.elements){const holes=rings(r.members,'inner').map(clip).filter(h=>h.length>=3);for(const p of rings(r.members,'outer').map(clip).filter(p=>p.length>=3))water.push({osmRelation:r.id,polygon:p,holes:holes.filter(h=>inside(h[0],p))});}
const existing=new Set(data.buildings.map(b=>b.osmId)),known={1470977355:['consulate','英国副领事署','colonial',4.2,1],1470977356:['prison','梅园监狱','colonial',4.0,1],1482480750:['hospitalA','圣教医院 A 座','colonial',7.8,2],1482480751:['hospitalB','圣教医院 B 座','colonial',7.8,2],1486253390:['dean','圣教医院院长公寓','colonial',7.2,2],1470977347:['oldMuseum','船政文化博物馆旧馆 · 已停用','context',16,5],1471591718:['auditorium','马尾造船厂礼堂','industrial',6,1],1470977343:['cutting','原切割车间 · 现商业使用','industrial',6,1],1470977337:['post','船政邮局','context',7.2,2],1470977348:['memorialPavilion','追思亭','pavilion',5,1],1470977354:['plumPavilion','梅园阁','pavilion',5,1]};
function addBuilding(id,name,p,kind='context',height=7.2,levels=2,props={}){const f=frame(p),evidence={layout:'有数据支持 · OSM轮廓 / 关系外环',facade:kind==='context'?'暂缺资料 · 仅体量':'暂缺资料 · 官方文字支持形制；多面照片、门窗净尺寸及未见立面待核',height:'估算；有明确尺寸的构件另记',accuracy:'扩展区不是实测复原'};data.buildings.push({id,name,footprint:p,renderFootprint:p,height,roofRise:kind==='colonial'?1.9:1.3,levels,completion:kind==='pagoda'?'photo':'mass',kind,frame:f,evidence,...props});}
for(const e of raw.elements.filter(e=>e.tags.building&&e.geometry&&!existing.has(e.id))){const p=fromGeo(e.geometry.slice(0,-1));if(!p.length||!inside(centre(p),data.boundary))continue;const k=known[e.id];addBuilding(k?.[0]||'osm-'+e.id,k?.[1]||e.tags.name||'地图建筑 '+e.id,p,k?.[2]||'context',k?.[3]||Number(e.tags.height)||Number(e.tags['building:levels']||2)*3.3,k?.[4]||Number(e.tags['building:levels']||2),{osmId:e.id,osmTimestamp:e.timestamp,sourceTags:e.tags});}
const relations={20140073:['yamen','总理船政衙门 · 现代复建','yamen',5,1],20140074:['frontSchool','船政前学堂 · 现代复建','school',8.2,2],20140075:['rearSchool','船政后学堂 · 现代复建','school',8.2,2],20140076:['zhaozhong','昭忠祠 · 马江海战纪念馆','memorial',5.5,1]};
for(const [id,k] of Object.entries(relations)){const r=poi.elements.find(e=>e.id===Number(id)),outers=rings(r.members,'outer'),holes=rings(r.members,'inner');outers.forEach((p,i)=>addBuilding(i?k[0]+'-'+i:k[0],k[1],p,k[2],k[3],k[4],{osmRelation:r.id,osmTimestamp:r.timestamp,holes:holes.filter(h=>inside(h[0],p))}));}
const temple=raw.elements.find(e=>e.id===1470977357);addBuilding('tianhou','船政天后宫 · 现代复建',fromGeo(temple.geometry.slice(0,-1)),'temple',7,1,{osmId:temple.id,footprintType:'compound landuse boundary; internal roof bands approximated',evidence:{layout:'有数据支持 · OSM宗教用地边界，不是各殿屋顶测量',facade:'形制近似 · 一轴二进二院与木构官方资料',height:'估算；总建筑面积1500m²文字未用作全部场地面积'}});
const memorial=data.buildings.find(b=>b.id==='zhaozhong'),mf=memorial.frame;[mf.width,mf.depth]=[mf.depth,mf.width];mf.angle-=Math.PI/2;memorial.evidence.facade='形制近似 · 官方25.1m面阔 / 37m进深、五开间和风火山墙；屋顶与门扇净尺寸估算';
const tower=poi.elements.find(e=>e.id===3512322824),tc=toLocal(tower.lon,tower.lat),tp=Array.from({length:8},(_,i)=>[tc[0]+Math.cos(i*Math.PI/4)*4.3,tc[1]+Math.sin(i*Math.PI/4)*4.3]);addBuilding('luoxing','罗星塔',tp,'pagoda',31.5,7,{osmNode:tower.id,osmTimestamp:tower.timestamp,evidence:{layout:'有数据支持 · OSM塔中心点；直径8.6m来自官方资料',facade:'照片近似 · 2022自然资源规划局航拍，七层八角、栏杆和石塔',height:'采用规划局31.5m；区文体局写通高30m，口径差异未测定'}});
const parks=raw.elements.filter(e=>e.tags.leisure==='park').map(e=>({osmId:e.id,name:e.tags.name||'公园',polygon:clip(fromGeo(e.geometry.slice(0,-1)))})).filter(p=>p.polygon.length>=3);
const grass=raw.elements.filter(e=>e.tags.landuse==='grass').map(e=>({osmId:e.id,polygon:clip(fromGeo(e.geometry.slice(0,-1)))})).filter(p=>p.polygon.length>=3);
const pools=raw.elements.filter(e=>e.tags.natural==='water'&&e.tags.water==='pond').map(e=>({id:'pond-'+e.id,name:e.tags.name||'景观水池',polygon:fromGeo(e.geometry.slice(0,-1)),osmId:e.id}));
const docks=raw.elements.filter(e=>e.tags.waterway==='dock').map(e=>({osmId:e.id,name:e.tags.name,polygon:fromGeo(e.geometry.slice(0,-1))}));
const roads=raw.elements.filter(e=>e.tags.highway&&e.geometry&&!e.tags.tunnel&&!['construction','proposed'].includes(e.tags.highway)).map(e=>({osmId:e.id,name:e.tags.name||'公共通道',type:e.tags.highway,width:Number(e.tags.width)||({primary:17,secondary:12,tertiary:9,residential:6,unclassified:6,pedestrian:5,footway:2.2,steps:2.2}[e.tags.highway]||5),estimatedWidth:!e.tags.width,points:fromGeo(e.geometry),footAllowed:e.tags.foot}));
data.city={bbox,water,parks,grass,pools,docks,roads,sourceDate:raw.osm3s.timestamp_osm_base,extentMetres:[limits[2]-limits[0],limits[3]-limits[1]],scopeNote:'五大片区及连接道路的建模窗口；不是官方111公顷保护边界；公共通行状态不由模型保证'};
function bareHeight(x,z){const u=Math.max(0,Math.min(dem.cols-1.000001,(x-dem.minX)/dem.step)),v=Math.max(0,Math.min(dem.rows-1.000001,(z-dem.minZ)/dem.step)),i=Math.floor(u),j=Math.floor(v),fx=u-i,fz=v-j,k=j*dem.cols+i;return Math.max(0,(dem.values[k]*(1-fx)+dem.values[k+1]*fx)*(1-fz)+(dem.values[k+dem.cols]*(1-fx)+dem.values[k+dem.cols+1]*fx)*fz-dem.referenceElevation);}
for(const b of data.buildings){const c=b.frame.centre||centre(b.footprint);b.baseHeight=b.kind&&!inside(c,data.coreBoundary)?bareHeight(...c):0;b.zone=b.kind?'expanded':'shipyard';if(b.kind&&b.kind!=='context'){const f=b.frame,c=f.centre,co=Math.cos(f.angle),si=Math.sin(f.angle);b.renderFootprint=[[-f.width/2-1,-f.depth/2-1],[f.width/2+1,-f.depth/2-1],[f.width/2+1,f.depth/2+1],[-f.width/2-1,f.depth/2+1]].map(([u,v])=>[c[0]+co*u+si*v,c[1]-si*u+co*v]);}}
for(const ids of [['frontSchool','frontSchool-1'],['hospitalA','hospitalB']]){const list=data.buildings.filter(b=>ids.includes(b.id)),h=Math.max(...list.map(b=>b.baseHeight));list.forEach(b=>{b.baseHeight=h;b.evidence.ground='共同地坪估算，消除粗DEM造成的相邻楼体虚假高差';});}
for(const p of [...pools,...docks]){p.baseHeight=bareHeight(...centre(p.polygon));p.depthEstimate=docks.includes(p)?1.4:.16;}
const pads=[...data.buildings.filter(b=>b.kind).map(b=>({polygon:b.renderFootprint,height:b.baseHeight})),...[...pools,...docks].map(p=>({polygon:p.polygon,height:p.baseHeight}))].map(p=>({...p,bounds:[Math.min(...p.polygon.map(q=>q[0]))-18,Math.min(...p.polygon.map(q=>q[1]))-18,Math.max(...p.polygon.map(q=>q[0]))+18,Math.max(...p.polygon.map(q=>q[1]))+18]}));
// 6m tessellation samples the coarser archived DEM; it does not increase source accuracy.
const grid={minX:dem.minX,minZ:dem.minZ,step:6,cols:(dem.cols-1)*2+1,rows:(dem.rows-1)*2+1,values:[]};
for(let j=0;j<grid.rows;j++)for(let i=0;i<grid.cols;i++){const x=grid.minX+i*grid.step,z=grid.minZ+j*grid.step,p=[x,z];let y=bareHeight(x,z);if(inside(p,data.coreBoundary))y=-.12;else{let nearest=null,best=18;for(const pad of pads){if(x<pad.bounds[0]||x>pad.bounds[2]||z<pad.bounds[1]||z>pad.bounds[3])continue;const dist=inside(p,pad.polygon)?0:Math.min(...pad.polygon.map((a,k)=>distance(p,a,pad.polygon[(k+1)%pad.polygon.length])));if(dist<best){best=dist;nearest=pad;}}if(nearest)y=nearest.height+(y-nearest.height)*Math.max(0,(best-8)/10);for(const feature of [...pools,...docks])if(inside(p,feature.polygon))y=feature.baseHeight-feature.depthEstimate;}if(water.some(w=>inside(p,w.polygon)&&!w.holes.some(h=>inside(p,h))))y=-3.1;grid.values.push(+y.toFixed(3));}
data.heightGrid=grid;data.terrain={...dem,values:undefined};data.verticalDatum='Mapzen archive relative to factory origin; core flattened to0, building pads locally flattened; tide/retaining-wall heights estimated';
for(const p of parks.filter(p=>[444492939,435074409].includes(p.osmId))){const xs=p.polygon.map(p=>p[0]),zs=p.polygon.map(p=>p[1]);for(let x=Math.min(...xs)+8;x<Math.max(...xs);x+=18)for(let z=Math.min(...zs)+8;z<Math.max(...zs);z+=18){if(!inside([x,z],p.polygon)||data.buildings.some(b=>inside([x,z],b.footprint)||b.footprint.some((a,i)=>distance([x,z],a,b.footprint[(i+1)%b.footprint.length])<9))||roads.some(r=>r.points.some((a,i)=>i&&distance([x,z],r.points[i-1],a)<5)))continue;data.trees.push({position:[x,z],height:13,radius:6.8,baseHeight:groundHeight(data,x,z),source:'公园边界内规则采样的树冠覆盖近似；非逐树定位、无随机位置'});}}
for(const e of raw.elements.filter(e=>e.type==='node'&&e.tags.natural==='tree'))data.trees.push({position:toLocal(e.lon,e.lat),height:12,radius:5,baseHeight:groundHeight(data,...toLocal(e.lon,e.lat)),source:'OSM individual tree; canopy estimated'});
const targetFor=id=>centre(data.buildings.find(b=>b.id===id).footprint),newPlaces=[['guanjie','船政官街',toLocal(119.4405,25.99365),toLocal(119.44018,25.9941),'2026-05焕新；街道线有地图依据，商铺逐栋立面与轮廓仍缺资料'],['yamen','总理船政衙门',null,targetFor('yamen'),'现代复建建筑 · OSM外环和院落，灰墙瓦顶形制近似'],['frontSchool','船政前后学堂',null,targetFor('frontSchool'),'现代复建洋楼 · 真实轮廓、两层廊式形制近似'],['tianhou','船政天后宫',null,targetFor('tianhou'),'现代复建木构寺庙 · 用地轮廓有据，殿宇分区估算'],['zhaozhong','昭忠祠 · 马江海战纪念馆',null,targetFor('zhaozhong'),'五开间、院落和风火山墙形制近似'],['consulate','马限山 · 英国副领事署',null,targetFor('consulate'),'现代保留建筑 · 地形采用公开DEM，未作实测'],['hospitalA','圣教医院建筑群',null,targetFor('hospitalA'),'A/B座位置有地图支持 · 两层砖木体量'],['dock2','旧港 · 二号船坞',toLocal(119.44365,25.9881),centre(docks[0].polygon),'仅加入已核对的二号船坞；一号船坞准确边界仍待资料'],['luoxing','罗星塔公园',null,tc,'八角七层石塔 · 官方总高口径30/31.5m；栏杆构件近似']];
for(const [id,name,eye,target,note] of newPlaces){const b=data.buildings.find(b=>b.id===id),f=b?.frame,p=eye||(f?[target[0]-Math.sin(f.angle)*((f.depth||20)/2+13),target[1]-Math.cos(f.angle)*((f.depth||20)/2+13)]:[target[0]-15,target[1]+20]);data.places.push({id,name,eye:p,target,label:target,labelHeight:(b?.baseHeight||groundHeight(data,...target))+(b?.height||5)+2,note,distance:id==='luoxing'?85:65});}
data.zones=[{id:'shipyard',name:'船厂',place:'huyuan',description:'绘事院 · 博物馆 · 铁胁厂'},{id:'guanjie',name:'官街',place:'guanjie',description:'船政官街 · 格致园'},{id:'maxian',name:'马限山',place:'consulate',description:'昭忠祠 · 梅园 · 近代建筑群'},{id:'oldPort',name:'旧港',place:'dock2',description:'二号船坞 · 滨江道路'},{id:'luoxing',name:'罗星塔',place:'luoxing',description:'石塔 · 公园 · 滨江步道'}];
for(const b of data.buildings.filter(b=>b.kind))b.evidence.categories={layout:'有数据支持',facade:b.kind==='pagoda'?'照片近似':'暂缺资料',detail:'暂缺资料'};
data.referenceDate+='；扩展区OSM'+data.city.sourceDate+'，官街2026-05开放资料补核，DEM为历史合成档案';data.summary={...data.summary,buildings:data.buildings.length,trees:data.trees.length,roads:roads.length,zones:5};data.missing=['2026正射航片与竣工测量控制','钟楼与一号船坞精确位置 / 边界','官街2026更新后商铺逐栋轮廓和立面','公园逐树位置、灯具与设备定位','扩展区建筑背立面及精细材质','DEM不是现状实测，不能给出地形测量精度'];
fs.writeFileSync(new URL('data/site.json',root),JSON.stringify(data,null,2));
const features=[{type:'Feature',properties:{name:'五大片区建模窗口（不是保护红线）'},geometry:{type:'Polygon',coordinates:[[...data.boundaryLonLat,data.boundaryLonLat[0]]]}},{type:'Feature',properties:{name:'原首期船厂细节范围'},geometry:{type:'Polygon',coordinates:[[...data.coreBoundaryLonLat,data.coreBoundaryLonLat[0]]]}},...data.buildings.map(b=>({type:'Feature',properties:{id:b.id,name:b.name,osmId:b.osmId||b.osmRelation||b.osmNode||null,completion:b.completion,estimatedHeight:b.height,baseHeight:b.baseHeight,kind:b.kind||'core'},geometry:{type:'Polygon',coordinates:[[...b.footprint.map(p=>toLonLat(...p)),toLonLat(...b.footprint[0])],...(b.holes||[]).map(h=>[...h.map(p=>toLonLat(...p)),toLonLat(...h[0])])]}})),...water.map(w=>({type:'Feature',properties:{osmRelation:w.osmRelation,name:'闽江水域'},geometry:{type:'Polygon',coordinates:[[...w.polygon.map(p=>toLonLat(...p)),toLonLat(...w.polygon[0])],...w.holes.map(h=>[...h.map(p=>toLonLat(...p)),toLonLat(...h[0])])]}}))];
fs.writeFileSync(new URL('data/layout.geojson',root),JSON.stringify({type:'FeatureCollection',features},null,2));
console.log(JSON.stringify({summary:data.summary,extent:data.city.extentMetres,waterRings:water.length,newBuildings:data.buildings.filter(b=>b.kind).map(b=>({id:b.id,name:b.name,baseHeight:b.baseHeight}))},null,2));
