import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createWorld} from './world.js';
import './style.css';

const $=s=>document.querySelector(s);const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.12,12000);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(error){$('#load-text').textContent='无法启动 WebGL。请启用浏览器硬件加速后重试。';throw error;}
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('#scene').append(renderer.domElement);
scene.fog=new THREE.FogExp2(0xb7cbd3,.00018);
const sunDirection=new THREE.Vector3(-.55,.84,.3).normalize();
const sky=new THREE.Mesh(new THREE.SphereGeometry(8000,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,toneMapped:false,uniforms:{sunDirection:{value:sunDirection}},vertexShader:`varying vec3 vDirection; void main(){ vec4 w=modelMatrix*vec4(position,1.0); vDirection=w.xyz-cameraPosition; gl_Position=projectionMatrix*viewMatrix*w; }`,fragmentShader:`uniform vec3 sunDirection; varying vec3 vDirection; void main(){ vec3 d=normalize(vDirection); float h=clamp(d.y*2.0,0.0,1.0); vec3 horizon=vec3(0.57,0.70,0.81); vec3 zenith=vec3(0.27,0.48,0.74); vec3 c=mix(horizon,zenith,pow(h,0.75)); float glow=pow(max(dot(d,normalize(sunDirection)),0.0),22.0); c+=vec3(0.19,0.16,0.11)*glow; gl_FragColor=vec4(c,1.0);
#include <colorspace_fragment>
}`}));scene.add(sky);
const envScene=new THREE.Scene();const envSky=sky.clone();envScene.add(envSky);const pmrem=new THREE.PMREMGenerator(renderer);const environment=pmrem.fromScene(envScene,.04,.1,20000);scene.environment=environment.texture;scene.environmentIntensity=.22;pmrem.dispose();
scene.add(new THREE.HemisphereLight(0xc7dbea,0x76806a,1.15));
const sun=new THREE.DirectionalLight(0xfff5e5,2.55);scene.add(sun);scene.add(sun.target);sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-120;sun.shadow.camera.right=120;sun.shadow.camera.top=120;sun.shadow.camera.bottom=-120;sun.shadow.camera.near=1;sun.shadow.camera.far=900;sun.shadow.bias=-.0002;sun.shadow.normalBias=.15;
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.085;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=9;controls.maxDistance=3600;controls.zoomToCursor=true;controls.screenSpacePanning=false;
let mode='orbit',quality='medium',world,ready=false,yaw=0,pitch=0,dragging=false,downPoint=null,frameId,last=performance.now(),lastStats=last,frameTimes=[],touchActive=false;
const keys=new Set();const up=new THREE.Vector3(0,1,0);
function updateProgress(n,text){$('progress').value=n;$('#load-text').textContent=text;}
function look(){camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);}
function showInfo(l){$('#info').hidden=false;$('#info h2').textContent=l.name;$('#info p').textContent=l.description;$('#info a').href=l.source;}
function settleOrbit(){controls.enableDamping=false;controls.update();controls.enableDamping=true;}
function choose(l,info=true){keys.clear();document.querySelectorAll('#spots button').forEach(b=>b.classList.toggle('selected',b.dataset.spot===l.id));if(mode==='walk'){let offset=l.id==='qinian'?62:l.id==='vault'?47:l.id==='altar'?46:l.id==='bridge'?40:Math.min(l.d/2+14,95);let x=l.x,z=l.z+offset;if(l.id==='palace'||l.id==='music'){x=l.x+l.w/2-15;z=l.z;}
 // Search locally for a free landing position, never teleport into walls.
 if(!world.canStand(x,z)){let found=false;for(let r=5;r<90&&!found;r+=5)for(let t=0;t<16;t++){const xx=x+Math.sin(t/16*Math.PI*2)*r,zz=z+Math.cos(t/16*Math.PI*2)*r;if(world.canStand(xx,zz)){x=xx;z=zz;found=true;break;}}}
 camera.position.set(x,world.ground(x,z)+1.7,z);yaw=Math.atan2(x-l.x,z-l.z);pitch=-.04;look();
 }else{let dist=l.id==='qinian'?125:l.id==='vault'?90:l.id==='altar'?130:l.id==='bridge'?240:Math.max(l.w,l.d)*1.2;if(innerWidth/innerHeight<.7)dist*=2.2;settleOrbit();camera.position.set(l.x+dist*.65,l.ground+dist*.52,l.z+dist*.84);controls.target.set(l.x,l.ground+(l.id==='qinian'?16:5),l.z);controls.update();}if(info)showInfo(l);}
function setMode(next){mode=next;keys.clear();controls.enabled=mode==='orbit';$('#orbit').classList.toggle('active',mode==='orbit');$('#walk').classList.toggle('active',mode==='walk');$('#hint').textContent=mode==='walk'?'WASD 行走 · Shift 快走 · 拖动 / 点击画面锁定视角 · Esc 释放':'拖动旋转 · 滚轮缩放 · 右键平移';document.querySelector('.crosshair')?.remove();if(mode==='walk'){const cross=document.createElement('div');cross.className='crosshair';document.body.append(cross);const l=world.landmarks.find(l=>document.querySelector(`#spots [data-spot="${l.id}"]`)?.classList.contains('selected'))||world.landmarks[0];choose(l,false);}else{if(document.pointerLockElement)document.exitPointerLock();controls.target.copy(camera.position).add(camera.getWorldDirection(new THREE.Vector3()).multiplyScalar(35));camera.position.y=Math.max(camera.position.y,18);controls.update();}}
function fullPark(){if(mode==='walk')setMode('orbit');settleOrbit();camera.position.set(700,1550,1570);controls.target.set(-200,0,230);controls.update();$('#info').hidden=true;document.querySelectorAll('#spots button').forEach(b=>b.classList.remove('selected'));}
function reset(){if(mode==='walk')setMode('orbit');choose(world.landmarks[0],false);$('#info').hidden=true;}
function setQuality(value){quality=value;renderer.setPixelRatio(value==='low'?Math.min(devicePixelRatio*.75,1):value==='high'?Math.min(devicePixelRatio*1.5,2):Math.min(devicePixelRatio,1.25));renderer.shadowMap.enabled=value!=='low';sun.castShadow=value!=='low';sun.shadow.mapSize.set(value==='high'?3072:2048,value==='high'?3072:2048);sun.shadow.map?.dispose();sun.shadow.map=null;scene.fog.density=value==='low'?.00032:.00018;for(const lod of world?.treeLODs||[])lod.levels[1].distance=value==='low'?120:value==='high'?420:300;for(const ridge of world?.roofRidges||[])ridge.visible=value!=='low';resize();}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
function move(dt){const forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);const side=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);if(!forward&&!side)return;const n=Math.hypot(forward,side),speed=(keys.has('ShiftLeft')?8:4.5)*dt/n;const dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*speed;const steps=Math.ceil(Math.hypot(dx,dz)/.15);for(let i=0;i<steps;i++){const y=world.ground(camera.position.x,camera.position.z);const x=camera.position.x+dx/steps,z=camera.position.z+dz/steps;if(world.canStand(x,z,y)){camera.position.x=x;camera.position.z=z;}else if(world.canStand(x,camera.position.z,y))camera.position.x=x;else if(world.canStand(camera.position.x,z,y))camera.position.z=z;camera.position.y=world.ground(camera.position.x,camera.position.z)+1.7;}}
const ns='http://www.w3.org/2000/svg';function svg(tag,attrs,parent=$('#map')){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);parent.append(e);return e;}
let dot,heading;
function buildMap(){svg('polygon',{points:world.data.boundary.map(p=>p.join(',')).join(' '),fill:'#d9e2cc',stroke:'#617a68','stroke-width':9});for(const r of world.roads)svg('line',{x1:r.a[0],y1:r.a[1],x2:r.b[0],y2:r.b[1],stroke:'#f8f8ee','stroke-width':r.width*2});svg('line',{x1:world.bridge.center(world.bridge.north),y1:world.bridge.north,x2:world.bridge.center(world.bridge.south),y2:world.bridge.south,stroke:'#b6ab85','stroke-width':30});for(const l of world.landmarks){const g=svg('g',{class:'marker',tabindex:0,role:'button','aria-label':l.name});svg('circle',{cx:l.x,cy:l.z,r:l.id==='qinian'?18:13,fill:'#8c6836',stroke:'#fff','stroke-width':5},g);const t=svg('text',{x:l.x+23,y:l.z-15},g);t.textContent=l.id==='vault'?'皇穹宇':l.name;g.addEventListener('click',()=>choose(l));g.addEventListener('keydown',e=>{if(e.key==='Enter')choose(l);});}heading=svg('path',{d:'M0,-40 L-15,0 L15,0 Z',fill:'#317a83',opacity:.8});dot=svg('circle',{r:13,fill:'#187a88',stroke:'#fff','stroke-width':5});}
function frame(time){if(!ready)return;const dt=Math.min((time-last)/1000,.05);last=time;if(mode==='walk')move(dt);else{controls.update();camera.position.y=Math.max(camera.position.y,world.ground(camera.position.x,camera.position.z)+1.7);}const target=mode==='walk'?camera.position:controls.target;sun.target.position.set(target.x,0,target.z);sun.position.copy(sun.target.position).addScaledVector(sunDirection,450);sun.target.updateMatrixWorld();for(const lod of world.treeLODs)lod.update(camera);renderer.render(scene,camera);dot.setAttribute('cx',camera.position.x);dot.setAttribute('cy',camera.position.z);const dir=camera.getWorldDirection(new THREE.Vector3());heading.setAttribute('transform',`translate(${camera.position.x},${camera.position.z}) rotate(${Math.atan2(dir.x,-dir.z)*180/Math.PI})`);frameTimes.push(dt*1000);if(time-lastStats>1000){const mean=frameTimes.reduce((a,b)=>a+b)/frameTimes.length;$('#stats').textContent=`${Math.round(1000/mean)} FPS · ${renderer.info.render.calls} calls · ${mode==='walk'?'视高 1.7 m':'北 ↑'}`;frameTimes=[];lastStats=time;}frameId=requestAnimationFrame(frame);}
renderer.domElement.addEventListener('pointerdown',e=>{downPoint=[e.clientX,e.clientY];if(mode==='walk'){dragging=true;renderer.domElement.setPointerCapture(e.pointerId);}});
renderer.domElement.addEventListener('pointermove',e=>{if(mode==='walk'&&(dragging||document.pointerLockElement===renderer.domElement)){yaw-=e.movementX*.0025;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0025,-1.4,1.4);look();}});
renderer.domElement.addEventListener('pointerup',e=>{dragging=false;if(!downPoint||Math.hypot(e.clientX-downPoint[0],e.clientY-downPoint[1])>5)return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=ray.intersectObjects(world?.pickables||[])[0];if(hit)showInfo(hit.object.userData.landmark);if(mode==='walk'&&e.pointerType==='mouse'&&!document.pointerLockElement)renderer.domElement.requestPointerLock()?.catch(()=>{});});
renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frameId);$('#loading').style.display='flex';$('#load-text').textContent='图形上下文已丢失，请刷新页面重建场景。';});
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)||$('#source-dialog').open)return;if(mode==='walk'&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft'].includes(e.code)){e.preventDefault();keys.add(e.code);}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();dragging=false;});document.addEventListener('pointerlockchange',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();last=performance.now();});window.addEventListener('resize',resize);
$('#orbit').onclick=()=>setMode('orbit');$('#walk').onclick=()=>setMode('walk');$('#all').onclick=fullPark;$('#reset').onclick=reset;$('#quality').onchange=e=>setQuality(e.target.value);$('#close-info').onclick=()=>$('#info').hidden=true;$('#sources').onclick=()=>{keys.clear();if(document.pointerLockElement)document.exitPointerLock();$('#source-dialog').showModal();};$('#close-sources').onclick=()=>$('#source-dialog').close();$('.brand').onclick=e=>{e.preventDefault();reset();};
async function start(){try{updateProgress(15,'读取公园地图与尺度基准…');const response=await fetch(`${import.meta.env.BASE_URL}data/layout.json`);if(!response.ok)throw new Error('地图资源加载失败');const data=await response.json();updateProgress(30,'构建建筑曲面、道路与古柏林…');await new Promise(r=>requestAnimationFrame(r));world=createWorld(scene,data);updateProgress(85,'准备游览与材质…');world.landmarks.forEach((l,i)=>{const b=document.createElement('button');b.dataset.spot=l.id;b.innerHTML=`${l.name}<span>0${i+1} ↗</span>`;b.onclick=()=>choose(l);$('#spots').append(b);const a=document.createElement('a');a.href=l.source;a.target='_blank';a.rel='noreferrer';a.textContent=l.name+' · 资料来源 ↗';$('#source-links').append(a);});const osm=document.createElement('a');osm.href='https://www.openstreetmap.org/copyright';osm.textContent='地图数据 © OpenStreetMap contributors / ODbL 1.0 ↗';osm.target='_blank';$('#source-links').append(osm);buildMap();setQuality(quality);reset();await renderer.compileAsync(scene,camera);ready=true;updateProgress(100,'可以开始游览');window.__tiantan={ready:true,renderer,camera,scene,world,controls,choose,setMode,fullPark,reset,get mode(){return mode;},get yaw(){return yaw;},get quality(){return quality;},setWalkPose(x,z,yaw0=0,pitch0=0){mode='walk';controls.enabled=false;camera.position.set(x,world.ground(x,z)+1.7,z);yaw=yaw0;pitch=pitch0;look();}};$('#loading').style.display='none';last=lastStats=performance.now();frameId=requestAnimationFrame(frame);}catch(error){console.error(error);$('#load-text').textContent='加载失败：'+error.message+'。请检查本地资源或重新启动服务器。';}}
start();
window.addEventListener('pagehide',()=>{cancelAnimationFrame(frameId);controls.dispose();const geos=new Set(),mats=new Set(),textures=new Set();scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material]){mats.add(m);for(const v of Object.values(m))if(v?.isTexture)textures.add(v);}});geos.forEach(g=>g.dispose());textures.forEach(t=>t.dispose());mats.forEach(m=>m.dispose());renderer.dispose();});
