import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';

export const inside=(p,poly)=>{let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;};
export function bounds(points){const xs=points.map(p=>p[0]),zs=points.map(p=>p[1]);const x0=Math.min(...xs),x1=Math.max(...xs),z0=Math.min(...zs),z1=Math.max(...zs);return{x:(x0+x1)/2,z:(z0+z1)/2,w:x1-x0,d:z1-z0};}
export function distanceSegment(x,z,a,b){const dx=b[0]-a[0],dz=b[1]-a[1],t=T.MathUtils.clamp(((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz||1),0,1);return Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz);}
export function createWorld(scene,data){
 const solids=[],surfaces=[],wallSegments=[],roads=[],pickables=[],treeLODs=[],roofRidges=[],groups=new Map();let seed=1420;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 function texture(kind){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),N=512;const base={stone:'#d5d2c6',brick:'#7c4238',roof:'#486896',grass:'#617253',bark:'#675745',paint:'#244f75'}[kind];ctx.fillStyle=base;ctx.fillRect(0,0,N,N);const noiseCount=kind==='roof'?18000:kind==='grass'?38000:kind==='stone'?9000:15000;for(let i=0;i<noiseCount;i++){const v=Math.floor(random()*90),light=random()>.5;ctx.fillStyle=`rgba(${light?255:22},${light?255:24},${light?255:25},${(kind==='stone'?.012:.019)+v/12000})`;const s=kind==='grass'?random()*6+1:random()*2+.5;ctx.fillRect(random()*N,random()*N,s,s);}if(kind==='stone'){ctx.strokeStyle='rgba(104,111,109,.23)';ctx.lineWidth=1;for(let y=0;y<N;y+=96){ctx.beginPath();ctx.moveTo(0,y+random()*3);ctx.lineTo(N,y+random()*3);ctx.stroke();for(let x=((y/96)%2)*96;x<N;x+=192){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+96);ctx.stroke();}}for(let i=0;i<45;i++){ctx.strokeStyle=`rgba(92,100,97,${random()*.055})`;ctx.beginPath();const x=random()*N,y=random()*N;ctx.moveTo(x,y);ctx.bezierCurveTo(x+10,y+6,x-4,y+18,x+28,y+32);ctx.stroke();}}if(kind==='brick'){ctx.strokeStyle='rgba(30,26,25,.36)';ctx.lineWidth=3;for(let y=0;y<N;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(N,y);ctx.stroke();for(let x=(y/40%2)*64;x<N;x+=128){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+40);ctx.stroke();}}}if(kind==='roof'){for(let x=0;x<N;x+=16){const grad=ctx.createLinearGradient(x,0,x+16,0);grad.addColorStop(0,'rgba(10,27,55,.35)');grad.addColorStop(.32,'rgba(131,165,194,.2)');grad.addColorStop(.63,'rgba(58,98,149,.18)');grad.addColorStop(1,'rgba(8,27,52,.38)');ctx.fillStyle=grad;ctx.fillRect(x,0,16,N);}for(let y=0;y<N;y+=24){ctx.fillStyle='rgba(8,20,38,.2)';ctx.fillRect(0,y, N,2);ctx.fillStyle='rgba(126,150,180,.11)';ctx.fillRect(0,y+2,N,2);}}if(kind==='bark'){for(let i=0;i<160;i++){const x=random()*N,y=random()*N;ctx.strokeStyle=`rgba(${random()>.5?'24,19,17':'183,161,124'},${random()*.13})`;ctx.lineWidth=random()*3+.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+random()*5-2,y+20+random()*75);ctx.stroke();}}if(kind==='paint'){for(let y=0;y<N;y+=128){ctx.fillStyle='#315c82';ctx.fillRect(0,y,N,126);ctx.fillStyle='#9b9b73';ctx.fillRect(0,y+6,N,4);ctx.fillRect(0,y+116,N,4);for(let x=0;x<N;x+=64){ctx.strokeStyle='#98a6a2';ctx.lineWidth=3;ctx.strokeRect(x+7,y+24,50,78);ctx.strokeStyle='#9f8451';ctx.lineWidth=2;ctx.strokeRect(x+13,y+31,38,64);ctx.beginPath();ctx.ellipse(x+32,y+63,13,23,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(215,217,185,.6)';for(let k=0;k<4;k++){ctx.beginPath();ctx.moveTo(x+32,y+63);ctx.lineTo(x+32+Math.cos(k*Math.PI/2)*16,y+63+Math.sin(k*Math.PI/2)*21);ctx.stroke();}}}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;return t;}
 const stoneTex=texture('stone'),roofTex=texture('roof'),brickTex=texture('brick'),grassTex=texture('grass'),barkTex=texture('bark'),paintTex=texture('paint');
 paintTex.repeat.set(.125,.25);
 const mat={stone:new T.MeshStandardMaterial({color:0xe4e2d9,map:stoneTex,roughness:.91}),pave:new T.MeshStandardMaterial({color:0xd5d2c5,map:stoneTex,roughness:.98}),red:new T.MeshStandardMaterial({color:0x963c2d,roughness:.72}),brick:new T.MeshStandardMaterial({color:0xb7a196,map:brickTex,roughness:.97}),blue:new T.MeshStandardMaterial({color:0xe2e8ee,map:roofTex,roughness:.46,metalness:.04}),green:new T.MeshStandardMaterial({color:0x8a9b88,map:roofTex,roughness:.55}),paint:new T.MeshStandardMaterial({color:0xd1dae1,map:paintTex,roughness:.76}),panel:new T.MeshStandardMaterial({color:0x819eac,roughness:.75}),soffit:new T.MeshBasicMaterial({color:0x182b48,side:T.DoubleSide}),indigo:new T.MeshStandardMaterial({color:0x253f6b,roughness:.71}),gold:new T.MeshStandardMaterial({color:0xc3a15f,metalness:.42,roughness:.45}),dark:new T.MeshStandardMaterial({color:0x2c2927,roughness:.93}),grass:new T.MeshStandardMaterial({color:0xa9b19a,map:grassTex,roughness:1}),outer:new T.MeshStandardMaterial({color:0x8f938e,roughness:1}),bark:new T.MeshStandardMaterial({color:0xc3afa0,map:barkTex,roughness:1}),leaves:new T.MeshStandardMaterial({color:0x879883,roughness:1}),water:new T.MeshStandardMaterial({color:0x637e75,roughness:.3,metalness:.12})};
 const cube=new T.BoxGeometry(1,1,1),cylinder=new T.CylinderGeometry(1,1,1,24),sphere=new T.SphereGeometry(1,12,8);const temp=new T.Object3D();
 function add(geo,m,x=0,y=0,z=0,sx=1,sy=1,sz=1,ry=0){temp.position.set(x,y,z);temp.rotation.set(0,ry,0);temp.scale.set(sx,sy,sz);temp.updateMatrix();const g=geo.clone().applyMatrix4(temp.matrix);if(!g.index)g.setIndex(Array.from({length:g.attributes.position.count},(_,i)=>i));if([mat.pave,mat.stone,mat.grass,mat.brick].includes(m)&&geo===cube){const p=g.attributes.position,n=g.attributes.normal,uv=g.attributes.uv;const repeat=m===mat.brick?3:8;for(let i=0;i<p.count;i++){const nx=Math.abs(n.getX(i)),ny=Math.abs(n.getY(i)),nz=Math.abs(n.getZ(i));uv.setXY(i,(nx>nz&&nx>ny?p.getZ(i):p.getX(i))/repeat,(ny>nx&&ny>nz?p.getZ(i):p.getY(i))/repeat);}}if(!groups.has(m))groups.set(m,[]);groups.get(m).push(g);}
 const box=(m,x,y,z,w,h,d,ry=0)=>add(cube,m,x,y,z,w,h,d,ry);
 const cyl=(m,x,y,z,r,h)=>add(cylinder,m,x,y,z,r,h,r);
 function polygon(points,m,y=0){const s=new T.Shape(points.map(([x,z])=>new T.Vector2(x,-z)));const g=new T.ShapeGeometry(s);g.rotateX(-Math.PI/2);const uv=g.attributes.uv;for(let i=0;i<uv.count;i++)uv.setXY(i,uv.getX(i)/12,uv.getY(i)/12);add(g,m,0,y,0);g.dispose();}
 polygon(data.boundary,mat.grass,-.06);box(mat.outer,-200,-1.2,230,3800,2,3400);
 const q={id:'qinian',name:'祈年殿',x:0,z:0,ground:4,source:'https://www.tiantanpark.cn/scenic_spot_list_g7yU_96/detail/1169.html',description:'明永乐十八年始建，清乾隆年间统一为蓝瓦。孟春祈谷礼的主要建筑。殿台通高约 38.2 米，外檐柱间直径约 24.2 米。'};
 const get=name=>bounds(data.ways.find(w=>w.tags.name===name).points);
 const eb=get('皇穹宇'),ab=get('圜丘'),zb=get('斋宫'),mb=get('神乐署');
 const e={id:'vault',name:'皇穹宇 · 回音壁',...eb,ground:0,source:'https://tiantanpark.cn/scenic_spot_list_g7yU_96/detail/1178.html',description:'皇穹宇供奉祭天大典的神位，现为单檐圆形攒尖顶。殿台通高 19.5 米、直径 15.6 米，周围圆形砖墙称回音壁。'};
 const a={id:'altar',name:'圜丘坛',...ab,ground:0,source:'https://wwj.beijing.gov.cn/bjww/362760/362770/436348561/',description:'冬至祭天的露天圆坛，建于明嘉靖九年。三层坛面直径约 54.91、39.31、23.65 米，四向台阶与石栏形成九数秩序。'};
 const z={id:'palace',name:'斋宫',...zb,ground:0,source:'https://gygl.beijing.gov.cn/mlgy/mlgy_lsmy/202508/t20250806_4167533.html',description:'皇帝祭天前斋戒的居所，始建于 1420 年，约占地四万平方米。内外墙与壕沟围合，无梁殿为主要建筑。'};
 const m={id:'music',name:'神乐署',...mb,ground:0,source:'https://www.tiantanpark.cn/index.html',description:'位于外坛西部，始建于明永乐十八年，是明清时期教习与演练祭祀礼乐的场所。当前院落位置依据公开地图。'};
 const landmarks=[q,e,a,{id:'bridge',name:'丹陛桥',x:15,z:300,ground:2,source:'https://www.tiantanpark.cn/scenic_spot_list/detail_g7yU_99/1447.html',description:'连接祈谷坛与圜丘坛的海墁大道，长 360 米、宽 30 米，向北渐高，北端高出地面约 4 米。'},z,m];
 // Walkable terraces are distinct from decoration, and use the same metre coordinates.
 const rectSurface=(x,z,w,d,y)=>surfaces.push({type:'rect',x,z,w,d,y});
 const circleSurface=(x,z,r,y)=>surfaces.push({type:'circle',x,z,r,y});
 function paveRect(x,z,w,d,y=0){box(mat.pave,x,y-.15,z,w,.3,d);rectSurface(x,z,w,d,y);}
 paveRect(0,0,152,210,4);polygon(Array.from({length:49},(_,i)=>{const t=Math.PI+i/48*Math.PI;return[76*Math.cos(t),-105+76*Math.sin(t)];}),mat.pave,4); // rounded northern prayer precinct
 const bridgeNorth=138,bridgeSouth=498,bx=14;
 const bridgeX=z=>7+(z-bridgeNorth)*14/360;
 paveRect(7,122,43,34,4);
 const bridgeGeo=new T.BoxGeometry(30,1,360);const pos=bridgeGeo.attributes.position;for(let i=0;i<pos.count;i++){const zz=pos.getZ(i)+318;pos.setX(i,pos.getX(i)+bridgeX(zz)-bx);pos.setY(i,pos.getY(i)+(bridgeSouth-zz)/90);}bridgeGeo.computeVertexNormals();const buv=bridgeGeo.attributes.uv;for(let i=0;i<buv.count;i++)buv.setXY(i,buv.getX(i)*3.75,buv.getY(i)*45);add(bridgeGeo,mat.pave,bx,-.5,318);bridgeGeo.dispose();surfaces.push({type:'bridge',x:bx,z:318,w:30,d:360});
 for(const dx of [-15,15,-5,5]){const g=new T.BoxGeometry(Math.abs(dx)===15?.5:.2,Math.abs(dx)===15?.3:.025,360);const a=g.attributes.position;for(let i=0;i<a.count;i++){const zz=a.getZ(i)+318;a.setX(i,a.getX(i)+bridgeX(zz)-bx);a.setY(i,a.getY(i)+(bridgeSouth-zz)/90);}g.computeVertexNormals();add(g,mat.stone,bx+dx,.08,318);g.dispose();}
 // A broad gradual terrain shoulder prevents a visually floating bridge.
 for(const side of [-1,1]){const g=new T.BufferGeometry();const verts=[],uvs=[];for(let i=0;i<20;i++){let z0=bridgeNorth+i*18,z1=z0+18;let y0=(bridgeSouth-z0)/90,y1=(bridgeSouth-z1)/90;verts.push(bridgeX(z0)+side*15,y0-.03,z0,bridgeX(z0)+side*30,0,z0,bridgeX(z1)+side*15,y1-.03,z1,bridgeX(z0)+side*30,0,z0,bridgeX(z1)+side*30,0,z1,bridgeX(z1)+side*15,y1-.03,z1);}for(let i=0;i<verts.length;i+=3)uvs.push(verts[i]/8,verts[i+2]/8);g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));g.computeVertexNormals();mat.grass.side=T.DoubleSide;add(g,mat.grass);g.dispose();}
 paveRect(a.x,a.z,168,168);cyl(mat.pave,e.x,.03,e.z+8,34,.12);circleSurface(e.x,e.z+8,34,.1);paveRect(z.x,z.z,z.w,z.d);paveRect(m.x,m.z,m.w,m.d);
 const allBuildingBounds=data.ways.filter(w=>w.tags.building).map(w=>({...bounds(w.points),id:w.id,tags:w.tags}));
 // Roads follow the downloaded OSM network, clipped to the park polygon.
 for(const way of data.ways.filter(w=>w.tags.highway&&w.tags.highway!=='steps')){let width=Number(way.tags.width)||(['service','unclassified'].includes(way.tags.highway)?7:way.tags.highway==='pedestrian'?8:4);width=Math.min(width,12);for(let i=1;i<way.points.length;i++){const p=way.points[i-1],r=way.points[i],mx=(p[0]+r[0])/2,mz=(p[1]+r[1])/2;if(!inside([mx,mz],data.boundary)||Math.abs(mx-bx)<18&&mz>105&&mz<477)continue;const len=Math.hypot(r[0]-p[0],r[1]-p[1]);box(mat.pave,mx,.025,mz,width,.1,len,Math.atan2(r[0]-p[0],r[1]-p[1]));roads.push({a:p,b:r,width});}}
 function wallLine(p,r,height=3,cap=true){const dx=r[0]-p[0],dz=r[1]-p[1],len=Math.hypot(dx,dz),x=(p[0]+r[0])/2,zz=(p[1]+r[1])/2;if(len<.2)return;const yy=Math.abs(x)<78&&zz<107&&zz>-190?4:0;const ry=Math.atan2(dx,dz);box(mat.brick,x,yy+height/2,zz,.8,height,len,ry);box(mat.stone,x,yy+.15,zz,1,.3,len,ry);if(cap)box(mat.blue,x,yy+height+.15,zz,1.3,.3,len,ry);wallSegments.push({a:p,b:r,width:.7,y:yy,h:height});}
 // OSM walls include both inner and outer altar enclosures; gate gaps are preserved.
 for(const w of data.ways.filter(w=>w.tags.barrier==='wall'&&!['43921113','237696577'].includes(w.id))){for(let i=1;i<w.points.length;i++){const p=w.points[i-1],r=w.points[i];const mid=[(p[0]+r[0])/2,(p[1]+r[1])/2];if(!inside(mid,data.boundary)&&distanceSegment(mid[0],mid[1],data.boundary[0],data.boundary[1])>3)continue;wallLine(p,r,2.8);}}
 // Outer park enclosure, with openings at each principal entry.
 const gateBounds=allBuildingBounds.filter(b=>/天坛.*门|昭亨门/.test(b.tags.name||''));
 for(let i=1;i<data.boundary.length;i++){const p=data.boundary[i-1],r=data.boundary[i],l=Math.hypot(r[0]-p[0],r[1]-p[1]);const n=Math.ceil(l/8);for(let j=0;j<n;j++){const p1=[T.MathUtils.lerp(p[0],r[0],j/n),T.MathUtils.lerp(p[1],r[1],j/n)],p2=[T.MathUtils.lerp(p[0],r[0],(j+1)/n),T.MathUtils.lerp(p[1],r[1],(j+1)/n)],x=(p1[0]+p2[0])/2,zz=(p1[1]+p2[1])/2;if(gateBounds.some(b=>Math.abs(b.x-x)<b.w/2+10&&Math.abs(b.z-zz)<b.d/2+10))continue;wallLine(p1,p2,3.2);}}
 function railing(x,z,r,y){const n=Math.round(2*Math.PI*r/2.25);for(let i=0;i<n;i++){const t=i/n*Math.PI*2,mid=t+Math.PI/n,xx=x+Math.sin(t)*r,zz=z+Math.cos(t)*r,px=x+Math.sin(mid)*r,pz=z+Math.cos(mid)*r,span=2*Math.PI*r/n-.37;if(Math.abs(Math.sin(t))*r<3.6||Math.abs(Math.cos(t))*r<3.6)continue;
 box(mat.stone,xx,y+.74,zz,.42,1.48,.42);box(mat.stone,xx,y+.18,zz,.55,.26,.55);add(sphere,mat.stone,xx,y+1.53,zz,.24,.19,.24);box(mat.stone,px,y+.72,pz,span,.72,.14,-mid);box(mat.stone,px,y+1.16,pz,span+.18,.17,.32,-mid);box(mat.stone,px,y+.29,pz,span+.12,.13,.28,-mid);for(const offset of [-.34,.34])box(mat.stone,px+Math.cos(mid)*offset,y+.73,pz-Math.sin(mid)*offset,.09,.5,.2,-mid);box(mat.stone,px,y+.72,pz,span*.48,.22,.23,-mid);}}
 function stairs(x,z,r0,r1,y0,y1){const n=Math.ceil((y1-y0)/.18);for(let dir=0;dir<4;dir++){const t=dir*Math.PI/2;for(let j=0;j<n;j++){const rr=T.MathUtils.lerp(r0+1,r1,j/n);const end=r1-1,depth=Math.abs(rr-end);box(mat.stone,x+Math.sin(t)*(rr+end)/2,y0+(y1-y0)*(j+1)/n/2,z+Math.cos(t)*(rr+end)/2,6.2,(y1-y0)*(j+1)/n,depth,t);}
 surfaces.push({type:'stairs',x,z,r0:r0+1,r1:r1-1,y0,y1,dir:t,width:6.2}); // narrow side rails follow the ascent
 for(const side of [-1,1]){const length=Math.hypot(r0-r1+2,y1-y0);const rail=new T.BoxGeometry(.22,.6,length);rail.rotateX(Math.atan2(y1-y0,r0-r1+2));add(rail,mat.stone,x+Math.sin(t)*(r0+r1)/2+Math.cos(t)*side*3.3,(y0+y1)/2+.6,z+Math.cos(t)*(r0+r1)/2-Math.sin(t)*side*3.3,1,1,1,t);rail.dispose();}}}
 function platform(x,z,radii,heights,base){let y=base;for(let i=0;i<radii.length;i++){const r=radii[i],h=heights[i];cyl(mat.stone,x,y+h/2,z,r,h);cyl(mat.stone,x,y+h-.12,z,r+.18,.25);circleSurface(x,z,r,y+h);railing(x,z,r-.35,y+h);stairs(x,z,i===0?r+8:radii[i-1]-.6,r,y,y+h);y+=h;}return y;}
 function roundRoof(x,z,points){const profile=points.map(p=>new T.Vector2(...p));const g=new T.LatheGeometry(profile,192);const uv=g.attributes.uv;for(let i=0;i<uv.count;i++)uv.setXY(i,uv.getX(i)*12,uv.getY(i)*3);mat.blue.side=T.DoubleSide;add(g,mat.blue,x,0,z);g.dispose();const lip=points[0][0],eaveY=points[0][1];const soffit=new T.RingGeometry(lip*.62,lip,192);soffit.rotateX(-Math.PI/2);add(soffit,mat.soffit,x,eaveY-.52,z);soffit.dispose();const curve=new T.CatmullRomCurve3(points.map(([r,y])=>new T.Vector3(r,y+.095,0)));const tube=new T.TubeGeometry(curve,32,.06,5,false);const count=Math.round(lip*19);const ridges=new T.InstancedMesh(tube,mat.blue,count);for(let i=0;i<count;i++){temp.position.set(x,0,z);temp.rotation.set(0,i/count*Math.PI*2,0);temp.scale.set(1,1,1);temp.updateMatrix();ridges.setMatrixAt(i,temp.matrix);}ridges.castShadow=true;ridges.receiveShadow=true;scene.add(ridges);roofRidges.push(ridges);for(const [radius,yy,tubeRadius,material] of [[lip,eaveY,.18,mat.blue],[lip-.2,eaveY-.16,.075,mat.gold],[lip-.44,eaveY-.21,.085,mat.red]]){const ring=new T.TorusGeometry(radius,tubeRadius,7,192);ring.rotateX(Math.PI/2);add(ring,material,x,yy,z);ring.dispose();}const tips=new T.SphereGeometry(.105,6,5),tiles=new T.InstancedMesh(tips,mat.blue,count);for(let i=0;i<count;i++){const a=i/count*Math.PI*2;temp.position.set(x+Math.sin(a)*lip,eaveY-.02,z+Math.cos(a)*lip);temp.rotation.set(0,a,0);temp.scale.set(1,1,.8);temp.updateMatrix();tiles.setMatrixAt(i,temp.matrix);}tiles.castShadow=true;scene.add(tiles);roofRidges.push(tiles);}
 function drum(x,z,r,y,h,n,ornate=false){cyl(ornate?mat.indigo:mat.red,x,y+h/2,z,r,h);for(let i=0;i<n;i++){let t=i/n*Math.PI*2;const px=x+Math.sin(t)*(r+.25),pz=z+Math.cos(t)*(r+.25);cyl(ornate?mat.indigo:mat.red,px,y+h/2,pz,.27,h);cyl(mat.stone,px,y+.13,pz,.4,.26);const tt=t+Math.PI/n,ww=2*Math.PI*r/n*.74;const xx=x+Math.sin(tt)*(r+.08),zz=z+Math.cos(tt)*(r+.08);if(ornate){box(mat.paint,xx,y+h*.5,zz,ww,h*.62,.14,tt);box(mat.indigo,xx,y+h*.17,zz,ww,.18,.17,tt);box(mat.indigo,xx,y+h*.83,zz,ww,.18,.17,tt);for(let k=-1;k<=1;k++){const u=k*ww/3;add(sphere,mat.gold,xx+Math.cos(tt)*u+Math.sin(tt)*.12,y+h*.51,zz-Math.sin(tt)*u+Math.cos(tt)*.12,.12,.22,.1);}}else{box(mat.dark,xx,y+h*.42,zz,ww,h*.63,.12,tt);for(let j=-2;j<=2;j++)box(mat.red,x+Math.sin(tt)*(r+.17)+Math.cos(tt)*j*ww/5,y+h*.42,z+Math.cos(tt)*(r+.17)-Math.sin(tt)*j*ww/5,.09,h*.64,.12,tt);for(let j=0;j<5;j++)box(mat.red,x+Math.sin(tt)*(r+.2),y+.65+j*(h*.65/5),z+Math.cos(tt)*(r+.2),ww,.075,.12,tt);}box(mat.paint,px,y+h-.35,pz,ww+1,.65,.5,tt);box(mat.gold,x+Math.sin(tt)*(r+.32),y+h-.3,z+Math.cos(tt)*(r+.32),ww*.66,.08,.05,tt);
 // layered bracket clusters under each beam, a geometric interpretation of dougong
 for(let k=0;k<3;k++){box(mat.paint,px,y+h-.8+k*.23,pz,.7+k*.4,.15,.55+k*.45,t);box(mat.gold,px,y+h-.72+k*.23,pz,.6+k*.4,.04,.6+k*.4,t);}}
 }
 const qTop=platform(0,0,[45,38,31],[2,2,2],4);drum(0,0,12.1,qTop,9.5,28);drum(0,0,9.3,23,4.4,24,true);drum(0,0,6.6,29.5,3.4,20,true);
 // The prayer hall's friezes, layered brackets and door bays follow the photographed rhythm of the 28 exterior columns.
 function prayerDecoration(){const n=28,r=12.1;for(const [radius,y,h] of [[12.13,18.4,.9],[9.32,26.55,.7],[6.63,32.28,.55]]){cyl(mat.indigo,0,y,0,radius,h);cyl(mat.gold,0,y+h/2+.035,0,radius+.055,.07);cyl(mat.gold,0,y-h/2-.035,0,radius+.055,.07);}for(let i=0;i<n;i++){const t=i/n*Math.PI*2,mid=t+Math.PI/n,px=Math.sin(t)*12.1,pz=Math.cos(t)*12.1,xx=Math.sin(mid)*12.37,zz=Math.cos(mid)*12.37,wide=2*Math.PI*r/n*.79;box(mat.paint,xx,18.28,zz,wide,.72,.08,mid);box(mat.gold,xx,18.75,zz,wide*.88,.06,.1,mid);box(mat.indigo,xx,17.83,zz,wide*.95,.1,.13,mid);for(const side of [-1,1]){box(mat.indigo,px+Math.cos(t)*side*.42,19.25,pz-Math.sin(t)*side*.42,.28,.26,.92,t);box(mat.paint,px+Math.cos(t)*side*.54,19.01,pz-Math.sin(t)*side*.54,.36,.18,1.12,t);box(mat.indigo,px+Math.cos(t)*side*.67,18.78,pz-Math.sin(t)*side*.67,.42,.18,1.34,t);}box(mat.dark,px,18.9,pz,.33,.24,.34,t);const doorway=(i===0||i===1||i===27);if(doorway){box(mat.dark,xx,13.65,zz,wide*.79,5.7,.21,mid);for(const s of [-1,1]){box(mat.red,xx+Math.cos(mid)*s*wide*.39,13.68,zz-Math.sin(mid)*s*wide*.39,.2,5.82,.25,mid);box(mat.gold,xx+Math.cos(mid)*s*wide*.31,13.7,zz-Math.sin(mid)*s*wide*.31,.045,5.5,.23,mid);}box(mat.red,xx,16.61,zz,wide*.88,.3,.31,mid);}else{box(mat.red,xx,15.15,zz,wide*.82,1.17,.2,mid);for(let k=-1;k<=1;k++)box(mat.gold,xx+Math.cos(mid)*k*wide*.22,15.1,zz-Math.sin(mid)*k*wide*.22,.055,.84,.23,mid);box(mat.gold,xx,15.72,zz,wide*.75,.06,.22,mid);}}for(const [radius,y,columns,height]of [[9.3,27,24,.7],[6.6,32.5,20,.55]])for(let i=0;i<columns;i++){const t=(i+.5)/columns*Math.PI*2;box(mat.paint,Math.sin(t)*(radius+.14),y,Math.cos(t)*(radius+.14),2*Math.PI*radius/columns*.78,height,.1,t);box(mat.gold,Math.sin(t)*(radius+.19),y-height*.46,Math.cos(t)*(radius+.19),2*Math.PI*radius/columns*.65,.045,.13,t);}}
 prayerDecoration();
 const signCanvas=document.createElement('canvas');signCanvas.width=256;signCanvas.height=512;const signCtx=signCanvas.getContext('2d');signCtx.fillStyle='#1f3c7d';signCtx.fillRect(0,0,256,512);signCtx.strokeStyle='#c8a75f';signCtx.lineWidth=13;signCtx.strokeRect(10,10,236,492);signCtx.lineWidth=3;signCtx.strokeRect(26,26,204,460);signCtx.fillStyle='#d8b76a';signCtx.font='bold 76px serif';signCtx.textAlign='center';for(const [i,ch]of [...'祈年殿'].entries())signCtx.fillText(ch,128,143+i*125);const signTex=new T.CanvasTexture(signCanvas);signTex.colorSpace=T.SRGBColorSpace;const signMat=new T.MeshStandardMaterial({map:signTex,roughness:.74});box(mat.gold,0,32.05,10.12,2.35,4.05,.24);add(cube,signMat,0,32.05,10.26,2.02,3.74,.08);for(const dx of [-1,1])for(const dy of [-1,1])add(sphere,mat.gold,dx*1.15,32.05+dy*2,10.27,.15,.17,.15);
 for(const [outer,inner,base]of [[53,45,4],[44.4,38,6],[37.4,31,8]]){const len=outer-inner,angle=Math.atan2(2,len),ramp=new T.BoxGeometry(2.45,.22,len-.4);ramp.rotateX(angle);add(ramp,mat.stone,0,base+1.23,(outer+inner)/2);ramp.dispose();for(const side of [-1,1])box(mat.stone,side*1.17,base+1.29,(outer+inner)/2,.1,.07,len-.5);}
 roundRoof(0,0,[[16.2,20.5],[15.7,20.2],[14.3,20.6],[12,21.5],[9,23.2],[5.4,25.7],[2,27]]);
 roundRoof(0,0,[[13.1,27.8],[12.6,27.5],[11.2,28],[9,29.2],[6.6,31.2],[3.4,33.4],[1.4,34.4]]);
 roundRoof(0,0,[[10.3,33.1],[9.8,32.85],[8.6,33.25],[6.8,34.05],[4.7,35.45],[2.4,38.05],[.7,40.35],[0,41]]);
 const finial=new T.LatheGeometry([[.38,0],[.75,.14],[.82,.27],[.58,.42],[.45,.56],[.58,.75],[.56,.95],[.68,1.1],[.72,1.45],[.56,1.8],[.31,2.05],[0,2.18]].map(p=>new T.Vector2(...p)),48);add(finial,mat.gold,0,40.1,0);
 const eTop=platform(e.x,e.z,[11.5],[2.85],0);drum(e.x,e.z,7.8,eTop,7,8);roundRoof(e.x,e.z,[[10,9.9],[9.5,9.65],[8.4,10],[6.6,11.2],[4.8,13.3],[2.6,16],[.5,18],[0,18.2]]);add(finial,mat.gold,e.x,17.3,e.z);finial.dispose();
 platform(a.x,a.z,[27.455,19.655,11.825],[1.67,1.63,1.87],0);cyl(mat.stone,a.x,5.22,a.z,.6,.1);
 function circularWall(x,z,r,h,gap=7){const n=150;for(let i=0;i<n;i++){const t=i/n*Math.PI*2,u=(i+1)/n*Math.PI*2;if(Math.abs(Math.sin((t+u)/2))*r<gap/2&&Math.cos((t+u)/2)>0)continue;wallLine([x+Math.sin(t)*r,z+Math.cos(t)*r],[x+Math.sin(u)*r,z+Math.cos(u)*r],h);}}
 circularWall(e.x,e.z+9,30.75,3.72,9);circularWall(a.x,a.z,54.2,1.89,10);
 // Main roofs use a custom swept hipped profile, with curved slopes and lifted corners.
 function hipRoof(x,z,w,d,y,roof=mat.blue){const levels=[[1,0],[.96,-.25],[.8,.25],[.58,1.1],[.32,2.2],[.02,3.4]],verts=[],uvs=[];const short=Math.min(w,d);const ring=(s,yy)=>{const wx=(Math.max(w-d,0)+short*s)/2,dz=(Math.max(d-w,0)+short*s)/2;return[[-wx,yy,-dz],[wx,yy,-dz],[wx,yy,dz],[-wx,yy,dz]];};for(let k=1;k<levels.length;k++){const [s0,y0]=levels[k-1],[s1,y1]=levels[k];const r0=ring(s0,y0),r1=ring(s1,y1);for(let j=0;j<4;j++){const n=(j+1)%4;const pts=[r0[j],r0[n],r1[j],r0[n],r1[n],r1[j]];for(let p=0;p<6;p++){let v=pts[p];verts.push(v[0],v[1]+(k===1?.22:0),v[2]);uvs.push((j%2?v[2]:v[0])/3,k/2);}}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));g.computeVertexNormals();roof.side=T.DoubleSide;add(g,roof,x,y,z);g.dispose();box(roof,x,y+3.4,z,Math.max(w-d,.25),.22,Math.max(d-w,.25));for(const dx of [-1,1])for(const dz of [-1,1]){add(sphere,mat.gold,x+dx*w*.48,y+.45,z+dz*d*.48,.16,.22,.16);}}
 function hall(b,base=0,green=false){const{w,d,x,z}=b;const gate=b.tags?.building==='gate'||b.tags?.building==='gatehouse';const h=b.tags?.name==='皇乾殿'?7:Math.min(6,Math.max(3.4,Math.min(w,d)*.52));const plinth=gate?.16:.7;box(mat.stone,x,base+plinth/2,z,w+1.8,plinth,d+1.8);rectSurface(x,z,w+1.8,d+1.8,base+plinth);if(!gate){box(mat.red,x,base+.7+h/2,z,w,h,d);solids.push({type:'rect',x,z,w,d,y:base,h:h+4});}else{const width=Math.max(2,w*.2);box(mat.red,x-w/2+width/2,base+h/2,z,width,h,d);box(mat.red,x+w/2-width/2,base+h/2,z,width,h,d);solids.push({type:'rect',x:x-w/2+width/2,z,w:width,d,y:base,h:h+4},{type:'rect',x:x+w/2-width/2,z,w:width,d,y:base,h:h+4});}
 const n=Math.max(3,Math.round(w/3));for(let i=0;i<=n;i++){const xx=x-w/2+i*w/n;for(const side of [-1,1]){cyl(mat.red,xx,base+.7+h/2,z+side*(d/2+.45),.23,h);if(i<n&&!gate){box(mat.dark,xx+w/n/2,base+2.6,z+side*(d/2+.07),w/n*.7,2.6,.1);for(let k=-2;k<=2;k++)box(mat.red,xx+w/n/2+k*.35,base+2.6,z+side*(d/2+.14),.08,2.6,.08);for(let k=0;k<5;k++)box(mat.red,xx+w/n/2,base+1.5+k*.48,z+side*(d/2+.15),w/n*.7,.06,.1);}}}
 box(mat.paint,x,base+h+.3,z,w+1,.8,d+1);box(mat.gold,x,base+h+.35,z+d/2+.6,w*.92,.08,.08);hipRoof(x,z,w+3.4,d+3.4,base+h+.9,green?mat.green:mat.blue);
 }
 for(const b of allBuildingBounds){if(['43921139','43921121','31099286','43921112'].includes(b.id))continue;if(b.w<1||b.d<1||b.w>180||b.d>90)continue;const base=Math.abs(b.x)<80&&b.z<108&&b.z>-200?4:0;hall(b,base,b.x<-250||/神厨|宰牲/.test(b.tags.name||''));}
 // Covered corridor: 72 repeated bays, a locally generated continuous geometry.
 const corridor=data.ways.find(w=>w.tags.name==='长廊');if(corridor){const b=bounds(corridor.points);const segs=[[80,0,180,0],[180,0,180,-32],[180,-32,300,-32]];for(const [x0,z0,x1,z1]of segs){const l=Math.hypot(x1-x0,z1-z0),mx=(x0+x1)/2,mz=(z0+z1)/2,vertical=x0===x1;box(mat.pave,mx,.25,mz,vertical?5:l,.5,vertical?l:5);for(let i=0;i<=Math.round(l/4.1);i++){const t=i/Math.round(l/4.1);for(const side of [-1,1])cyl(mat.red,x0+(x1-x0)*t+(vertical?side*2:0),1.8,z0+(z1-z0)*t+(vertical?0:side*2),.15,3.2);}hipRoof(mx,mz,vertical?6:l+1,vertical?l+1:6,3.6,mat.green);}void b;}
 const double=data.ways.find(w=>w.tags.name==='双环万寿亭');if(double){const b=bounds(double.points);for(const offset of [-3,3]){drum(b.x+offset,b.z,4,0,4,8);roundRoof(b.x+offset,b.z,[[5,4],[4,4.3],[2.5,5.8],[0,8]]);}}
 // Collision disks keep visitors out of the closed timber halls.
 solids.push({type:'circle',x:0,z:0,r:12.5,y:qTop,h:32},{type:'circle',x:e.x,z:e.z,r:8,y:eTop,h:20});
 // Zhaigong moat: avoid replacing the court with water.
 for(const side of [-1,1]){box(mat.water,z.x+side*(z.w/2+7),-.02,z.z,7,.12,z.d+15);solids.push({type:'rect',x:z.x+side*(z.w/2+7),z:z.z,w:7,d:z.d+15,y:0,h:.3});}
 // Flush static geometry by material. No mesh is allocated per tile or baluster.
 for(const [material,geos]of groups){const combined=mergeGeometries(geos,false);const mesh=new T.Mesh(combined,material);mesh.castShadow=![mat.pave,mat.grass,mat.water].includes(material);mesh.receiveShadow=true;scene.add(mesh);geos.forEach(g=>g.dispose());}
 groups.clear();cube.dispose();cylinder.dispose();sphere.dispose();
 // Organic cypress crown prototype, shared by spatial LOD cells and InstancedMesh.
 const crownParts=[];for(const [xx,yy,zz,rx,ry,rz] of [[0,6.2,0,2.6,3.1,2.55],[.72,8.35,-.38,2.42,2.7,2.28],[-.52,10.42,.32,1.85,2.3,1.8],[.18,12.1,-.15,1.1,1.72,1.08],[1.38,5.7,.6,1.35,2.1,1.3],[-1.4,6.5,-.48,1.36,2.2,1.34]]){const g=new T.SphereGeometry(1,16,12),p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),noise=1+.12*Math.sin(x*13+y*19+z*7)*Math.cos(z*16-y*9)+.065*Math.sin(x*31+z*23+y*17);p.setXYZ(i,x*noise,y*noise,z*noise);}g.computeVertexNormals();g.scale(rx,ry,rz);g.translate(xx,yy,zz);crownParts.push(g);}const crown=mergeGeometries(crownParts);crownParts.forEach(g=>g.dispose());const lowCrown=new T.IcosahedronGeometry(3.2,1);lowCrown.scale(1,1.7,1);lowCrown.translate(0,8.1,0);const woodParts=[];const stem=new T.CylinderGeometry(.25,.53,7.4,9);stem.translate(0,3.7,0);woodParts.push(stem);for(let i=0;i<5;i++){const t=i*2.399,y=3.8+i*.7;const branch=new T.CylinderGeometry(.06,.18,3.7,6);branch.translate(0,1.85,0);branch.rotateZ(.7);branch.rotateY(t);branch.translate(0,y,0);woodParts.push(branch);}const trunk=mergeGeometries(woodParts);woodParts.forEach(g=>g.dispose());
 const cells=new Map();const treePoints=[];
 function clearTree(x,zz){if(!inside([x,zz],data.boundary))return false;if(Math.abs(x)<91&&zz>-202&&zz<110||Math.abs(x-bx)<31&&zz>85&&zz<492||Math.hypot(x-e.x,zz-e.z-8)<43||Math.abs(x-a.x)<99&&Math.abs(zz-a.z)<100||Math.abs(x-z.x)<z.w/2+17&&Math.abs(zz-z.z)<z.d/2+17||Math.abs(x-m.x)<m.w/2+15&&Math.abs(zz-m.z)<m.d/2+15)return false;if(allBuildingBounds.some(b=>Math.abs(x-b.x)<b.w/2+6&&Math.abs(zz-b.z)<b.d/2+6))return false;return!roads.some(r=>distanceSegment(x,zz,r.a,r.b)<r.width/2+4);}
 for(let i=0;i<21000;i++){const x=-1060+random()*1700,zz=-505+random()*1538; // broad lawns, sparse gardens and denser groves form a nonuniform canopy
 const lawn=(x<-220&&x>-650&&zz<170&&zz>15)||(x>210&&zz>50&&zz<220);const grove=.53+.43*(.5+.5*Math.sin(x*.014+Math.sin(zz*.005)*3)*Math.sin(zz*.012+Math.cos(x*.009)*2));if(random()>grove||lawn&&random()<.93||!clearTree(x,zz))continue;if(treePoints.some(p=>Math.hypot(x-p[0],zz-p[1])<7))continue;treePoints.push([x,zz,.74+random()*.61,random()*Math.PI*2,.76+random()*.43]);if(treePoints.length>=4700)break;}
 for(const p of treePoints){const key=`${Math.floor(p[0]/220)},${Math.floor(p[1]/220)}`;if(!cells.has(key))cells.set(key,[]);cells.get(key).push(p);}
 for(const points of cells.values()){const b=bounds(points.map(p=>p.slice(0,2)));const lod=new T.LOD();lod.position.set(b.x,0,b.z);function level(geometry,near){const group=new T.Group();for(const [geo,material]of [[geometry,mat.leaves],[trunk,mat.bark]]){const mesh=new T.InstancedMesh(geo,material,points.length);points.forEach(([x,zz,s,ry,shape],i)=>{temp.position.set(x-b.x,0,zz-b.z);temp.rotation.set(0,ry,0);temp.scale.set(s*shape,s,s/shape);temp.updateMatrix();mesh.setMatrixAt(i,temp.matrix);if(material===mat.leaves)mesh.setColorAt(i,new T.Color().setHSL(.24+random()*.07,.15+random()*.13,.24+random()*.11));});mesh.castShadow=near;mesh.receiveShadow=true;group.add(mesh);}return group;}lod.addLevel(level(crown,true),0);lod.addLevel(level(lowCrown,false),240);scene.add(lod);treeLODs.push(lod);}
 // Pick proxy meshes are raycast-only, excluded from render and collision geometry.
 for(const l of landmarks){const radius=l===q?45:l===a?28:l===e?32:l.id==='bridge'?20:Math.min(l.w,l.d)/2;const proxy=new T.Mesh(new T.CylinderGeometry(radius,radius,l===q?38:20,24),new T.MeshBasicMaterial({visible:false}));proxy.position.set(l.x,l.ground+10,l.z);proxy.userData.landmark=l;scene.add(proxy);pickables.push(proxy);}
 function ground(x,zz){let y=0;for(const s of surfaces){if(s.type==='rect'&&Math.abs(x-s.x)<=s.w/2&&Math.abs(zz-s.z)<=s.d/2)y=Math.max(y,s.y);if(s.type==='circle'&&Math.hypot(x-s.x,zz-s.z)<=s.r)y=Math.max(y,s.y);if(s.type==='bridge'&&Math.abs(x-bridgeX(zz))<=s.w/2&&zz>=bridgeNorth&&zz<=bridgeSouth)y=Math.max(y,(bridgeSouth-zz)/90);if(s.type==='stairs'){const dx=x-s.x,dz=zz-s.z,along=dx*Math.sin(s.dir)+dz*Math.cos(s.dir),across=dx*Math.cos(s.dir)-dz*Math.sin(s.dir);if(Math.abs(across)<=s.width/2&&along>=s.r1&&along<=s.r0){const h=T.MathUtils.lerp(s.y0,s.y1,(s.r0-along)/(s.r0-s.r1));return h;}}}return y;}
 function canStand(x,zz,oldY=ground(x,zz)){const y=ground(x,zz);if(!inside([x,zz],data.boundary)||Math.abs(y-oldY)>.4)return false;for(const s of solids){if(y>=s.y+s.h)continue;if(s.type==='circle'&&Math.hypot(x-s.x,zz-s.z)<s.r+.35||s.type==='rect'&&Math.abs(x-s.x)<s.w/2+.35&&Math.abs(zz-s.z)<s.d/2+.35)return false;}for(const s of wallSegments)if(y<s.y+s.h&&distanceSegment(x,zz,s.a,s.b)<s.width+.3)return false; // Stone balustrades admit only stair openings.
 for(const [xx,zz0,radii,base,heights]of [[0,0,[45,38,31],4,[2,2,2]],[e.x,e.z,[11.5],0,[2.85]],[a.x,a.z,[27.455,19.655,11.825],0,[1.67,1.63,1.87]]]){let yy=base;for(let i=0;i<radii.length;i++){yy+=heights[i];let dx=x-xx,dz=zz-zz0;if(Math.abs(Math.hypot(dx,dz)-(radii[i]-.35))<.45&&Math.abs(dx)>3.1&&Math.abs(dz)>3.1&&y<yy+1.5)return false;}}
 return true;}
 return{mat,landmarks,pickables,solids,surfaces,wallSegments,roads,treeLODs,roofRidges,treeCount:treePoints.length,ground,canStand,bridge:{north:bridgeNorth,south:bridgeSouth,x:bx,center:bridgeX},data};
}
