import {chromium} from 'playwright';
import fs from 'node:fs';
import os from 'node:os';
const base=process.env.TEST_URL||'http://127.0.0.1:5186/';
const executablePath=process.env.CHROMIUM_PATH||'C:/Users/YUE/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe';
fs.mkdirSync('evidence',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath,args:['--enable-webgl','--ignore-gpu-blocklist']});
const report={dateUTC:new Date().toISOString(),dateLocal:'2026-10-01 Asia/Shanghai',url:base,device:{platform:os.platform(),release:os.release(),cpu:os.cpus()[0]?.model,logicalCores:os.cpus().length,memoryGiB:Math.round(os.totalmem()/1024**3),browser:await browser.version(),headless:true},viewport:{width:1440,height:960,dpr:1},checks:[],failures:[],errors:[],warnings:[],failedRequests:[],performance:[]};
const assert=(condition,msg)=>{if(!condition)report.failures.push(msg)};
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});
page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());if(m.type()==='warning'&&!report.warnings.includes(m.text()))report.warnings.push(m.text())});page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));page.on('response',r=>{if(r.status()>=400)report.failedRequests.push({url:r.url(),status:r.status()})});
const capture=async file=>{await page.waitForTimeout(450);await page.screenshot({path:`evidence/${file}.png`})};
try{
 const started=performance.now();await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__ymy?.ready,null,{timeout:90000});report.loadMs=Math.round(performance.now()-started);await page.waitForTimeout(1000);
 report.scene=await page.evaluate(()=>{const s=window.__ymy,g=s.renderer.getContext(),e=g.getExtension('WEBGL_debug_renderer_info');return {gpu:e?g.getParameter(e.UNMASKED_RENDERER_WEBGL):g.getParameter(g.RENDERER),sites:s.models.length,treeInstances:s.foliage.total,water:s.data.water.length,waterHoles:s.data.water.reduce((a,w)=>a+w.holes.length,0),navigationSegments:s.ground.segments.length,colliders:s.obstacles.length,drawCalls:s.renderer.info.render.calls,triangles:s.renderer.info.render.triangles}});await capture('western-medium');report.checks.push('页面、本地材质与数据加载；实际WebGL场景');
 await page.locator('#sources-open').click();assert(await page.locator('#sources-dialog').isVisible(),'资料弹窗显示');assert(await page.locator('#source-links article').count()>10,'来源显示');await page.locator('#sources-dialog .dialog-close').click();await page.locator('#help-open').click();assert(await page.locator('#help-dialog').isVisible(),'操作弹窗');await page.locator('#help-dialog .dialog-close').click();report.checks.push('来源、证据分级与操作说明弹窗');
 await page.locator('#search').fill('海晏');assert(await page.locator('.site-row').count()===1,'景点搜索过滤');await page.locator('.site-row').click();assert((await page.locator('#info-content h2').innerText())==='海晏堂','搜索定位信息');await page.locator('#info-close').click();await page.locator('#search').fill('不存在景点');assert(await page.locator('.site-row').count()===0,'空搜索状态');await page.locator('#search').fill('');report.checks.push('搜索、空状态和景点定位');
 await page.locator('#fold-map').click();assert(await page.locator('#map-panel').evaluate(e=>e.classList.contains('folded')),'折叠地图');await page.locator('#fold-map').click();await page.locator('#minimap [aria-label="九洲清晏"]').click();assert((await page.locator('#info-content h2').innerText())==='九洲清晏','地图点定位');await capture('jiuzhou');await page.locator('#info-close').click();report.checks.push('小地图折叠、点击定位与三园显示');
 await page.locator('#reset-view').click();await capture('whole-gardens');const before=await page.evaluate(()=>window.__ymy.camera.position.toArray());await page.mouse.move(810,390);await page.mouse.down();await page.mouse.move(900,435,{steps:12});await page.mouse.up();await page.waitForTimeout(450);const after=await page.evaluate(()=>window.__ymy.camera.position.toArray());assert(Math.hypot(...after.map((x,i)=>x-before[i]))>20,'鸟瞰旋转');await page.mouse.wheel(0,-250);await page.waitForTimeout(400);report.checks.push('全园重置、鸟瞰鼠标旋转和缩放');
 await page.locator('#detail-view').click();await capture('stone-close');await page.locator('#labels-toggle').click();assert(await page.locator('#labels-toggle').getAttribute('aria-pressed')==='true','标签开启');await page.locator('#labels-toggle').click();report.checks.push('石材近景、按需标签');
 const safe=await page.evaluate(()=>{const s=window.__ymy;return s.data.sites.map(site=>{const p=s.nearestSafe([site.position[0],site.position[1]+Math.max(40,site.size[1])],site);return {name:site.name,point:p,safe:p&&s.validPosition(...p),distance:p?Math.hypot(p[0]-site.position[0],p[1]-site.position[1]):null}})});report.safeJumps=safe;assert(safe.every(s=>s.safe),'全部景点落脚点安全');assert(safe.every(s=>s.distance<150),'景点落脚距离<150m');
 const collision=await page.evaluate(()=>{const s=window.__ymy;let water=0,waterBlocked=0,insideBuildings=0,buildingBlocked=0;for(let x=-1100;x<1200;x+=13)for(let z=-800;z<1000;z+=13){if(s.ground.wet(x,z)&&!s.ground.bridgeAt(x,z)){water++;if(!s.validPosition(x,z))waterBlocked++}}for(const o of s.obstacles){insideBuildings++;if(!s.validPosition(o.x,o.z))buildingBlocked++}return {water,waterBlocked,insideBuildings,buildingBlocked}});report.collision=collision;assert(collision.water===collision.waterBlocked,'水面碰撞');assert(collision.insideBuildings===collision.buildingBlocked,'建筑内部封闭碰撞');report.checks.push('47处快捷跳转安全检查；桥面以外水面与建筑碰撞抽样');
 report.routeContinuity=await page.evaluate(()=>{const s=window.__ymy,graph=new Map(),edges=[];const key=p=>p.map(x=>x.toFixed(1)).join(',');for(const segment of s.ground.segments){const {a,b}=segment,len=Math.hypot(b[0]-a[0],b[1]-a[1]);if(len>150)continue;let valid=true;for(let t=0;t<=Math.ceil(len);t++){let p=[a[0]+(b[0]-a[0])*t/Math.ceil(len),a[1]+(b[1]-a[1])*t/Math.ceil(len)];if(!s.validPosition(...p)){valid=false;break}}if(!valid)continue;const ka=key(a),kb=key(b);if(!graph.has(ka))graph.set(ka,[]);if(!graph.has(kb))graph.set(kb,[]);graph.get(ka).push(kb);graph.get(kb).push(ka);edges.push({ka,kb,len})}const seen=new Set(),components=[];for(const start of graph.keys()){if(seen.has(start))continue;const component=new Set([start]),queue=[start];seen.add(start);while(queue.length){let k=queue.pop();for(const n of graph.get(k)||[]){if(seen.has(n))continue;seen.add(n);component.add(n);queue.push(n)}}components.push({nodes:component.size,totalLength:Math.round(edges.filter(e=>component.has(e.ka)).reduce((a,e)=>a+e.len,0))})}return {checkedAtMetreIntervals:true,passableSegments:edges.length,components:components.sort((a,b)=>b.totalLength-a.totalLength).slice(0,8)}});assert(report.routeContinuity.components[0]?.totalLength>1000,'主要可连通路线总长>1km');report.checks.push('辅助路线按1米间隔检查；连通图主分量超过1km，支路阻断未伪称全部连通');
 await page.evaluate(()=>window.__ymy.jump(window.__ymy.data.sites.find(s=>s.name==='大水法'),true));await page.waitForTimeout(300);const walkStart=await page.evaluate(()=>window.__ymy.camera.position.toArray());await page.keyboard.down('KeyW');await page.waitForTimeout(2600);await page.keyboard.up('KeyW');let walkEnd=await page.evaluate(()=>{const s=window.__ymy;return {position:s.camera.position.toArray(),valid:s.validPosition(s.camera.position.x,s.camera.position.z),eye:s.camera.position.y-s.ground.height(s.camera.position.x,s.camera.position.z)}});report.walk={start:walkStart,end:walkEnd};assert(Math.hypot(walkEnd.position[0]-walkStart[0],walkEnd.position[2]-walkStart[2])>.8,'WASD移动');assert(walkEnd.valid&&Math.abs(walkEnd.eye-1.7)<.001,'地面与1.7m视高');await page.mouse.move(830,480);await page.mouse.down();await page.mouse.move(980,470,{steps:8});await page.mouse.up();await capture('walking');report.checks.push('WASD步行、拖动观察、1.7米地面检测');
 await page.locator('#orbit-mode').click();await page.locator('#search').fill('大水法');await page.locator('.site-row').click();await page.locator('#info-close').click();await page.locator('#search').fill('');
 for(const quality of ['low','medium','high']){await page.locator('#quality').selectOption(quality);await page.waitForTimeout(1200);let sample=await page.evaluate(async()=>{const s=window.__ymy,frames=[];let last=performance.now();for(let i=0;i<120;i++){await new Promise(requestAnimationFrame);let n=performance.now();frames.push(n-last);last=n}let sorted=frames.slice().sort((a,b)=>a-b),avg=frames.reduce((a,b)=>a+b,0)/frames.length;return {averageFrameMs:+avg.toFixed(2),fps:+(1000/avg).toFixed(1),p95FrameMs:+sorted[Math.floor(sorted.length*.95)].toFixed(2),frames:frames.length,drawCalls:s.renderer.info.render.calls,triangles:s.renderer.info.render.triangles,dpr:s.renderer.getPixelRatio(),treeCount:s.foliage.canopies.count}});report.performance.push({quality,...sample})}report.checks.push('三档画质各120帧实际采样');
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.on('pageerror',e=>report.errors.push('mobile:'+e.message));await mp.goto(base);await mp.waitForFunction(()=>window.__ymy?.ready,null,{timeout:90000});await mp.waitForTimeout(450);await mp.locator('#fold-list').tap();await mp.locator('#search').fill('谐奇趣');await mp.locator('.site-row').tap();assert((await mp.locator('#info-content h2').innerText())==='谐奇趣','手机查询与跳转');await mp.locator('#info-close').tap();await mp.locator('#fold-list').tap();await mp.locator('#fold-map').tap();await mp.screenshot({path:'evidence/mobile.png'});
 const cdp=await mobile.newCDPSession(mp),mbefore=await mp.evaluate(()=>window.__ymy.camera.position.toArray());await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:300,y:260,id:1}]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:300-i*7,y:260+i*4,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mp.waitForTimeout(400);const mafter=await mp.evaluate(()=>window.__ymy.camera.position.toArray());assert(Math.hypot(...mafter.map((x,i)=>x-mbefore[i]))>1,'手机单指鸟瞰触控');report.mobile={viewport:{width:390,height:844},emulated:true,overflow:await mp.evaluate(()=>document.documentElement.scrollWidth>innerWidth),touchOrbit:true};assert(!report.mobile.overflow,'手机无水平溢出');await mobile.close();report.checks.push('390×844手机模拟：搜索、定位、小地图和触控旋转');
 const failContext=await browser.newContext({viewport:{width:1000,height:800}}),failPage=await failContext.newPage();await failPage.route('**/textures/rock-color.webp',r=>r.abort('failed'));await failPage.goto(base);await failPage.waitForSelector('#retry:not([hidden])',{timeout:20000});assert((await failPage.locator('#loading-text').innerText()).includes('加载失败'),'失败提示');report.failureRecovery={message:await failPage.locator('#loading-text').innerText()};await failPage.screenshot({path:'evidence/resource-failure.png'});await failPage.unroute('**/textures/rock-color.webp');await failPage.locator('#retry').click();await failPage.waitForFunction(()=>window.__ymy?.ready,null,{timeout:90000});await failContext.close();report.checks.push('主动阻断材质下载：失败说明、重试恢复');
 assert(report.errors.length===0,'主测试控制台无错误');assert(report.failedRequests.length===0,'主测试资源无失败');
}catch(e){report.failures.push(e.stack);await page.screenshot({path:'evidence/test-failure.png'}).catch(()=>{});}finally{await browser.close();let bytes=0;const walk=path=>{for(const dir of fs.readdirSync(path,{withFileTypes:true})){let p=path+'/'+dir.name;if(dir.isDirectory())walk(p);else bytes+=fs.statSync(p).size}};if(fs.existsSync('dist'))walk('dist');report.buildBytes=bytes;report.passed=report.failures.length===0;fs.writeFileSync('evidence/test-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,loadMs:report.loadMs,scene:report.scene,performance:report.performance,checks:report.checks,failures:report.failures,errors:report.errors,warnings:report.warnings},null,2));if(!report.passed)process.exitCode=1;}

