import * as T from 'three';
import {createScene,planWorld} from './scene.js';
import {collision,inside,toLonLat} from './geo.js';
import {Navigation} from './navigation.js';
const $=s=>document.querySelector(s),compactLayout=matchMedia('(max-width:900px)');
let mobile=matchMedia('(pointer:coarse)').matches||innerWidth<700;
function setPlacesOpen(open){$('#places').hidden=!open;$('#places-toggle').setAttribute('aria-expanded',String(open));$('#places-icon').textContent=open?'−':'+';}
const progress=(value,text)=>{$('#progress').value=value;$('#loading-text').textContent=text;};
const toast=message=>{$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4300);};
progress(5,'读取 site.json 地理数据');
async function loadJson(url){const r=await fetch(url);if(!r.ok)throw Error(`${url} 加载失败（HTTP ${r.status}）`);try{return await r.json();}catch{throw Error(`${url} 内容不是有效 JSON`);}}
const [data,sources]=await Promise.all([loadJson('./data/site.json'),loadJson('./data/sources.json')]);
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('#view'),antialias:true,logarithmicDepthBuffer:true,powerPreference:'high-performance'});}catch{throw Error('无法创建 WebGL 2。请启用浏览器硬件加速，检查显卡驱动后重载。');}
renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.93;renderer.info.autoReset=false;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.12,8000),world=await createScene(renderer,data,progress),scene=world.scene,coll=collision(data),sampleGround=coll.height;
coll.height=(x,z)=>{for(const p of world.platforms){const dx=x-p.center[0],dz=z-p.center[1],c=Math.cos(p.angle),s=Math.sin(p.angle),u=c*dx-s*dz,v=s*dx+c*dz;if(Math.abs(u)<p.width/2&&Math.abs(v)<p.depth/2){const edge=Math.min(p.width/2-Math.abs(u),p.depth/2-Math.abs(v));return edge<.19?.15:p.height;}}return sampleGround(x,z);};
let aerialScope='all',currentPlace='huyuan',quality=mobile?'low':'balanced',labelsEnabled=true,frameTime=16.7,frames=0,lastStamp=performance.now(),lastUI=0;
function updateNavigationUI(){document.body.classList.toggle('walking',nav.mode==='walk');document.body.classList.toggle('touch-walking',mobile&&nav.mode==='walk');for(const mode of ['aerial','core','walk']){const el=$('#'+mode),active=mode==='walk'?nav.mode==='walk':nav.mode==='aerial'&&aerialScope===(mode==='core'?'core':'all');el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));}$('#touch-controls').hidden=!(mobile&&nav.mode==='walk');$('#lock').hidden=mobile||nav.mode!=='walk';$('#hint').textContent=nav.mode==='walk'?(mobile?'左侧箭头移动 · 拖动场景观察':'WASD 移动 · 拖动观察 · 双击锁定鼠标 · Esc 释放'):'拖动旋转 · 右键平移 · 滚轮缩放';}
const nav=new Navigation(camera,$('#view'),coll,message=>{if(message)toast(message);updateNavigationUI();});
const labelNodes=[];for(const p of data.places){const el=document.createElement('span');el.className='label';el.textContent=p.name.replace(' · 原机修车间','').replace('与前场','');$('#labels').append(el);labelNodes.push({el,id:p.id,name:p.name,point:new T.Vector3(p.label[0],p.labelHeight,p.label[1])});const btn=document.createElement('button');btn.textContent=p.name.replace(' · 原机修车间','').replace('玻璃保护外壳','').replace('与前场','').replace(' · 新馆','');btn.dataset.place=p.id;btn.addEventListener('click',()=>jump(p.id,nav.mode));$('#places').append(btn);}
function setNote(id,mode){const p=data.places.find(p=>p.id===id);$('#mode-title').textContent=mode==='walk'?'地面漫游 · 视点 1.65 米':'建筑定位';$('#place-title').textContent=p?.name||'从闽江看船政';$('#place-description').textContent=p?.note|| (id==='quay'?'岸线有总平面依据 · 岸壁和水位高差为估算':data.buildings.find(b=>b.id===id)?.completion==='sample'?'砖木结构、窗洞与檐口 · 照片近似样板':'真实轮廓 · 代表性立面照片近似');document.querySelectorAll('[data-place]').forEach(b=>b.classList.toggle('active',b.dataset.place===id));}
export function jump(id,mode='walk',instant=false){const p=data.places.find(p=>p.id===id);if(!p)return;if(compactLayout.matches)setPlacesOpen(false);aerialScope='place';currentPlace=id;setNote(id,mode);const base=coll.height(...p.eye),targetBase=coll.height(...p.target),building=data.buildings.find(b=>b.id===id);if(mode==='walk')nav.fly([p.eye[0],base+1.65,p.eye[1]],[p.target[0],base+1.65,p.target[1]],mode,instant?0:1050);else{const v=new T.Vector2(p.eye[0]-p.target[0],p.eye[1]-p.target[1]).normalize().multiplyScalar(p.distance||(id==='museum'?77:55)),height=Math.max(31,(building?.height||16)*1.6);nav.fly([p.target[0]+v.x,targetBase+height,p.target[1]+v.y],[p.target[0],targetBase+(building?.height||8)*.45,p.target[1]],mode,instant?0:1050);}}
function aerial(instant=false,scope='all'){aerialScope=scope;let target,eye;if(scope==='core'||!data.city){target=planWorld(data,938,567);const p=planWorld(data,928,-598);eye=[p[0],225,p[1]];}else{target=[350,0,150];eye=[-850,1260,1900];const radius=Math.max(...data.boundary.map(p=>Math.hypot(p[0]-350,p[1]-150)))+35,half=Math.min(T.MathUtils.degToRad(camera.fov/2),Math.atan(Math.tan(T.MathUtils.degToRad(camera.fov/2))*camera.aspect)),offset=new T.Vector3(...eye).sub(new T.Vector3(...target)),fit=Math.max(offset.length(),radius/Math.sin(half)*1.03);eye=new T.Vector3(...target).add(offset.setLength(fit)).toArray();}currentPlace='huyuan';nav.fly(eye,[target[0],0,target[2]??target[1]],'aerial',instant?0:1200);$('#mode-title').textContent=scope==='core'?'旧船厂 · 样板区':'五大片区鸟瞰';$('#place-title').textContent=scope==='core'?'从闽江看船政':'船政 · 山、城与江';$('#place-description').textContent=scope==='core'?'原核心区14处体量 · 重点建筑照片近似':'船厂 / 官街 / 马限山 / 旧港 / 罗星塔';document.querySelectorAll('[data-place]').forEach(b=>b.classList.remove('active'));}
for(const zone of data.zones||[]){const button=document.createElement('button');button.textContent=zone.name;button.title=zone.description;button.dataset.zone=zone.id;button.addEventListener('click',()=>jump(zone.place,nav.mode));$('#zones').append(button);}
$('#core').addEventListener('click',()=>aerial(false,'core'));
$('#aerial').addEventListener('click',()=>aerial());$('#walk').addEventListener('click',()=>jump(currentPlace,'walk'));$('#lock').addEventListener('click',()=>nav.lock());
$('#reference-camera').addEventListener('click',()=>{currentPlace='huyuan';setNote('huyuan','aerial');const e=planWorld(data,459,449),t=planWorld(data,459,774);nav.fly([e[0],1.85,e[1]],[t[0],5.4,t[1]],'aerial');$('#mode-title').textContent='绘事院西立面 · 实景近似机位';});
$('#labels-toggle').addEventListener('click',()=>{labelsEnabled=!labelsEnabled;$('#labels').hidden=!labelsEnabled;$('#labels-toggle').setAttribute('aria-pressed',String(labelsEnabled));});
function applyQuality(value){quality=value;$('#quality').value=value;const dpr=value==='low'?1:value==='high'?Math.min(devicePixelRatio,1.75):Math.min(devicePixelRatio,1.35);renderer.setPixelRatio(dpr);renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=value!=='low';const size=value==='high'?2048:1024;if(world.sun.shadow.mapSize.x!==size){world.sun.shadow.mapSize.set(size,size);world.sun.shadow.map?.dispose();world.sun.shadow.map=null;}renderer.shadowMap.needsUpdate=true;world.trees.crowns.castShadow=value==='high';}
$('#quality').addEventListener('change',e=>applyQuality(e.target.value));window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();applyQuality(quality);});applyQuality(quality);
$('#evidence-toggle').addEventListener('click',()=>{world.evidence.visible=!world.evidence.visible;$('#evidence-toggle').setAttribute('aria-pressed',String(world.evidence.visible));toast(world.evidence.visible?'绿色：样板；赭色：照片近似；灰色：体块。建筑底边是地理轮廓。':'轮廓依据已隐藏');});
$('#places-toggle').addEventListener('click',()=>setPlacesOpen($('#places-toggle').getAttribute('aria-expanded')!=='true'));setPlacesOpen(!compactLayout.matches);compactLayout.addEventListener('change',e=>{if(e.matches)setPlacesOpen(false);});window.addEventListener('resize',()=>{mobile=matchMedia('(pointer:coarse)').matches||innerWidth<700;updateNavigationUI();});
for(const b of document.querySelectorAll('[data-move]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);nav.touchMoves.add(b.dataset.move);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>nav.touchMoves.delete(b.dataset.move));}
const content=$('#source-content');for(const item of [{title:'范围与日期',text:data.referenceDate+'。现覆盖五大片区及其连接道路，约1.77×1.57km建模窗口；不是官方保护红线。边界及原船厂范围见GeoJSON。'},{title:'米制与精度',text:'WGS84 局部 ENU；原点 119.4431389°E / 25.9905083°N。建筑轮廓有OSM支持；总平面两点配准，未通过独立测量验收。建筑高度、门窗尺寸、路宽和水位有估算。山体来自Mapzen公开DEM历史合成档案，约30m或更粗源分辨率；地坪和建筑平台经过局部平整，未校核国家高程基准。'},{title:'本期完成程度',text:'62处有来源的体量或形制；保留船厂样板，加入衙门、学堂、天后宫、昭忠祠、马限山近代建筑群、罗星塔等。新增区域为布局/形制阶段，官街商铺、钟楼、一号船坞等仍待资料。未达到全区照片级或测绘级1:1。'},{title:'尚缺资料',text:data.missing.join('；')+'。'}]){const article=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=item.title;p.textContent=item.text;article.append(h,p);content.append(article);}
for(const s of sources){const article=document.createElement('article'),h=document.createElement('h3'),a=document.createElement('a'),p=document.createElement('p');a.href=s.url;a.target='_blank';a.rel='noopener';a.textContent=s.title;h.append(a);p.textContent=`${s.date} · ${s.license} · ${s.use}`;article.append(h,p);content.append(article);}
$('#info-toggle').addEventListener('click',()=>{$('#info').showModal();nav.keys.clear();nav.touchMoves.clear();if(document.pointerLockElement)document.exitPointerLock();});$('#info-close').addEventListener('click',()=>$('#info').close());$('#info').addEventListener('click',e=>{if(e.target===$('#info')){const b=$('#info').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$('#info').close();}});
$('#capture').addEventListener('click',()=>{renderer.info.reset();renderer.render(scene,camera);const url=renderer.domElement.toDataURL('image/png'),a=document.createElement('a');a.href=url;a.download=`mawei-${currentPlace}-${nav.mode}.png`;a.click();});
const minimap=$('#minimap'),ctx=minimap.getContext('2d'),minX=Math.min(...data.boundary.map(p=>p[0])),maxX=Math.max(...data.boundary.map(p=>p[0])),minZ=Math.min(...data.boundary.map(p=>p[1])),maxZ=Math.max(...data.boundary.map(p=>p[1])),mapScale=Math.min(396/(maxX-minX),342/(maxZ-minZ)),offsetX=220-(minX+maxX)/2*mapScale,offsetZ=193-(minZ+maxZ)/2*mapScale;
const mp=([x,z])=>[x*mapScale+offsetX,z*mapScale+offsetZ];function poly(p,fill,stroke){ctx.beginPath();p.map(mp).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.2;ctx.stroke();}}
function mapDraw(){ctx.clearRect(0,0,440,400);ctx.fillStyle='#e6e9df';ctx.fillRect(0,0,440,400);poly(data.boundary,'#f3f0e5','#a8b59b');for(const w of data.city?.water||[])poly(w.polygon,'#a4b5b5');for(const p of data.city?.parks||[])poly(p.polygon,'#bdcaaa');for(const road of data.city?.roads||[]){ctx.beginPath();road.points.map(mp).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=['footway','steps'].includes(road.type)?'#bec4ae':'#b8b7aa';ctx.lineWidth=Math.max(1,road.width*mapScale);ctx.stroke();}for(const p of [...data.pools,...(data.city?.pools||[])])poly(p.polygon,'#a0aba7');for(const b of data.buildings)poly(b.footprint,b.completion==='sample'?'#b77959':b.completion==='photo'?'#baa787':'#c4c3b6','#9b9e8f');for(const tree of data.trees){const p=mp(tree.position);ctx.fillStyle='#8d9c76';ctx.beginPath();ctx.arc(...p,2.5,0,Math.PI*2);ctx.fill();}ctx.font='16px sans-serif';ctx.fillStyle='#626f56';ctx.fillText('N',407,26);ctx.beginPath();ctx.moveTo(413,35);ctx.lineTo(413,60);ctx.strokeStyle='#626f56';ctx.stroke();ctx.beginPath();ctx.moveTo(408,42);ctx.lineTo(413,34);ctx.lineTo(418,42);ctx.stroke();const position=mp(nav.mode==='walk'?[camera.position.x,camera.position.z]:[nav.orbit.target.x,nav.orbit.target.z]);ctx.save();ctx.translate(...position);ctx.rotate(nav.mode==='walk'?-nav.yaw:Math.atan2(camera.getWorldDirection(new T.Vector3()).x,-camera.getWorldDirection(new T.Vector3()).z));ctx.fillStyle='#516e48';ctx.beginPath();ctx.moveTo(0,-15);ctx.lineTo(-9,8);ctx.lineTo(9,8);ctx.closePath();ctx.fill();ctx.restore();ctx.strokeStyle='#647656';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(21,373);ctx.lineTo(21+(data.city?200:50)*mapScale,373);ctx.stroke();ctx.font='14px sans-serif';ctx.fillText(data.city?'200 m':'50 m',21,363);}
function jumpMap(x,z){const p=coll.safe(x,z),h=coll.height(...p);if(nav.mode==='walk')nav.fly([p[0],h+1.65,p[1]],[p[0]-Math.sin(nav.yaw),h+1.65,p[1]-Math.cos(nav.yaw)],'walk');else nav.fly([p[0]+20,h+55,p[1]+30],[p[0],h,p[1]],'aerial');toast('已定位到小地图选择位置');}
minimap.addEventListener('click',e=>{const b=minimap.getBoundingClientRect(),x=(e.clientX-b.left)*440/b.width,z=(e.clientY-b.top)*400/b.height;try{jumpMap((x-offsetX)/mapScale,(z-offsetZ)/mapScale);}catch(e){toast(e.message);}});minimap.addEventListener('keydown',e=>{if(e.key==='Enter')jump('huyuan',nav.mode);});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();window.maweiFail(Error('WebGL 上下文丢失。请重载页面或切换节能画质。'));});
function updateLabels(){if(!labelsEnabled)return;const wide=nav.mode==='aerial'&&camera.position.y>450,zoneNames={huyuan:'船厂片区',guanjie:'官街片区',consulate:'马限山片区',dock2:'旧港片区',luoxing:'罗星塔片区'},rects=[],overlaps=(r,q)=>r.left<q.right+5&&r.right>q.left-5&&r.top<q.bottom+4&&r.bottom>q.top-4,occupied=[...document.querySelectorAll('#hud > :not([hidden])')].filter(el=>getComputedStyle(el).display!=='none').map(el=>el.getBoundingClientRect()).filter(r=>r.width&&r.height);
 const nodes=[...labelNodes].sort((a,b)=>a.id===currentPlace?-1:b.id===currentPlace?1:camera.position.distanceToSquared(a.point)-camera.position.distanceToSquared(b.point));for(const {el,id,name,point} of nodes){const p=point.clone().project(camera),dist=camera.position.distanceTo(point),show=p.z<1&&p.z>-1&&Math.abs(p.x)<.95&&Math.abs(p.y)<.9&&(nav.mode==='aerial'||dist<90)&&(!wide||zoneNames[id]);el.hidden=!show;if(!show)continue;el.textContent=wide?zoneNames[id]:name;el.style.left=((p.x+1)*innerWidth/2)+'px';el.style.top=((1-p.y)*innerHeight/2)+'px';const r=el.getBoundingClientRect();if(r.left<8||r.right>innerWidth-8||r.top<8||r.bottom>innerHeight-8||occupied.some(q=>overlaps(r,q))||rects.some(q=>overlaps(r,q)))el.hidden=true;else rects.push(r);}}
function animate(now){const dt=Math.min(.05,(now-lastStamp)/1000);frameTime=frameTime*.95+(now-lastStamp)*.05;lastStamp=now;if(!document.hidden&&!$('#info').open)nav.update(dt,now);world.update(now/1000,camera,quality);renderer.info.reset();renderer.render(scene,camera);if(now-lastUI>180){mapDraw();updateLabels();const ll=toLonLat(camera.position.x,camera.position.z);$('#fps').textContent=`${Math.round(1000/frameTime)} fps`;$('#coordinates').textContent=`${ll[1].toFixed(5)} N / ${ll[0].toFixed(5)} E`;lastUI=now;}frames++;requestAnimationFrame(animate);}
progress(100,'场景已就绪');aerial(true);$('#loading').hidden=true;if(window.__maweiWarnings?.length)toast('部分贴图加载失败，已采用程序材质：'+window.__maweiWarnings.join('、')); 
window.__mawei={ready:true,data,sources,renderer,scene,camera,nav,collision:coll,world,jump,aerial,groundHeight:sampleGround,quality:()=>quality,applyQuality,frames:()=>frames,planWorld:(x,y)=>planWorld(data,x,y),stats:()=>({fps:1000/frameTime,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles})};requestAnimationFrame(animate);
