import * as T from 'three';
import {box,beam,planePolygon,batch} from './geometry.js';
import {metricUV} from './materials.js';
import {groundHeight,inside} from './geo.js';
export function buildCity(scene,data,m,riverMaterial){const city=data.city;if(!city)return null;const g=new T.Group();scene.add(g);const grid=data.heightGrid,geo=new T.BufferGeometry(),positions=[],indices=[],uv=[];
 const colours=[],parkColour=new T.Color(0xa5b38b),baseColour=new T.Color(0xd4d1c4);
 for(let j=0;j<grid.rows;j++)for(let i=0;i<grid.cols;i++){const x=grid.minX+i*grid.step,z=grid.minZ+j*grid.step;positions.push(x,grid.values[j*grid.cols+i],z);uv.push(x/2.4,z/2.4);const colour=[...city.parks,...city.grass].some(p=>inside([x,z],p.polygon))?parkColour:baseColour;colours.push(colour.r,colour.g,colour.b);}
 for(let j=0;j<grid.rows-1;j++)for(let i=0;i<grid.cols-1;i++){const k=j*grid.cols+i;indices.push(k,k+grid.cols,k+1,k+1,k+grid.cols,k+grid.cols+1);}
 geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setAttribute('color',new T.Float32BufferAttribute(colours,3));geo.setIndex(indices);geo.computeVertexNormals();const terrainMat=new T.MeshStandardMaterial({vertexColors:true,roughness:.98});const terrain=new T.Mesh(geo,terrainMat);terrain.receiveShadow=true;scene.add(terrain);
 // Park colours share the terrain vertices; no planar park overlay bridges a hill.
 for(const water of city.water)planePolygon(scene,riverMaterial,water.polygon,-2.02,water.holes).receiveShadow=false;
 const asphalt=new T.MeshStandardMaterial({color:0x767870,roughness:.94}),pathMat=m.stone;
 // Clip each road to the actual terrain triangles, so broad roads cannot sink into slopes.
 const clipTriangle=(poly,tri)=>{let p=poly;const cross=(a,b,q)=>(b[0]-a[0])*(q[1]-a[1])-(b[1]-a[1])*(q[0]-a[0]),sgn=Math.sign(cross(tri[0],tri[1],tri[2]));for(let i=0;i<3;i++){const a=tri[i],b=tri[(i+1)%3],next=[];for(let j=0;j<p.length;j++){const q=p[j],r=p[(j+1)%p.length],cq=cross(a,b,q)*sgn,cr=cross(a,b,r)*sgn;if(cq>=-1e-8)next.push(q);if((cq>=0)!==(cr>=0)){const t=cq/(cq-cr);next.push([q[0]+(r[0]-q[0])*t,q[1]+(r[1]-q[1])*t]);}}p=next;if(!p.length)break;}return p;};
 city.roads.forEach((road,roadIndex)=>{const vertices=[],foot=['steps','pedestrian','footway','path'].includes(road.type),lift=(foot?.10:.07)+roadIndex*.00001;for(let k=1;k<road.points.length;k++){const a=road.points[k-1],b=road.points[k],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(!len)continue;const nx=-dz/len*road.width/2,nz=dx/len*road.width/2,quad=[[a[0]+nx,a[1]+nz],[a[0]-nx,a[1]-nz],[b[0]-nx,b[1]-nz],[b[0]+nx,b[1]+nz]],xs=quad.map(p=>p[0]),zs=quad.map(p=>p[1]),loX=Math.max(0,Math.floor((Math.min(...xs)-grid.minX)/grid.step)),hiX=Math.min(grid.cols-2,Math.ceil((Math.max(...xs)-grid.minX)/grid.step)),loZ=Math.max(0,Math.floor((Math.min(...zs)-grid.minZ)/grid.step)),hiZ=Math.min(grid.rows-2,Math.ceil((Math.max(...zs)-grid.minZ)/grid.step));for(let j=loZ;j<=hiZ;j++)for(let i=loX;i<=hiX;i++){const x=grid.minX+i*grid.step,z=grid.minZ+j*grid.step,s=grid.step;for(const tri of [[[x,z],[x,z+s],[x+s,z]],[[x+s,z],[x,z+s],[x+s,z+s]]]){const p=clipTriangle(quad,tri);if(p.length<3)continue;const c=p.reduce((a,v)=>[a[0]+v[0]/p.length,a[1]+v[1]/p.length],[0,0]);if(!inside(c,data.boundary)||inside(c,data.coreBoundary)||city.water.some(w=>inside(c,w.polygon)&&!w.holes.some(h=>inside(c,h))))continue;for(let n=1;n<p.length-1;n++){const face=[p[0],p[n],p[n+1]],cross=(face[1][0]-face[0][0])*(face[2][1]-face[0][1])-(face[1][1]-face[0][1])*(face[2][0]-face[0][0]);if(Math.abs(cross)<1e-9)continue;if(cross>0)face.reverse();vertices.push(...face.flatMap(v=>[v[0],groundHeight(data,...v)+lift,v[1]]));}}}}if(vertices.length){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geo.computeVertexNormals();metricUV(geo);const mesh=new T.Mesh(geo,foot?pathMat:asphalt);mesh.receiveShadow=true;g.add(mesh);}});
 for(const pool of city.pools){const h=pool.baseHeight;const mat=new T.MeshStandardMaterial({color:0x647e70,metalness:.18,roughness:.36});planePolygon(g,mat,pool.polygon,h+.055);for(let i=0;i<pool.polygon.length;i++){const a=pool.polygon[i],b=pool.polygon[(i+1)%pool.polygon.length];beam(g,m.stone,[a[0],h+.11,a[1]],[b[0],h+.11,b[1]],.1);}}
 for(const dock of city.docks){const h=dock.baseHeight;planePolygon(g,m.dark,dock.polygon,h-1.39);for(let i=0;i<dock.polygon.length;i++){const a=dock.polygon[i],b=dock.polygon[(i+1)%dock.polygon.length],len=Math.hypot(b[0]-a[0],b[1]-a[1]),wall=box(g,m.stone,len,1.6,.75,(a[0]+b[0])/2,h-.6,(a[1]+b[1])/2);wall.rotation.y=-Math.atan2(b[1]-a[1],b[0]-a[0]);}}
 batch(g);return {terrain,ground:g};}
