// WGS84 geodetic -> ECEF -> local east/north. x=east, z=south, y=local up.
export const ORIGIN = [119.4431389, 25.9905083];
const A=6378137,E2=6.6943799901413165e-3,R=Math.PI/180;
function ecef(lon,lat){lon*=R;lat*=R;const n=A/Math.sqrt(1-E2*Math.sin(lat)**2);return [n*Math.cos(lat)*Math.cos(lon),n*Math.cos(lat)*Math.sin(lon),n*(1-E2)*Math.sin(lat)];}
const base=ecef(...ORIGIN),lon=ORIGIN[0]*R,lat=ORIGIN[1]*R;
const east=[-Math.sin(lon),Math.cos(lon),0],north=[-Math.sin(lat)*Math.cos(lon),-Math.sin(lat)*Math.sin(lon),Math.cos(lat)];
export function toLocal(lon,lat){const d=ecef(lon,lat).map((v,i)=>v-base[i]);return [d.reduce((n,v,i)=>n+v*east[i],0),-d.reduce((n,v,i)=>n+v*north[i],0)];}
// Intersect the local east/north ray with the WGS84 ellipsoid, then invert ECEF.
export function toLonLat(x,z){const up=[Math.cos(lat)*Math.cos(lon),Math.cos(lat)*Math.sin(lon),Math.sin(lat)],p=base.map((v,i)=>v+east[i]*x-north[i]*z),axes=[A*A,A*A,A*A*(1-E2)],qa=up.reduce((s,v,i)=>s+v*v/axes[i],0),qb=2*p.reduce((s,v,i)=>s+v*up[i]/axes[i],0),qc=p.reduce((s,v,i)=>s+v*v/axes[i],0)-1,t=-2*qc/(qb+Math.sqrt(qb*qb-4*qa*qc)),v=p.map((a,i)=>a+up[i]*t),horizontal=Math.hypot(v[0],v[1]);let phi=Math.atan2(v[2],horizontal*(1-E2));for(let i=0;i<6;i++){const n=A/Math.sqrt(1-E2*Math.sin(phi)**2);phi=Math.atan2(v[2]+E2*n*Math.sin(phi),horizontal);}return [Math.atan2(v[1],v[0])/R,phi/R];}
export function inside(p,polygon){let hit=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit;}return hit;}
export function distance(p,a,b){const x=b[0]-a[0],z=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*x+(p[1]-a[1])*z)/(x*x+z*z||1)));return Math.hypot(p[0]-a[0]-x*t,p[1]-a[1]-z*t);}
export function blockedPolygon(p,poly,r=.32){return inside(p,poly)||poly.some((a,i)=>distance(p,a,poly[(i+1)%poly.length])<r);}
export function groundHeight(data,x,z){if(data.coreBoundary&&inside([x,z],data.coreBoundary))return 0;const g=data.heightGrid;if(!g)return 0;const u=Math.max(0,Math.min(g.cols-1.000001,(x-g.minX)/g.step)),v=Math.max(0,Math.min(g.rows-1.000001,(z-g.minZ)/g.step)),i=Math.floor(u),j=Math.floor(v),fx=u-i,fz=v-j,k=j*g.cols+i,a=g.values[k],b=g.values[k+1],c=g.values[k+g.cols],d=g.values[k+g.cols+1];return fx+fz<=1?a+(b-a)*fx+(c-a)*fz:d+(c-d)*(1-fx)+(b-d)*(1-fz);}
export function collision(data){const trunks=data.trees.map(t=>Array.from({length:8},(_,i)=>[t.position[0]+Math.cos(i*Math.PI/4)*.24,t.position[1]+Math.sin(i*Math.PI/4)*.24]));const polys=[...data.buildings.map(b=>b.renderFootprint||b.footprint),...data.pools.map(p=>p.polygon),...data.obstacles.map(p=>p.polygon),...trunks,...(data.city?.pools||[]).map(p=>p.polygon),...(data.city?.docks||[]).map(p=>p.polygon)];const waters=data.city?.water||[];return {polys,blocked(x,z){const p=[x,z];return !inside(p,data.boundary)||data.boundary.some((a,i)=>distance(p,a,data.boundary[(i+1)%data.boundary.length])<.35)||waters.some(w=>inside(p,w.polygon)&&!w.holes?.some(h=>inside(p,h)))||polys.some(poly=>blockedPolygon(p,poly));},safe(x,z){if(!this.blocked(x,z))return [x,z];for(let r=.6;r<100;r+=.7)for(let a=0;a<Math.PI*2;a+=Math.PI/12){const p=[x+Math.cos(a)*r,z+Math.sin(a)*r];if(!this.blocked(...p))return p;}throw Error('此处没有可用步行地面，请选择定位点。');},height(x,z){return groundHeight(data,x,z);}};}
