import * as T from 'three';
import {mergeGeometries} from './vendor/BufferGeometryUtils.js';
import {metricUV} from './materials.js';
export function box(parent,mat,w,h,d,x=0,y=h/2,z=0){const mesh=new T.Mesh(metricUV(new T.BoxGeometry(w,h,d)),mat);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh;}
export function beam(parent,mat,a,b,r=.05){const d=new T.Vector3(...b).sub(new T.Vector3(...a)),mesh=new T.Mesh(metricUV(new T.CylinderGeometry(r,r,d.length(),7)),mat);mesh.position.copy(new T.Vector3(...a).add(new T.Vector3(...b)).multiplyScalar(.5));mesh.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());mesh.castShadow=true;parent.add(mesh);return mesh;}
export function planePolygon(parent,mat,points,y=0,holes=[]){const s=new T.Shape();points.forEach((p,i)=>i?s.lineTo(p[0],-p[1]):s.moveTo(p[0],-p[1]));s.closePath();for(const polygon of holes){const p=new T.Path();polygon.forEach((v,i)=>i?p.lineTo(v[0],-v[1]):p.moveTo(v[0],-v[1]));p.closePath();s.holes.push(p);}const geo=new T.ShapeGeometry(s);geo.rotateX(-Math.PI/2);metricUV(geo);const mesh=new T.Mesh(geo,mat);mesh.position.y=y;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
export function prism(parent,mat,points,h){const s=new T.Shape();points.forEach((p,i)=>i?s.lineTo(p[0],-p[1]):s.moveTo(p[0],-p[1]));s.closePath();const g=new T.ExtrudeGeometry(s,{depth:h,bevelEnabled:false});g.rotateX(-Math.PI/2);metricUV(g);const mesh=new T.Mesh(g,mat);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh;}
export function hippedRoof(parent,mat,w,d,y,rise,hip=true){const h=Math.min(w,d)*.24,points=[[-w/2,y,-d/2],[w/2,y,-d/2],[w/2,y,d/2],[-w/2,y,d/2],[-w/2+h,y+rise,0],[w/2-h,y+rise,0]],faces=hip?[[0,1,5],[0,5,4],[1,2,5],[2,3,4],[2,4,5],[3,0,4]]:[[0,1,5],[0,5,4],[2,3,4],[2,4,5]];
if(!hip){points[4]=[-w/2,y+rise,0];points[5]=[w/2,y+rise,0];faces.push([3,0,4],[1,2,5]);}
// Exterior winding: slopes must face upward, gable ends must face outward.
const arr=faces.flatMap(f=>[...f].reverse().flatMap(i=>points[i])),geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(arr,3));geo.computeVertexNormals();metricUV(geo);const mesh=new T.Mesh(geo,mat);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh;}
export function archPath(x,bottom,w,h,arch=.22){const s=new T.Shape(),l=x-w/2,r=x+w/2,top=bottom+h;s.moveTo(l,bottom);s.lineTo(r,bottom);s.lineTo(r,top-arch);s.quadraticCurveTo(x,top+arch,r-w,top-arch);s.lineTo(l,bottom);return s;}
// All static meshes are merged by material within a building/detail zone.
export function batch(group){group.updateMatrixWorld(true);const buckets=new Map();for(const o of [...group.children])o.traverse(n=>{if(!n.isMesh||Array.isArray(n.material))return;const key=n.material.uuid;if(!buckets.has(key))buckets.set(key,{mat:n.material,geos:[]});n.updateMatrix();const geo=n.geometry.clone();const matrix=new T.Matrix4().copy(group.matrixWorld).invert().multiply(n.matrixWorld);geo.applyMatrix4(matrix);geo.deleteAttribute('uv1');geo.deleteAttribute('uv2');const g=geo.index?geo.toNonIndexed():geo; if(g!==geo)geo.dispose();buckets.get(key).geos.push(g);});
const originals=[...group.children];group.clear();for(const {mat,geos} of buckets.values()){const geo=mergeGeometries(geos,false);if(!geo)throw Error('几何合并失败');geos.forEach(g=>g.dispose());const mesh=new T.Mesh(geo,mat);mesh.castShadow=!mat.transparent;mesh.receiveShadow=true;group.add(mesh);}originals.forEach(o=>o.traverse(n=>n.geometry?.dispose()));return group;}
