import * as T from 'three';
import {box,beam,prism,hippedRoof,archPath,planePolygon,batch} from './geometry.js';
import {metricUV} from './materials.js';
import {groundHeight} from './geo.js';

function sign(parent,text,w,y,z){const c=document.createElement('canvas');c.width=1024;c.height=192;const ctx=c.getContext('2d');ctx.fillStyle='#393a31';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#d6c5a0';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='80px serif';ctx.fillText(text,512,96);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const mesh=new T.Mesh(new T.PlaneGeometry(w,w*.1875),new T.MeshStandardMaterial({map:texture,roughness:.9}));mesh.position.set(0,y,z);mesh.rotation.y=Math.PI;parent.add(mesh);}
function curvedRoof(parent,material,w,d,y,rise){const vertices=[],steps=10;for(const side of [-1,1])for(let i=0;i<steps;i++){const t=i/steps,q=(i+1)/steps,z=side*d*.5*t,zz=side*d*.5*q,yy=y+rise*(1-t)**1.6+(t>.75?(t-.75)*.7:0),yyy=y+rise*(1-q)**1.6+(q>.75?(q-.75)*.7:0);const p=[[-w/2,yy,z],[w/2,yy,z],[-w/2,yyy,zz],[w/2,yyy,zz]],faces=side>0?[[0,2,1],[1,2,3]]:[[0,1,2],[1,3,2]];vertices.push(...faces.flatMap(f=>f.flatMap(i=>p[i])));}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geo.computeVertexNormals();metricUV(geo);const mesh=new T.Mesh(geo,material);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);box(parent,material,w,.18,.22,0,y+rise+.05,0);return mesh;}
function windowWall(parent,m,length,height,position,rotation,levels=1,brick=false){const group=new T.Group();group.position.set(...position);group.rotation.y=rotation;parent.add(group);const shape=new T.Shape();shape.moveTo(-length/2,0);shape.lineTo(length/2,0);shape.lineTo(length/2,height);shape.lineTo(-length/2,height);shape.closePath();const bays=Math.max(1,Math.floor(length/3.6)),width=Math.min(1.5,length/bays*.52),floor=height/levels;
 for(let row=0;row<levels;row++)for(let i=0;i<bays;i++){const x=(i-(bays-1)/2)*length/bays,y=.8+row*floor,h=Math.min(2.1,floor-1.25),opening=archPath(x,y,width,h,.12);shape.holes.push(opening);const glass=new T.Mesh(new T.ShapeGeometry(archPath(x,y+.05,width-.12,h-.1,.08)),m.glass);glass.position.z=.12;group.add(glass);for(const xx of [x-width/2,x,x+width/2])box(group,m.frame,.075,h,.16,xx,y+h/2,.04);for(const yy of [y,y+h/2,y+h])box(group,m.frame,width,.08,.16,x,yy,.03);box(group,m.mortar,width+.22,.13,.4,x,y-.02,-.06);}
 const geo=metricUV(new T.ExtrudeGeometry(shape,{depth:.32,bevelEnabled:false,curveSegments:8})),mesh=new T.Mesh(geo,brick?m.brick:m.plaster);mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);return group;
}
function hall(parent,m,w,d,z,height,roofMaterial=m.roof,bays=5,wood=false){const g=new T.Group();g.position.z=z;parent.add(g);box(g,m.stone,w+.7,.42,d+.7,0,.21,0);const wall=wood?m.wood:m.plaster;box(g,wall,w,height,.3,0,height/2+.42,d/2);box(g,wall,.32,height,d,-w/2,height/2+.42,0);box(g,wall,.32,height,d,w/2,height/2+.42,0);const bay=w/bays;
 for(let i=0;i<bays;i++){const x=(i-(bays-1)/2)*bay;box(g,m.wood,bay-.18,height-.5,.2,x,(height-.5)/2+.42,-d/2);for(let k=1;k<4;k++)box(g,m.frame,.07,height-.65,.12,x-bay/2+k*bay/4,height/2+.42,-d/2-.14);for(let k=0;k<4;k++)box(g,m.frame,bay-.1,.055,.12,x,1.25+k*.55,-d/2-.15);beam(g,m.frame,[x-bay/2,.42,-d/2-.7],[x-bay/2,height+.32,-d/2-.7],.105);}
 box(g,m.frame,w,.24,.3,0,height+.28,-d/2-.7);curvedRoof(g,roofMaterial,w+1.6,d+1.7,height+.42,2.1);return g;}
function fireWall(parent,m,x,d,height){const s=new T.Shape();s.moveTo(-d/2,0);s.lineTo(d/2,0);s.lineTo(d/2,height+.35);s.quadraticCurveTo(d*.27,height+.15,d*.17,height+1.5);s.quadraticCurveTo(0,height+3,-d*.17,height+1.5);s.quadraticCurveTo(-d*.27,height+.15,-d/2,height+.35);s.closePath();const g=metricUV(new T.ExtrudeGeometry(s,{depth:.28,bevelEnabled:false,curveSegments:12})),mesh=new T.Mesh(g,m.plaster);mesh.position.x=x;mesh.rotation.y=Math.PI/2;mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);}
export function buildLandmark(b,data,m){const f=b.frame,c=f.centre,g=new T.Group(),detail=new T.Group();g.position.set(c[0],b.baseHeight||0,c[1]);g.rotation.y=f.angle;g.userData={id:b.id,frame:f,detail,evidence:b.evidence};g.add(detail);const w=b.kind==='temple'?34:f.width,d=b.kind==='temple'?52:f.depth,h=b.height;
 const local=p=>p.map(v=>{const dx=v[0]-c[0],dz=v[1]-c[1],co=Math.cos(f.angle),si=Math.sin(f.angle);return [co*dx-si*dz,si*dx+co*dz];});
 // A retaining plinth reaches below the sampled terrain; no suspended wall bases.
 const plinth=Math.max(.18,(b.baseHeight||0)-Math.min(...b.renderFootprint.map(p=>groundHeight(data,...p)))+.15),foundation=local(['context','pagoda'].includes(b.kind)?b.footprint:b.renderFootprint),base=new T.Group();base.position.y=-plinth;g.add(base);prism(base,m.stone,foundation,plinth);
 if(b.kind==='pagoda'){
  const stone=m.stone.clone();stone.color.set(0xc2ae89);const ring=(radius,height,y,material=stone)=>{const mesh=new T.Mesh(metricUV(new T.CylinderGeometry(radius,radius,height,8,1,false,Math.PI/8)),material);mesh.position.y=y;mesh.castShadow=mesh.receiveShadow=true;g.add(mesh);};
  ring(4.3,.8,.4);ring(4.05,.5,1.05);for(let level=0;level<7;level++){const radius=3.55-level*.15,y=1.3+level*3.87,side=2*radius*Math.sin(Math.PI/8),apothem=radius*Math.cos(Math.PI/8);for(let i=0;i<8;i++){const a=i*Math.PI/4,face=new T.Group();face.rotation.y=a;face.position.set(Math.sin(a)*apothem,y,Math.cos(a)*apothem);g.add(face);const s=new T.Shape();s.moveTo(-side/2,0);s.lineTo(side/2,0);s.lineTo(side/2,3.25);s.lineTo(-side/2,3.25);s.closePath();s.holes.push(archPath(0,.38,.62,1.9,.24));const wall=new T.Mesh(metricUV(new T.ExtrudeGeometry(s,{depth:.35,bevelEnabled:false,curveSegments:10})),stone);wall.castShadow=wall.receiveShadow=true;face.add(wall);for(const yy of [.2,2.9])box(detail,stone,side+.1,.12,.15,Math.sin(a)*(apothem+.08),y+yy,Math.cos(a)*(apothem+.08)).rotation.y=a;}
   const rim=radius+.58;ring(rim,.24,y+3.35);ring(rim+.1,.16,y+3.57);for(let i=0;i<8;i++){const a=i*Math.PI/4,p=[Math.sin(a)*rim,y+3.69,Math.cos(a)*rim],q=[Math.sin(a+Math.PI/4)*rim,y+3.69,Math.cos(a+Math.PI/4)*rim];if(level<6){beam(detail,m.metal,[p[0],p[1],p[2]],[p[0],p[1]+.75,p[2]],.025);beam(detail,m.metal,[p[0],p[1]+.75,p[2]],[q[0],q[1]+.75,q[2]],.025);beam(detail,m.metal,[p[0],p[1]+.4,p[2]],[q[0],q[1]+.4,q[2]],.02);}}
  }ring(2.35,.45,28.9);const cap=new T.Mesh(metricUV(new T.ConeGeometry(2.35,1.25,8)),stone);cap.position.y=29.72;g.add(cap);const ball=new T.Mesh(new T.SphereGeometry(.42,16,10),m.rust);ball.position.y=30.8;g.add(ball);beam(detail,m.metal,[0,30.8,0],[0,31.5,0],.035);
 }else if(['yamen','temple','memorial'].includes(b.kind)){
  // Compound outline is factual; roof bands and unseen details remain estimates.
  const count=2,hallDepth=d*(b.kind==='temple'?.28:.25),hallWidth=w*.89;
  for(let i=0;i<count;i++)hall(g,m,hallWidth,hallDepth,-d*.30+i*d*.60,b.kind==='temple'?5.1:4.0,m.roof,b.kind==='memorial'?5:7,b.kind==='temple');
  for(const x of [-w*.445,w*.445]){box(g,m.plaster,2.7,3.5,d*.5,x,1.75,0);const wing=new T.Group();wing.position.x=x;wing.rotation.y=Math.PI/2;g.add(wing);curvedRoof(wing,m.roof,d*.54,3.4,3.6,1.1);}
  for(let i=0;i<3;i++)box(detail,m.stone,w*.46+i*.8,.14,.55,0,.07+i*.14,-d*.48+i*.55);
  for(const x of [-w*.45,w*.45])fireWall(g,m,x,hallDepth,4.5);
  sign(detail,b.kind==='yamen'?'总理船政':b.kind==='temple'?'船政天后宫':'昭忠祠',b.kind==='temple'?5:4.2,3.6,-d*.30-hallDepth/2-.34);
 }else if(b.kind==='pavilion'){
  box(g,m.stone,w,.3,d,0,.15,0);for(const x of [-w*.38,w*.38])for(const z of [-d*.38,d*.38])beam(g,m.frame,[x,.3,z],[x,h-1.3,z],.13);curvedRoof(g,m.roof,w+.7,d+.7,h-1.3,1.3);
 }else if(['colonial','school','industrial'].includes(b.kind)){
  // Real openings around the source polygon; repetitive unknown bays are labelled estimates.
  const p=local(b.footprint);for(let i=0;i<p.length;i++){const a=p[i],q=p[(i+1)%p.length],len=Math.hypot(q[0]-a[0],q[1]-a[1]),angle=-Math.atan2(q[1]-a[1],q[0]-a[0]);if(len>1)windowWall(g,m,len,h,[(a[0]+q[0])/2,0,(a[1]+q[1])/2],angle,b.levels,b.kind==='industrial');}
  planePolygon(g,m.dark,p,.02);planePolygon(g,m.roof,p,h);hippedRoof(g,m.roof,w+.35,d+.35,h,b.roofRise,false);for(const z of [-d/2,d/2])for(let level=1;level<=b.levels;level++)box(detail,m.mortar,w+.25,.15,.35,0,level*h/b.levels-.15,z);if(b.kind==='school'){for(let i=0;i<Math.floor(w/3.5);i++){const x=(i-(Math.floor(w/3.5)-1)/2)*3.5;beam(detail,m.mortar,[x,.2,-d/2-.6],[x,h,-d/2-.6],.1);}box(detail,m.stone,w,.3,1.4,0,h/2,-d/2-.6);}
 }else{const p=local(b.footprint);prism(g,m.plaster,p,h);planePolygon(g,m.metal,p,h+.01);}
 g.remove(detail);batch(g);batch(detail);g.add(detail);return g;
}
