import * as T from 'three';
function random(seed=417){return()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};}
function surface(kind){const n=1024,c=document.createElement('canvas');c.width=c.height=n;const ctx=c.getContext('2d'),rand=random(kind.length*1021),img=ctx.createImageData(n,n),base=kind==='brick'?[133,77,53]:kind==='tile'?[71,73,71]:kind==='stone'?[163,158,144]:kind==='wood'?[88,57,41]:kind==='rust'?[137,77,56]:kind==='grass'?[92,105,66]:[160,158,148];
for(let y=0;y<n;y++)for(let x=0;x<n;x++){const k=(y*n+x)*4,g=(rand()-.5)*17+Math.sin(x*.027)*2+Math.sin(y*.023)*2;for(let j=0;j<3;j++)img.data[k+j]=base[j]+g;img.data[k+3]=255;}ctx.putImageData(img,0,0);
if(kind==='brick'){const h=n/18,w=n/10;for(let row=0;row<18;row++)for(let col=-1;col<11;col++){const x=col*w+(row%2)*w/2,y=row*h,v=(rand()-.5)*16;ctx.fillStyle=`rgba(${140+v},${82+v},${61+v},.35)`;ctx.fillRect(x+2,y+2,w-4,h-4);ctx.strokeStyle='rgba(131,116,95,.75)';ctx.lineWidth=2.4;ctx.strokeRect(x,y,w,h);ctx.strokeStyle='rgba(52,40,30,.22)';ctx.lineWidth=1.5;ctx.strokeRect(x+3,y+3,w-6,h-6);}}
if(kind==='stone'){for(let y=0;y<4;y++)for(let x=0;x<4;x++){ctx.fillStyle=`rgba(90,86,75,${rand()*.06})`;ctx.fillRect(x*256,y*256,256,256);ctx.strokeStyle='rgba(73,72,67,.45)';ctx.lineWidth=2;ctx.strokeRect(x*256,y*256,256,256);}}
if(kind==='tile'){for(let y=0;y<10;y++)for(let x=0;x<12;x++){ctx.fillStyle=`rgba(135,137,128,${.07+rand()*.12})`;ctx.fillRect(x*n/12+4,y*n/10+2,n/12-8,n/10-4);ctx.strokeStyle='rgba(20,24,24,.65)';ctx.lineWidth=3;ctx.strokeRect(x*n/12,y*n/10,n/12,n/10);}}
if(kind==='wood'){for(let x=0;x<n;x+=4){ctx.strokeStyle=`rgba(27,24,20,${rand()*.3})`;ctx.beginPath();ctx.moveTo(x,0);for(let y=0;y<=n;y+=32)ctx.lineTo(x+Math.sin(y*.012+x)*3,y);ctx.stroke();}}
if(kind==='rust'){for(let x=0;x<8;x++){ctx.strokeStyle='rgba(47,41,37,.25)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x*128,0);ctx.lineTo(x*128,n);ctx.stroke();}}
const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;map.wrapS=map.wrapT=T.RepeatWrapping;
const bump=new T.CanvasTexture(c);bump.colorSpace=T.NoColorSpace;bump.wrapS=bump.wrapT=T.RepeatWrapping;
const roughCanvas=document.createElement('canvas');roughCanvas.width=roughCanvas.height=256;const rc=roughCanvas.getContext('2d');rc.fillStyle=kind==='rust'?'#a8a8a8':'#dfdfdf';rc.fillRect(0,0,256,256);const rough=new T.CanvasTexture(roughCanvas);rough.wrapS=rough.wrapT=T.RepeatWrapping;rough.colorSpace=T.NoColorSpace;
return {map,bumpMap:bump,roughnessMap:rough};}
export function materials(renderer){const make=(kind,params={})=>new T.MeshStandardMaterial({...surface(kind),roughness:.86,bumpScale:kind==='brick'?.018:.012,...params});const m={brick:make('brick'),grayBrick:make('brick',{color:0xa7afaa}),roof:make('tile',{roughness:.91}),stone:make('stone',{color:0xb7b8af}),wood:make('wood'),rust:make('rust',{metalness:.2,roughness:.7}),grass:make('grass',{roughness:1}),plaster:make('plaster',{color:0xe0dfd3}),metal:new T.MeshStandardMaterial({color:0x3d4544,metalness:.6,roughness:.62}),frame:new T.MeshStandardMaterial({color:0x704237,roughness:.62}),blueFrame:new T.MeshStandardMaterial({color:0x617575,metalness:.15,roughness:.65}),mortar:new T.MeshStandardMaterial({color:0xc3b9a1,roughness:.92}),dark:new T.MeshStandardMaterial({color:0x393a32,roughness:1}),glass:new T.MeshPhysicalMaterial({color:0x738888,roughness:.2,metalness:.12,transparent:true,opacity:.60,depthWrite:false,envMapIntensity:.75,side:T.DoubleSide}),leaf:new T.MeshStandardMaterial({color:0x657248,roughness:1,side:T.DoubleSide}),bark:make('wood',{color:0xaba393})};
for(const mat of Object.values(m))for(const key of ['map','bumpMap','roughnessMap'])if(mat[key])mat[key].anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());m.ironGlass=new T.MeshPhysicalMaterial({color:0xaac0bd,roughness:.12,transparent:true,opacity:.25,metalness:.06,depthWrite:false,envMapIntensity:1.05,side:T.DoubleSide});return m;}
export function metricUV(geo,span=2.4){const p=geo.attributes.position,n=geo.attributes.normal,uv=[];for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),nx=Math.abs(n.getX(i)),ny=Math.abs(n.getY(i)),nz=Math.abs(n.getZ(i));const coords=ny>nx&&ny>nz?[x,z]:nx>nz?[z,y]:[x,y];uv.push(coords[0]/span,coords[1]/span);}geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));return geo;}
export async function loadPBR(m,renderer,progress){const loader=new T.TextureLoader(),warnings=[];
const sets=[['brick','brick',1.25,'.jpg',['color','normalgl','roughness']],['stone','paving',2,'.webp',['color','normalgl','roughness']],['bark','bark',1.4,'.webp',['color','normalgl','roughness']],['plaster','plaster',1,'.webp',['color','normalgl','roughness']]];
await Promise.all(sets.map(async([key,alias,metres,ext,maps])=>{const results=await Promise.allSettled(maps.map(k=>loader.loadAsync(`./textures/${alias}-${k}${ext}`)));for(let i=0;i<results.length;i++)if(results[i].status==='rejected')warnings.push(`textures/${alias}-${maps[i]}${ext}`);if(results.some(r=>r.status==='rejected'))return;
const properties=['map','normalMap','roughnessMap','aoMap'],mat=m[key];for(let i=0;i<maps.length;i++){const tex=results[i].value;tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.setScalar(2.4/metres);tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());tex.colorSpace=i===0?T.SRGBColorSpace:T.NoColorSpace;mat[properties[i]]?.dispose();mat[properties[i]]=tex;}mat.bumpMap?.dispose();mat.bumpMap=null;mat.normalScale=new T.Vector2(.6,.6);mat.aoMapIntensity=.5;mat.needsUpdate=true;}));
if(warnings.length){window.__maweiWarnings=warnings;progress(20,'部分材质未载入，采用程序材质');}return warnings;}
