import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
export class Navigation{
 constructor(camera,canvas,collision,changed){this.camera=camera;this.canvas=canvas;this.collision=collision;this.changed=changed;this.mode='aerial';this.yaw=0;this.pitch=0;this.keys=new Set();this.touchMoves=new Set();this.transition=null;this.orbit=new OrbitControls(camera,canvas);this.orbit.enableDamping=true;this.orbit.dampingFactor=.08;this.orbit.minDistance=6;this.orbit.maxDistance=6000;this.orbit.maxPolarAngle=Math.PI*.49;this.orbit.target.set(-55,0,-100);this.drag=null;
 canvas.addEventListener('pointerdown',e=>{canvas.focus();if(this.mode==='walk'){this.drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}});
 canvas.addEventListener('pointermove',e=>{if(this.mode!=='walk')return;if(document.pointerLockElement===canvas){this.look(e.movementX,e.movementY);return;}if(this.drag?.id===e.pointerId){this.look(e.clientX-this.drag.x,e.clientY-this.drag.y);this.drag.x=e.clientX;this.drag.y=e.clientY;}});
 const end=e=>{if(this.drag?.id===e.pointerId)this.drag=null;};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('dblclick',()=>{if(this.mode==='walk')this.lock();});
 document.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,dialog'))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft'].includes(e.code)){e.preventDefault();this.keys.add(e.code);}if(e.code==='Escape'){this.keys.clear();this.drag=null;}});document.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>{this.keys.clear();this.touchMoves.clear();this.drag=null;});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.keys.clear();this.touchMoves.clear();}});
 }
 async lock(){try{if(this.mode==='walk')await this.canvas.requestPointerLock();}catch{this.changed('鼠标锁定不可用，可按住场景拖动观察。');}}
 look(dx,dy){this.yaw-=dx*.0025;this.pitch=T.MathUtils.clamp(this.pitch-dy*.0025,-1.12,1.05);this.applyLook();}
 applyLook(){this.camera.rotation.order='YXZ';this.camera.rotation.set(this.pitch,this.yaw,0);}
 setMode(mode){this.mode=mode;this.orbit.enabled=mode==='aerial';if(mode==='aerial'&&document.pointerLockElement)document.exitPointerLock();this.keys.clear();this.touchMoves.clear();this.drag=null;this.changed();}
 fly(position,target,mode='aerial',duration=1100){if(document.pointerLockElement)document.exitPointerLock();this.setMode(mode);const to=new T.Vector3(...position),look=new T.Vector3(...target);if(mode==='walk'){const p=this.collision.safe(to.x,to.z);to.set(p[0],this.collision.height(...p)+1.65,p[1]);}
 const fromQ=this.camera.quaternion.clone(),temp=this.camera.clone();temp.position.copy(to);temp.lookAt(look);if(duration<=0){this.transition=null;this.camera.position.copy(to);this.camera.quaternion.copy(temp.quaternion);this.orbit.target.copy(look);this.orbit.enabled=mode==='aerial';if(mode==='walk'){const e=new T.Euler().setFromQuaternion(this.camera.quaternion,'YXZ');this.yaw=e.y;this.pitch=e.x;this.applyLook();}return;}this.transition={start:performance.now(),duration,from:this.camera.position.clone(),to,fromQ,toQ:temp.quaternion.clone(),target:look,fromTarget:this.orbit.target.clone()};this.orbit.enabled=false;
 }
 get transitioning(){return !!this.transition;}
 update(dt,now){if(this.transition){const f=this.transition,t=Math.max(0,Math.min(1,(now-f.start)/f.duration)),ease=t*t*(3-2*t);this.camera.position.lerpVectors(f.from,f.to,ease);this.camera.quaternion.slerpQuaternions(f.fromQ,f.toQ,ease);this.orbit.target.lerpVectors(f.fromTarget,f.target,ease);if(t===1){this.transition=null;if(this.mode==='walk'){const e=new T.Euler().setFromQuaternion(this.camera.quaternion,'YXZ');this.yaw=e.y;this.pitch=e.x;this.applyLook();}else this.orbit.enabled=true;}return;}
 if(this.mode==='aerial'){this.orbit.update();return;}let f=(this.keys.has('KeyW')||this.keys.has('ArrowUp')||this.touchMoves.has('forward')?1:0)-(this.keys.has('KeyS')||this.keys.has('ArrowDown')||this.touchMoves.has('back')?1:0),s=(this.keys.has('KeyD')||this.keys.has('ArrowRight')||this.touchMoves.has('right')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')||this.touchMoves.has('left')?1:0);if(f||s){const norm=Math.hypot(f,s),speed=this.keys.has('ShiftLeft')?3.0:1.45,dx=(-Math.sin(this.yaw)*f+Math.cos(this.yaw)*s)*speed*dt/norm,dz=(-Math.cos(this.yaw)*f-Math.sin(this.yaw)*s)*speed*dt/norm,steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.12));for(let i=0;i<steps;i++){const x=this.camera.position.x+dx/steps,z=this.camera.position.z+dz/steps;if(!this.collision.blocked(x,this.camera.position.z))this.camera.position.x=x;if(!this.collision.blocked(this.camera.position.x,z))this.camera.position.z=z;}}
 this.camera.position.y=this.collision.height(this.camera.position.x,this.camera.position.z)+1.65;
 }
}
