import * as T from 'three';
import {materials,loadPBR} from './materials.js';
import {box,beam,planePolygon,batch} from './geometry.js';
import {buildBuilding} from './buildings.js';
import {Reflector} from './vendor/Reflector.js';
import {buildCity} from './city-scene.js';
import {groundHeight} from './geo.js';
function rng(seed=403){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
export function planWorld(data,x,y){const {a,b,anchor}=data.planRegistration;x-=anchor[0];y-=anchor[1];return [a*x+b*y,-b*x+a*y];}
function planGroup(data,x,y,parent){const p=planWorld(data,x,y),g=new T.Group();g.position.set(p[0],0,p[1]);g.rotation.y=data.planRegistration.angle;parent.add(g);return g;}
function planRect(data,parent,mat,x,y,w,h,height=.02){const g=planGroup(data,x+w/2,y+h/2,parent),s=data.planRegistration.scale;return box(g,mat,w*s,height,h*s,0,height/2,0);}
function waterMaterial(reflecting=false){const mat=new T.MeshStandardMaterial({color:reflecting?0x646c62:0x737e73,roughness:reflecting?.23:.46,metalness:.12,envMapIntensity:.8});mat.onBeforeCompile=shader=>{shader.uniforms.uTime={value:0};shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nuniform float uTime;').replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.y += 0.004 * sin(position.x * 1.8 + uTime*.5) * cos(position.z*2.4 + uTime*.4);');mat.userData.shader=shader;};return mat;}
function vegetation(data,m,scene){const woody=new T.Group();scene.add(woody);const rand=rng(319),leafCanvas=document.createElement('canvas');leafCanvas.width=leafCanvas.height=128;const ctx=leafCanvas.getContext('2d');
for(let i=0;i<190;i++){ctx.fillStyle=['#728059','#69754d','#8a9665','#546344'][i%4];ctx.beginPath();const x=12+rand()*104,y=12+rand()*104;ctx.ellipse(x,y,3+rand()*5,2+rand()*2,rand()*Math.PI,0,Math.PI*2);ctx.fill();}
const tex=new T.CanvasTexture(leafCanvas);tex.colorSpace=T.SRGBColorSpace;const mat=new T.MeshStandardMaterial({map:tex,roughness:1,alphaTest:.28,alphaToCoverage:true,side:T.DoubleSide,color:0xbfc2a4});const count=data.trees.length*150,crowns=new T.InstancedMesh(new T.PlaneGeometry(1.9,1.45),mat,count),dummy=new T.Object3D();crowns.castShadow=true;crowns.receiveShadow=true;let cursor=0;
for(let layer=0;layer<150;layer++)for(const tree of data.trees){const [x,z]=tree.position,h=tree.height,r=tree.radius,baseY=tree.baseHeight||0;if(layer===0){beam(woody,m.bark,[x,baseY,z],[x+.25,baseY+h*.62,z+.1],.18);for(let j=0;j<7;j++){const a=j*Math.PI*2/7+.2,end=[x+Math.cos(a)*r*.75,baseY+h*(.68+(j%3)*.07),z+Math.sin(a)*r*.75];beam(woody,m.bark,[x,baseY+h*.43,z],end,.07);beam(woody,m.bark,end,[end[0],end[1]+1.4,end[2]+.35],.035);}}
const a=rand()*Math.PI*2,v=rand(),rad=Math.sqrt(v)*r,y=h*.65+(rand()-.5)*r*.86+Math.sqrt(1-v)*r*.45;dummy.position.set(x+Math.cos(a)*rad,baseY+y,z+Math.sin(a)*rad);dummy.rotation.set(rand()*Math.PI,rand()*Math.PI,rand()*Math.PI);dummy.scale.setScalar((.8+rand()*.65)*Math.max(1,r/3.8));dummy.updateMatrix();crowns.setMatrixAt(cursor++,dummy.matrix);crowns.setColorAt(cursor-1,new T.Color().setHSL(.20+rand()*.035,.18+rand()*.13,.62+rand()*.15));}
batch(woody);crowns.instanceMatrix.needsUpdate=true;crowns.computeBoundingSphere();scene.add(crowns);return {crowns,woody};}
export async function createScene(renderer,data,progress){const scene=new T.Scene();scene.background=new T.Color(0xcbd6d9);scene.fog=null;const m=materials(renderer);await loadPBR(m,renderer,progress);progress(25,'构建米制地坪与岸线');
// An original generated sky environment, not a photographic site background.
const env=new T.Scene();env.background=new T.Color(0xc4d0d6);const skyGeo=new T.SphereGeometry(400,32,16),skyMat=new T.MeshBasicMaterial({side:T.BackSide,color:0xa8bdcb}),sky=new T.Mesh(skyGeo,skyMat);env.add(sky);const floor=new T.Mesh(new T.PlaneGeometry(1000,1000),new T.MeshBasicMaterial({color:0x818676}));floor.rotation.x=-Math.PI/2;floor.position.y=-30;env.add(floor);const pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(env,.02);scene.environment=environment.texture;pmrem.dispose();skyGeo.dispose();skyMat.dispose();floor.geometry.dispose();floor.material.dispose();
scene.environmentIntensity=.6;scene.add(new T.HemisphereLight(0xe1e7e7,0x656359,.85));const sun=new T.DirectionalLight(0xfff2dc,2.9);sun.position.set(-110,200,85);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-230;sun.shadow.camera.right=230;sun.shadow.camera.top=230;sun.shadow.camera.bottom=-230;sun.shadow.camera.far=3000;sun.shadow.normalBias=.25;sun.shadow.bias=-.0007;sun.shadow.radius=3;sun.target.position.set(-55,0,-110);scene.add(sun,sun.target);
const skyDome=new T.Mesh(new T.SphereGeometry(6000,24,12),new T.ShaderMaterial({side:T.BackSide,toneMapped:false,depthWrite:false,uniforms:{top:{value:new T.Color(0x7899b5)},horizon:{value:new T.Color(0xcbd8de)}},vertexShader:'varying vec3 direction; void main(){direction=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top;uniform vec3 horizon;varying vec3 direction;void main(){float h=clamp(normalize(direction).y*.8+.06,0.,1.);gl_FragColor=vec4(mix(horizon,top,pow(h,.65)),1.);\n #include <tonemapping_fragment>\n #include <colorspace_fragment> }'}));scene.add(skyDome);const ground=new T.Group();scene.add(ground);planePolygon(ground,m.stone,data.coreBoundary||data.boundary,0,data.pools.map(p=>p.polygon));const riverMat=waterMaterial(),riverCorners=[[210,-1400],[1622,-1400],[1622,107],[210,107]].map(p=>planWorld(data,...p));const river=data.city?new T.Group():planePolygon(scene,riverMat,riverCorners,-2);river.receiveShadow=false;const city=buildCity(scene,data,m,riverMat);
// Checked straight quay segment. Retaining-wall height is explicitly estimated.
const g=planGroup(data,916,107,ground),length=(1622-210)*data.planRegistration.scale;box(g,m.stone,length,2.5,1,0,-1.25,0);box(g,m.mortar,length,.14,1.15,0,-.02,.05);
const [quayA,quayB]=data.quay;beam(ground,m.metal,[quayA[0],1.03,quayA[1]],[quayB[0],1.03,quayB[1]],.035);for(let t=0;t<=1;t+=1/120){const x=quayA[0]+(quayB[0]-quayA[0])*t,z=quayA[1]+(quayB[1]-quayA[1])*t;beam(ground,m.metal,[x,0,z],[x,1.05,z],.025);}
const poolMats=[],pools=[];for(const p of data.pools){const mat=waterMaterial(true);poolMats.push(mat);pools.push(planePolygon(scene,mat,p.polygon,-.055));for(let i=0;i<p.polygon.length;i++){const a=p.polygon[i],b=p.polygon[(i+1)%p.polygon.length];beam(ground,m.dark,[a[0],-.04,a[1]],[b[0],-.04,b[1]],.1);}}
// OSM road centre lines; widths are estimates. Segment top surfaces share one elevation.
for(const road of data.roads)for(let i=1;i<road.points.length;i++){const a=road.points[i-1],b=road.points[i],dist=Math.hypot(b[0]-a[0],b[1]-a[1]),mesh=box(ground,m.plaster,dist,.016,road.width,(a[0]+b[0])/2,.016,(a[1]+b[1])/2);mesh.rotation.y=-Math.atan2(b[1]-a[1],b[0]-a[0]);}
for(const r of [[380,686,246,30],[696,730,63,242],[896,358,88,295],[875,455,22,190],[1500,730,70,246]])planRect(data,ground,m.grass,...r,.035);
planRect(data,ground,m.stone,948,726,220,246,.024);
for(let i=0;i<19;i++)planRect(data,ground,m.dark,948+i*12.2,726,1,246,.031);for(let i=0;i<20;i++)planRect(data,ground,m.dark,948,726+i*12.3,220,1,.031);
// Non-walkable slipway: location from the numbered plan, slope and rail dimensions estimated.
const slip=planGroup(data,162,540,ground),sw=93*data.planRegistration.scale,sd=669*data.planRegistration.scale;const slab=box(slip,m.plaster,sw,.3,sd,0,-.65,0);slab.rotation.x=.01;for(const x of [-sw*.34,0,sw*.34])box(slip,m.metal,.09,.08,sd,x,-.45,0);
const platforms=[];for(const [x,y,w,h,steps] of [[625,916,42,23,2]]){const g=planGroup(data,x+w/2,y+h/2,ground),s=data.planRegistration.scale;for(let i=0;i<steps;i++)box(g,m.wood,w*s-i*.38,.15,h*s-i*.38,0,.075+i*.15,0);platforms.push({center:planWorld(data,x+w/2,y+h/2),width:w*s,depth:h*s,angle:data.planRegistration.angle,height:steps*.15});}
for(const [x,y] of [[384,689],[664,690],[706,875],[825,733],[899,924]]){const p=planWorld(data,x,y);beam(ground,m.metal,[p[0],0,p[1]],[p[0],4.2,p[1]],.045);beam(ground,m.metal,[p[0],4.2,p[1]],[p[0]+.55,4.2,p[1]],.04);const lamp=new T.Mesh(new T.ConeGeometry(.25,.22,12),m.metal);lamp.position.set(p[0]+.55,3.99,p[1]);ground.add(lamp);}
batch(ground);progress(40,'载入有来源的建筑轮廓');const buildingGroups=[];for(let i=0;i<data.buildings.length;i++){const b=data.buildings[i],g=buildBuilding(b,data,m);scene.add(g);buildingGroups.push(g);progress(40+40*(i+1)/data.buildings.length,'建模 '+b.name);await new Promise(r=>setTimeout(r,0));}
progress(85,'生成定位植被与近景材质');const trees=vegetation(data,m,scene),outlines=[];
for(const b of data.buildings){const points=b.footprint.map(p=>new T.Vector3(p[0],(b.baseHeight||0)+.08,p[1]));points.push(points[0]);const outline=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:b.completion==='sample'?0x268264:b.completion==='photo'?0xb58542:0x8c8994,depthTest:false}));outline.renderOrder=12;outlines.push(outline);}
const reflections=[];for(const p of data.pools){const shape=new T.Shape();p.polygon.forEach((v,i)=>i?shape.lineTo(v[0],-v[1]):shape.moveTo(v[0],-v[1]));shape.closePath();const mirror=new Reflector(new T.ShapeGeometry(shape),{color:0x747a68,textureWidth:512,textureHeight:512,clipBias:.003});mirror.rotation.x=-Math.PI/2;mirror.position.y=-.04;mirror.material.uniforms.waterTime={value:0};mirror.material.fragmentShader=mirror.material.fragmentShader.replace("uniform vec3 color;","uniform vec3 color; uniform float waterTime;").replace("vec4 base = texture2DProj( tDiffuse, vUv );","vec4 wavUv = vUv; wavUv.xy += .0006 * wavUv.w * vec2(sin(vUv.x*4.0+waterTime*.35), cos(vUv.y*5.0+waterTime*.23)); vec4 base = texture2DProj(tDiffuse, wavUv);");mirror.onBeforeRender=((original)=>function(renderer,scene,camera){const hidden=reflections.filter(v=>v!==this).map(v=>[v,v.visible]);hidden.forEach(([v])=>v.visible=false);const now=performance.now();if(now-(this.userData.lastReflection||0)>75){original.call(this,renderer,scene,camera);this.userData.lastReflection=now;}hidden.forEach(([v,was])=>v.visible=was);})(mirror.onBeforeRender);scene.add(mirror);reflections.push(mirror);}const evidence=new T.Group();evidence.add(...outlines);evidence.visible=false;scene.add(evidence);
return {scene,m,sun,buildingGroups,trees,evidence,river,pools,platforms,environment,reflections,city,update(time,camera,quality){skyDome.position.copy(camera.position);const baseY=groundHeight(data,camera.position.x,camera.position.z),near=camera.position.y-baseY<20;sun.shadow.camera.left=sun.shadow.camera.bottom=near?-55:(data.city?-1200:-230);sun.shadow.camera.right=sun.shadow.camera.top=near?55:(data.city?1200:230);sun.shadow.normalBias=near?.08:.25;sun.shadow.bias=near?-.0001:-.0007;if(near){sun.target.position.set(camera.position.x,baseY,camera.position.z);sun.position.set(camera.position.x-55,baseY+200,camera.position.z+195);}else{sun.target.position.set(data.city?350:-55,0,data.city?150:-110);sun.position.set(data.city?295:-110,200,data.city?345:85);}sun.shadow.camera.updateProjectionMatrix();let closest=0,best=Infinity;for(let i=0;i<data.pools.length;i++){const p=data.pools[i].polygon,center=p.reduce((a,v)=>[a[0]+v[0]/p.length,a[1]+v[1]/p.length],[0,0]),dist=Math.hypot(camera.position.x-center[0],camera.position.z-center[1]);if(dist<best){best=dist;closest=i;}}for(let i=0;i<reflections.length;i++){const r=reflections[i];r.visible=quality!=='low'&&camera.position.y<35&&best<100&&i===closest;r.material.uniforms.waterTime.value=time;}for(const mat of [riverMat,...poolMats])if(mat.userData.shader)mat.userData.shader.uniforms.uTime.value=time;for(const g of buildingGroups){const d=camera.position.distanceTo(g.position);g.userData.detail.visible=d<(quality==='low'?95:quality==='balanced'?220:420);}trees.crowns.count=data.trees.length*(quality==='low'?75:150);}};}
