import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {makeMaterials} from './materials.js';
import {buildSite} from './models.js';
import {makeGround,makeLandscape,trees,makeJets,inside,segmentDistance} from './landscape.js';
import './style.css';
const $=id=>document.getElementById(id);
const handlers=[];const listen=(el,event,cb,opts)=>{el.addEventListener(event,cb,opts);handlers.push(()=>el.removeEventListener(event,cb,opts))};
let renderer,scene,camera,controls,data,m,ground,landscape,foliage,jetEffect,sourceList,ready=false,frameId;
let mode='orbit',quality='medium',yaw=0,pitch=0,dragging=false,selected=null,showLabels=false,autoRotate=false,tourTime=0,last=performance.now(),stats=[],lastUI=0,toastTimer;
const keys=new Set(),models=[],obstacles=[],plazas=[];
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',3800)}
function progress(n,msg){$('progress').value=n;$('loading-text').textContent=msg}
async function fetchJSON(url){const r=await fetch(url);if(!r.ok)throw new Error(`资料资源读取失败：${url}（HTTP ${r.status}）`);return r.json()}
function blockAt(x,z){return obstacles.some(o=>Math.abs(x-o.x)<o.w/2+.42&&Math.abs(z-o.z)<o.d/2+.42)}
function validPosition(x,z){if(!inside([x,z],data.boundary)||ground.wet(x,z)||blockAt(x,z))return false;return ground.routeDistance(x,z).distance<2.4||plazas.some(p=>Math.abs(x-p.x)<p.w/2&&Math.abs(z-p.z)<p.d/2)}
function nearestSafe(point,site){let candidates=[];for(const s of ground.segments){const nearest=segmentDistance(...point,s.a,s.b);if(validPosition(...nearest.point))candidates.push(nearest.point);for(let t=0;t<=1;t+=.2){let p=[s.a[0]+(s.b[0]-s.a[0])*t,s.a[1]+(s.b[1]-s.a[1])*t];if(validPosition(...p))candidates.push(p)}}for(let r=4;r<95;r+=4)for(let a=0;a<Math.PI*2;a+=Math.PI/12){let p=[point[0]+Math.cos(a)*r,point[1]+Math.sin(a)*r];if(validPosition(...p))candidates.push(p)}candidates.sort((a,b)=>Math.hypot(a[0]-point[0],a[1]-point[1])-Math.hypot(b[0]-point[0],b[1]-point[1]));return candidates[0]||site?.position}
function nearestSite(){const p=camera.position;return data.sites.reduce((a,s)=>Math.hypot(s.position[0]-p.x,s.position[1]-p.z)<Math.hypot(a.position[0]-p.x,a.position[1]-p.z)?s:a,data.sites[0])}
function setMode(next,site=selected||nearestSite()){
 if(next==='walk'&&matchMedia('(pointer:coarse)').matches){toast('触屏使用鸟瞰模式；景点定位仍可使用。');return}
 mode=next;controls.enabled=mode==='orbit';controls.autoRotate=false;autoRotate=false;keys.clear();$('crosshair').hidden=mode!=='walk';$('orbit-mode').classList.toggle('active',mode==='orbit');$('walk-mode').classList.toggle('active',mode==='walk');
 if(mode==='walk'){const p=nearestSafe([site.position[0],site.position[1]+Math.max(40,site.size[1])],site);if(!p||!validPosition(...p)){toast('此点暂缺安全步行落脚位置，请用鸟瞰查看。');setMode('orbit',site);return}camera.position.set(p[0],ground.height(...p)+1.7,p[1]);yaw=Math.atan2(p[0]-site.position[0],p[1]-site.position[1]);pitch=0;camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);$('hint').textContent='WASD移动 · 拖动观察 · 双击锁定 · Esc释放';toast('已进入虚拟安全步道 · 视高1.7米');}
 else{document.exitPointerLock?.();controls.target.copy(camera.position).add(new T.Vector3(-Math.sin(yaw)*35,0,-Math.cos(yaw)*35));camera.position.y=Math.max(camera.position.y,12);controls.target.y=2;controls.update();$('hint').textContent='拖动旋转 · 滚轮缩放 · 右键平移'}
}
function jump(s,walking=false){selected=s;updateSelection();if(walking){setMode('walk',s);$('info-card').hidden=true;return}if(mode==='walk')setMode('orbit',s);controls.autoRotate=false;autoRotate=false;const d=s.kind==='western'?76:125;camera.position.set(s.position[0]+d*.6,ground.height(...s.position)+d*.34,s.position[1]+d);controls.target.set(s.position[0],5,s.position[1]+(s.name==='大水法'?9:0));controls.update();$('scene-title').textContent=s.name;$('scene-description').textContent=s.zone+' · '+s.exterior;}
function home(){if(mode==='walk')setMode('orbit');autoRotate=false;controls.autoRotate=false;camera.position.set(80,1570,1680);controls.target.set(-100,0,-20);controls.update();$('scene-title').textContent='圆明三园 · 山水格局';$('scene-description').textContent='圆明园在西 · 长春园在东 · 绮春园在东南 / 边界与水岸为地理代理';}
function detail(){let s=data.sites.find(s=>s.name==='大水法');if(mode==='walk')setMode('orbit',s);autoRotate=false;controls.autoRotate=false;camera.position.set(s.position[0]+5.7,3.8,s.position[1]+11);controls.target.set(s.position[0]+1.4,5.5,s.position[1]+.5);controls.update();$('scene-title').textContent='大水法 · 石龛近景';$('scene-description').textContent='实体叠盘、线脚与曲线构件 / 雕刻仍为简化示意';}
function updateSelection(){for(const el of document.querySelectorAll('.site-row'))el.classList.toggle('selected',el.dataset.id===selected?.id)}
function info(s){selected=s;updateSelection();$('info-card').hidden=false;const el=$('info-content');el.replaceChildren();const over=document.createElement('span');over.className='eyebrow';over.textContent=`${s.zone} / 1786`;const h=document.createElement('h2');h.textContent=s.name;const status=document.createElement('div');status.className='status';status.textContent=s.status;const p=document.createElement('p');p.textContent=s.note+(s.name==='大水法'?' 铜犬、铜鹿与精细雕刻尚未复原，喷流只是水法原理示意。':'');const dl=document.createElement('dl');for(const [name,value]of [['外观',s.exterior],['内部',s.interior],['色彩',s.color],['陈设',s.furnishing]]){let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;dl.append(dt,dd)}const links=document.createElement('div');for(const id of s.sources){const ref=sourceList.find(r=>r.id===id);if(!ref)continue;let a=document.createElement('a');a.href=ref.url;a.target='_blank';a.rel='noopener';a.textContent=ref.short+' ↗';links.append(a)}el.append(over,h,status,p,dl,links)}
function renderList(zone='全部',query=''){const list=$('site-list');list.replaceChildren();const ordered=[...data.sites].sort((a,b)=>{const n=['大水法','远瀛观','海晏堂','谐奇趣','黄花阵','九洲清晏','方壶胜境','蓬岛瑶台','海岳开襟','含经堂','正觉寺'];return(n.indexOf(a.name)<0?100:n.indexOf(a.name))-(n.indexOf(b.name)<0?100:n.indexOf(b.name))});const items=ordered.filter(s=>(zone==='全部'||s.zone===zone)&&s.name.includes(query.trim()));$('count').textContent=`${items.length} 处景点`;items.forEach((s,i)=>{let button=document.createElement('button');button.className='site-row';button.dataset.id=s.id;button.innerHTML='<span class="num"></span><span class="text"><strong></strong><small></small></span><span class="arrow">↗</span>';button.querySelector('.num').textContent=String(i+1).padStart(2,'0');button.querySelector('strong').textContent=s.name;button.querySelector('small').textContent=s.zone+' · '+(s.exterior.startsWith('B')?'图像约束':'推测性外观');button.addEventListener('click',()=>{info(s);jump(s)});list.append(button)});if(!items.length){let p=document.createElement('p');p.textContent='没有匹配的景点，请尝试其他名称。';p.style.fontSize='11px';list.append(p)}updateSelection()}
const mapXY=p=>[(p[0]+1470)/2700*270+5,(p[1]+880)/1930*195+5];
function drawMap(){const svg=$('minimap'),ns='http://www.w3.org/2000/svg';const make=(name,attrs={})=>{let el=document.createElementNS(ns,name);for(const [key,value]of Object.entries(attrs))el.setAttribute(key,value);return el};const ringPath=r=>'M'+r.map(p=>mapXY(p).join(',')).join('L')+'Z';svg.append(make('path',{d:ringPath(data.boundary),fill:'#e5e9dc',stroke:'#c4ceb5','stroke-dasharray':'3 2','stroke-width':1}));for(const w of data.water)svg.append(make('path',{d:ringPath(w.outer)+w.holes.map(ringPath).join(''),fill:'#acc6bf','fill-rule':'evenodd',stroke:'#98b7ab','stroke-width':.35}));for(const p of data.paths)svg.append(make('path',{d:'M'+p.points.map(a=>mapXY(a).join(',')).join('L'),fill:'none',stroke:'#a59572','stroke-width':.3,opacity:.5}));for(const s of data.sites){const p=mapXY(s.position),circle=make('circle',{cx:p[0],cy:p[1],r:2.5,fill:s.kind==='western'?'#a07f4d':'#748762',class:'site-dot',role:'button',tabindex:0,'aria-label':s.name});circle.addEventListener('click',()=>{info(s);jump(s)});circle.addEventListener('keydown',e=>{if(e.key==='Enter'){info(s);jump(s)}});svg.append(circle)}for(const [name,p]of [['圆明园',[-800,-100]],['福海',[20,-220]],['长春园',[750,-180]],['绮春园',[510,470]]]){let xy=mapXY(p),t=make('text',{x:xy[0],y:xy[1],'font-size':8,fill:'#62775b','text-anchor':'middle'});t.textContent=name;svg.append(t)}svg.append(make('path',{id:'map-view',d:'M0,-6L-4,4L0,2L4,4Z',fill:'#ad693f',stroke:'#fff','stroke-width':1}));}
function setQuality(q){quality=q;const settings={low:{dpr:1,shadow:0,count:.45},medium:{dpr:1.3,shadow:1024,count:.75},high:{dpr:1.7,shadow:2048,count:1}}[q];renderer.setPixelRatio(Math.min(devicePixelRatio,settings.dpr));renderer.shadowMap.enabled=!!settings.shadow;sun.shadow.mapSize.set(settings.shadow||512,settings.shadow||512);if(sun.shadow.map){sun.shadow.map.dispose();sun.shadow.map=null}if(foliage){foliage.canopies.count=Math.floor(foliage.total*settings.count);foliage.trunks.count=foliage.canopies.count;}for(const lod of models)lod.levels[1].distance=q==='high'?520:q==='medium'?340:200;resize();}
let sun;
function resize(){const w=window.innerWidth,h=window.innerHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}
function updateWalk(dt){let dx=0,dz=0;if(keys.has('KeyW')||keys.has('ArrowUp'))dz--;if(keys.has('KeyS')||keys.has('ArrowDown'))dz++;if(keys.has('KeyA')||keys.has('ArrowLeft'))dx--;if(keys.has('KeyD')||keys.has('ArrowRight'))dx++;if(dx||dz){const len=Math.hypot(dx,dz),speed=keys.has('ShiftLeft')?3.2:1.6,step=speed*dt,lenStep=step/len;const vx=(Math.cos(yaw)*dx+Math.sin(yaw)*dz)*lenStep,vz=(-Math.sin(yaw)*dx+Math.cos(yaw)*dz)*lenStep;const divisions=Math.max(1,Math.ceil(step/.18));for(let i=0;i<divisions;i++){let x=camera.position.x+vx/divisions,z=camera.position.z+vz/divisions;if(validPosition(x,z)){camera.position.x=x;camera.position.z=z}else{if(validPosition(x,camera.position.z))camera.position.x=x;if(validPosition(camera.position.x,z))camera.position.z=z}}camera.position.y=ground.height(camera.position.x,camera.position.z)+1.7;}camera.rotation.set(pitch,yaw,0)}
function updateLabels(){if(!showLabels)return;for(const s of data.sites){const el=$('label-'+s.id);let v=new T.Vector3(s.position[0],18,s.position[1]),dist=v.distanceTo(camera.position);v.project(camera);let visible=v.z<1&&v.z>-1&&Math.abs(v.x)<.98&&Math.abs(v.y)<.98&&dist<900;el.hidden=!visible;if(visible){el.style.left=(v.x*.5+.5)*innerWidth+'px';el.style.top=(-v.y*.5+.5)*innerHeight+'px'}}}
function animate(now){frameId=requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);stats.push(now-last);if(stats.length>180)stats.shift();last=now;if(mode==='walk')updateWalk(dt);else controls.update();landscape.clockUniform.value=now*.001;if(jetEffect)jetEffect.mat.uniforms.time.value=now*.001;sun.position.set(camera.position.x-110,170,camera.position.z-95);sun.target.position.set(camera.position.x,0,camera.position.z);sun.target.updateMatrixWorld();for(const lod of models)lod.update(camera);renderer.render(scene,camera);if(now-lastUI>250){lastUI=now;const center=mode==='walk'?camera.position:controls.target;$('position').textContent=`E ${center.x.toFixed(0)} m · N ${(-center.z).toFixed(0)} m`;$('fps').textContent=`${Math.round(1000/(stats.reduce((a,b)=>a+b,0)/stats.length))} FPS`;const xy=mapXY([center.x,center.z]);$('map-view').setAttribute('transform',`translate(${xy[0]},${xy[1]}) rotate(${mode==='walk'?-yaw*180/Math.PI:controls.getAzimuthalAngle()*-180/Math.PI})`);updateLabels();}}
function events(){let activeZone='全部';listen($('search'),'input',()=>renderList(activeZone,$('search').value));for(const b of document.querySelectorAll('[data-zone]'))listen(b,'click',()=>{activeZone=b.dataset.zone;for(const a of document.querySelectorAll('[data-zone]'))a.classList.toggle('active',a===b);renderList(activeZone,$('search').value)});
 listen($('fold-list'),'click',()=>{let folded=$('explorer').classList.toggle('folded');$('fold-list').textContent=folded?'+':'−'});listen($('fold-map'),'click',()=>{let folded=$('map-panel').classList.toggle('folded');$('fold-map').textContent=folded?'+':'−';$('fold-map').setAttribute('aria-expanded',String(!folded))});
 for(const [button,dialog]of [['sources-open','sources-dialog'],['help-open','help-dialog']])listen($(button),'click',()=>{keys.clear();document.exitPointerLock?.();$(dialog).showModal()});for(const button of document.querySelectorAll('.dialog-close'))listen(button,'click',()=>button.closest('dialog').close());
 listen($('info-close'),'click',()=>$('info-card').hidden=true);listen($('jump-orbit'),'click',()=>jump(selected));listen($('jump-walk'),'click',()=>jump(selected,true));listen($('walk-mode'),'click',()=>setMode('walk'));listen($('orbit-mode'),'click',()=>setMode('orbit'));listen($('reset-view'),'click',home);listen($('detail-view'),'click',detail);listen($('quality'),'change',e=>setQuality(e.target.value));listen($('labels-toggle'),'click',()=>{showLabels=!showLabels;$('labels').hidden=!showLabels;$('labels-toggle').setAttribute('aria-pressed',showLabels);updateLabels()});listen($('soundless-tour'),'click',()=>{if(mode==='walk')setMode('orbit');controls.autoRotate=!controls.autoRotate;controls.autoRotateSpeed=.28;});listen(window,'resize',resize);
 listen(window,'keydown',e=>{if(e.target.matches('input,select')||document.querySelector('dialog[open]'))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Slash'){e.preventDefault();$('search').focus()}if(e.code==='KeyH')home();if(e.code==='Digit1')setMode('orbit');if(e.code==='Digit2')setMode('walk')});listen(window,'keyup',e=>keys.delete(e.code));listen(window,'blur',()=>{keys.clear();dragging=false});listen(document,'visibilitychange',()=>keys.clear());listen(document,'pointerlockchange',()=>keys.clear());
 let down=null;listen(renderer.domElement,'pointerdown',e=>{down=[e.clientX,e.clientY];if(mode==='walk')dragging=true});listen(window,'pointerup',()=>dragging=false);listen(window,'pointermove',e=>{if(mode==='walk'&&(dragging||document.pointerLockElement===renderer.domElement)){yaw-=e.movementX*.003;pitch=Math.max(-1.3,Math.min(1.3,pitch-e.movementY*.003))}});listen(renderer.domElement,'dblclick',()=>{if(mode==='walk')renderer.domElement.requestPointerLock?.()?.catch(()=>toast('鼠标锁定不可用，可以按住鼠标拖动观察。'))});
 const ray=new T.Raycaster();listen(renderer.domElement,'click',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5||document.pointerLockElement)return;ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);let hits=ray.intersectObjects(models,true);if(hits.length){let p=hits[0].object;while(p&&!p.userData.site)p=p.parent;if(p)info(p.userData.site)}});
}
async function init(){try{progress(8,'读取1786历史截面与局部米制坐标…');[data,sourceList]=await Promise.all([fetchJSON('data/layout.json'),fetchJSON('data/sources.json')]);renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;renderer.shadowMap.type=T.PCFSoftShadowMap;$('viewport').append(renderer.domElement);scene=new T.Scene();scene.background=new T.Color('#c1d5db');scene.fog=new T.Fog('#c9d8d9',2600,6500);camera=new T.PerspectiveCamera(48,1,.15,9000);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=3;controls.maxDistance=4700;controls.maxPolarAngle=Math.PI*.495;controls.minPolarAngle=.15;
 const pmrem=new T.PMREMGenerator(renderer),envScene=new RoomEnvironment();const env=pmrem.fromScene(envScene,.025);scene.environment=env.texture;scene.environmentIntensity=.24;envScene.dispose();pmrem.dispose();scene.add(new T.HemisphereLight('#eef7f9','#677958',2.1));sun=new T.DirectionalLight('#fff0ce',3.1);sun.castShadow=true;sun.shadow.camera.left=sun.shadow.camera.bottom=-140;sun.shadow.camera.right=sun.shadow.camera.top=140;sun.shadow.camera.near=1;sun.shadow.camera.far=420;sun.shadow.bias=-.0003;sun.shadow.normalBias=.09;scene.add(sun,sun.target);
 m=await makeMaterials(v=>progress(10+v*25,'加载本地PBR石材、铺地与树皮…'));ground=makeGround(data);landscape=makeLandscape(data,m,ground,scene);progress(45,'构造曲面屋顶、石龛与西洋楼立面…');const jets=[];
 for(let i=0;i<data.sites.length;i++){const s=data.sites[i],built=buildSite(s,m),root=built.group,far=new T.Group();for(const child of root.children){if(child.userData.far){const f=child.userData.far;f.position.copy(child.position);f.rotation.copy(child.rotation);far.add(f)}}if(root.userData.far)far.add(root.userData.far);if(!far.children.length)far.add(root.clone());const lod=new T.LOD();lod.addLevel(root,0);lod.addLevel(far,340);lod.position.set(s.position[0],.62,s.position[1]);lod.userData.site=s;scene.add(lod);models.push(lod);for(const o of built.obstacles)obstacles.push({...o,x:o.x+s.position[0],z:o.z+s.position[1]});const large=s.kind==='western'?85:65;plazas.push({x:s.position[0],z:s.position[1],w:large*2,d:large*2});jets.push(...built.jets.map(j=>({...j,a:[j.a[0]+s.position[0],j.a[1]+.62,j.a[2]+s.position[1]],b:[j.b[0]+s.position[0],j.b[1]+.62,j.b[2]+s.position[1]]})));
 const label=document.createElement('span');label.id='label-'+s.id;label.className='world-label';label.textContent=s.name;label.hidden=true;$('labels').append(label);if(i%4===0){progress(45+25*i/data.sites.length,`建立景点：${s.name}`);await new Promise(r=>requestAnimationFrame(r))}}
 progress(75,'实例化植被，建立水岸碰撞与安全定位…');foliage=trees(data,m,ground,obstacles,scene);jetEffect=makeJets(jets,scene);renderList();drawMap();for(const ref of sourceList){let article=document.createElement('article'),a=document.createElement('a'),small=document.createElement('small');a.href=ref.url;a.target='_blank';a.rel='noopener';a.textContent=ref.title+' ↗';small.textContent=`${ref.date} · ${ref.use} · ${ref.confidence}`;article.append(a,small);$('source-links').append(article)}events();setQuality('medium');const dash=data.sites.find(s=>s.name==='大水法');selected=dash;jump(dash);$('info-card').hidden=true;progress(100,'园林已就绪');ready=true;
 window.__ymy={ready,renderer,scene,camera,controls,data,models,ground,obstacles,foliage,validPosition,nearestSafe,jump,home,detail,setMode,setQuality,get mode(){return mode},get stats(){return stats},get quality(){return quality}};
 $('loading').hidden=true;if(matchMedia('(max-width:680px)').matches){$('explorer').classList.add('folded');$('fold-list').textContent='+';$('map-panel').classList.add('folded');$('fold-map').textContent='+';$('fold-map').setAttribute('aria-expanded','false')}last=performance.now();frameId=requestAnimationFrame(animate);
 }catch(e){console.error(e);$('loading-text').textContent=e.message;$('retry').hidden=false;$('retry').onclick=()=>location.reload()}}
function dispose(){cancelAnimationFrame(frameId);clearTimeout(toastTimer);for(const remove of handlers)remove();controls?.dispose();if(scene){const geometries=new Set(),materials=new Set(),textures=new Set();scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const mm of(Array.isArray(o.material)?o.material:o.material?[o.material]:[])){materials.add(mm);for(const v of Object.values(mm))if(v?.isTexture)textures.add(v)}});for(const g of geometries)g.dispose();for(const t of textures)t.dispose();for(const mm of materials)mm.dispose();scene.environment?.dispose()}renderer?.dispose()}
listen(window,'pagehide',dispose);init();
