import * as T from 'three';
let seed=1786;
export const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const mat=(color,roughness=.85,more={})=>new T.MeshStandardMaterial({color,roughness,...more});
function drawn(kind){const c=document.createElement('canvas');c.width=c.height=512;const p=c.getContext('2d');p.fillStyle=kind==='tiles'?'#899087':kind==='paint'?'#264f48':'#b4bba8';p.fillRect(0,0,512,512);
 if(kind==='tiles'){for(let x=0;x<512;x+=32){let g=p.createLinearGradient(x,0,x+32,0);g.addColorStop(0,'#3c4843');g.addColorStop(.42,'#8d968a');g.addColorStop(.8,'#667167');g.addColorStop(1,'#3a4943');p.fillStyle=g;p.fillRect(x,0,32,512)}p.strokeStyle='#30392c99';for(let y=0;y<512;y+=64){p.beginPath();p.moveTo(0,y);p.lineTo(512,y);p.stroke()}}
 if(kind==='paint'){p.strokeStyle='#a49b59';p.lineWidth=3;p.strokeRect(6,6,500,500);for(let y=35;y<500;y+=100){p.beginPath();p.moveTo(12,y);for(let x=12;x<500;x+=3)p.lineTo(x,y+15*Math.sin(x*.04));p.stroke();for(let x=50;x<500;x+=80){p.save();p.translate(x,y+20);p.rotate(Math.PI/4);p.strokeRect(-12,-12,24,24);p.restore()}}}
 for(let i=0;i<7000;i++){p.fillStyle=random()>.5?'#fff7df0a':'#15241a0d';p.fillRect(random()*512,random()*512,1+random()*3,1+random()*2)}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=4;return t;}
export async function makeMaterials(onProgress){const loader=new T.TextureLoader();let loaded=0;const read=async(name,color=false,repeat=1)=>{try{const t=await loader.loadAsync(new URL(`textures/${name}.webp`,window.location.href).href);if(color)t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(repeat,repeat);t.anisotropy=4;onProgress(++loaded/12);return t}catch(e){throw new Error(`材质资源加载失败：textures/${name}.webp。请检查构建是否完整，再重试。`)}};
 const textures=await Promise.all(['bark','paving','rock','forest'].map(async alias=>({map:await read(alias+'-color',true),normalMap:await read(alias+'-normalgl'),roughnessMap:await read(alias+'-roughness')})));
 const p=Object.fromEntries(textures.map((t,i)=>[['bark','paving','rock','forest'][i],t]));const tileMap=drawn('tiles'),paint=drawn('paint');
 const cc=document.createElement('canvas');cc.width=cc.height=768;const ctx=cc.getContext('2d');ctx.drawImage(p.rock.map.image,0,0,768,768);ctx.fillStyle='rgba(238,232,210,.76)';ctx.fillRect(0,0,768,768);const paleStone=new T.CanvasTexture(cc);paleStone.colorSpace=T.SRGBColorSpace;paleStone.wrapS=paleStone.wrapT=T.RepeatWrapping;paleStone.anisotropy=4;p.rock.map.dispose();p.rock.map=paleStone;
 const m={stone:mat('#eee9d8',.9,{...p.rock,normalScale:new T.Vector2(.1,.1)}),limestone:mat('#f1ead4',.82,{...p.rock,normalScale:new T.Vector2(.07,.07)}),pave:mat('#c1bca4',.92,{...p.paving,normalScale:new T.Vector2(.18,.18)}),grass:mat('#b2bb8f',.96,{...p.forest,vertexColors:true,normalScale:new T.Vector2(.15,.15)}),earth:mat('#777a5f',.98),bark:mat('#aeaaa0',.97,{...p.bark,normalScale:new T.Vector2(.7,.7)}),roof:mat('#a0b09d',.9,{map:tileMap}),yellowRoof:mat('#ceb979',.6,{map:tileMap}),wood:mat('#793f32',.8),beam:mat('#335a4f',.85,{map:paint}),gold:mat('#ac945c',.6,{metalness:.22}),wall:mat('#d8d1b9',.95,{map:paleStone}),brick:mat('#696e66',.96),window:mat('#31453f',.78),glass:mat('#426467',.32,{metalness:.08}),bronze:mat('#576453',.6,{metalness:.45}),leaf:mat('#566d38',.9,{side:T.DoubleSide}),pond:new T.MeshPhysicalMaterial({color:'#668c79',roughness:.32,metalness:.18,clearcoat:.5})};for(const t of Object.values(p)){for(const k of ['map','normalMap','roughnessMap'])t[k].repeat.set(1,1)}m.allTextures=[...textures.flatMap(x=>[x.map,x.normalMap,x.roughnessMap]),tileMap,paint];return m;
}

