import {chromium} from 'playwright';
import fs from 'node:fs';
import os from 'node:os';
const base=process.env.TEST_URL||'http://127.0.0.1:5186/',errors=[],requests=[],failures=[],checks=[];
fs.mkdirSync('evidence',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'C:/Users/YUE/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe',args:['--enable-webgl','--ignore-gpu-blocklist']});
const context=await browser.newContext({viewport:{width:1440,height:960},deviceScaleFactor:1,acceptDownloads:true}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>requests.push({url:r.url(),error:r.failure()?.errorText}));
const report={testDateLocal:'2026-10-07 Asia/Shanghai',timestampUTC:new Date().toISOString(),base,browser:await browser.version(),device:{os:os.type()+' '+os.release(),cpu:os.cpus()[0]?.model,logicalCpuCount:os.cpus().length,ramGB:+(os.totalmem()/2**30).toFixed(1)},viewport:{width:1440,height:960,dpr:1},mode:'Local Windows desktop, headless Chromium, hardware WebGL. Mobile emulation is not a real phone.',errors,requests,failures,checks,performance:[]};
const assert=(value,message)=>{if(!value)failures.push(message);};
const settle=async()=>{await page.waitForFunction(()=>!window.__pingtan.nav.transitioning);await page.waitForTimeout(850);};
async function perf(label){return page.evaluate(async label=>{const intervals=[];let last=performance.now(),start=last;await new Promise(resolve=>{function frame(now){intervals.push(now-last);last=now;if(now-start<3500)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});intervals.shift();intervals.sort((a,b)=>a-b);const mean=intervals.reduce((a,b)=>a+b,0)/intervals.length,s=window.__pingtan;return {label,quality:s.quality(),sampleSeconds:3.5,sampleFrames:intervals.length,meanFrameMs:+mean.toFixed(2),observedRafFps:+(1000/mean).toFixed(1),p95FrameMs:+intervals[Math.floor(intervals.length*.95)].toFixed(2),drawCalls:s.renderer.info.render.calls,triangles:s.renderer.info.render.triangles,geometries:s.renderer.info.memory.geometries,textures:s.renderer.info.memory.textures,pixelRatio:s.renderer.getPixelRatio()};},label);}
try{
 const start=Date.now();await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__pingtan?.ready,null,{timeout:90000});report.firstReadyMs=Date.now()-start;
 report.scene=await page.evaluate(()=>{const s=window.__pingtan,g=s.renderer.getContext(),ext=g.getExtension('WEBGL_debug_renderer_info');return {gpu:ext?g.getParameter(ext.UNMASKED_RENDERER_WEBGL):g.getParameter(g.RENDERER),terrainTiles:s.ground.tiles.length,sourceCoastVertices:s.data.geo.coastlines[s.data.geo.mainIsland].length,buildings:s.data.geo.buildings.length,renderedRoads:s.features.roadCount,vegetationInstances:s.vegetation.count,turbines:s.turbines.specs.length,places:s.nav.places.map(p=>({id:p.id,lonLat:p.lonLat,source:p.source})),projection:s.data.geo.metadata.projection,peak:s.ui.peak};});
 await page.waitForTimeout(1500);await page.screenshot({path:'evidence/overview.png'});report.performance.push(await perf('全岛鸟瞰'));checks.push('Real-data initial scene and overview');console.log('Overview checked',report.scene.gpu);
 await page.locator('#sources-open').click();assert(await page.locator('#sources-dialog').isVisible(),'sources dialog');await page.screenshot({path:'evidence/data-disclosure.png'});await page.locator('#sources-dialog .dialog-close').click();await page.locator('#help-open').click();assert(await page.locator('#help-dialog').isVisible(),'help dialog');await page.keyboard.press('Escape');assert(!(await page.locator('#help-dialog').isVisible()),'Esc close');checks.push('Data categories, source links, help and keyboard dialog close');
 const before=await page.evaluate(()=>window.__pingtan.camera.position.toArray());await page.mouse.move(900,350);await page.mouse.down();await page.mouse.move(990,385,{steps:10});await page.mouse.up();await page.waitForTimeout(400);assert((await page.evaluate(()=>window.__pingtan.camera.position.toArray())).some((v,i)=>Math.abs(v-before[i])>1),'orbit drag');const dist=await page.evaluate(()=>window.__pingtan.camera.position.distanceTo(window.__pingtan.nav.orbit.target));await page.mouse.wheel(0,-180);await page.waitForTimeout(400);assert((await page.evaluate(()=>window.__pingtan.camera.position.distanceTo(window.__pingtan.nav.orbit.target)))<dist,'wheel zoom');checks.push('Mouse orbit / wheel');
 report.cameraClearance=[];
 for(const id of report.scene.places.map(p=>p.id)){await page.locator(`[data-place="${id}"]`).click();await settle();assert(await page.evaluate(id=>window.__pingtan.nav.selected?.id===id,id),'landmark '+id);await page.screenshot({path:`evidence/${id}.png`});report.cameraClearance.push(await page.evaluate(()=>{const s=window.__pingtan,p=s.camera.position;return {place:s.nav.selected.id,clearance:p.y-s.ground.collisionHeight(p.x,p.z)};}));}
 report.coasts=await page.evaluate(()=>{const s=window.__pingtan;return {beaches:s.coasts.counts.beaches,rocks:s.coasts.counts.rocks,sea:s.turbines.offshoreCount,land:s.turbines.onshoreCount,changjiangRetained:s.data.geo.areas.some(a=>a.id==='w990631702'),train:{length:s.train.route.total,stops:s.train.stations.length,vehicles:s.train.cars.length,classification:s.train.route.classification}};});
 assert(report.coasts.changjiangRetained&&report.coasts.beaches===52,'mapped beach coverage');assert(report.coasts.sea===81&&report.coasts.land===99,'sea/land turbines separately rendered');assert(Math.abs(report.coasts.train.length-800)<.01&&report.coasts.train.stops===3&&report.coasts.train.vehicles===1,'photo-reference double-deck train');
 await page.locator('[data-place="longwang"]').click();await settle();await page.locator('#train-close').click();await settle();await page.screenshot({path:'evidence/train-close.png'});const trainBefore=await page.evaluate(()=>window.__pingtan.train.travelled);await page.waitForTimeout(800);assert(Math.abs((await page.evaluate(()=>window.__pingtan.train.travelled))-trainBefore)>1,'train animation');report.performance.push(await perf('龙王头观光车近景'));checks.push('52 mapped beaches; 81 offshore / 99 onshore; photo-reference double-deck train and illustrative 800m route');
 checks.push('All 15 destinations, source/approximate classifications and smooth transitions');
 report.landscapes=await page.evaluate(()=>{const s=window.__pingtan,well=s.data.landmarks.places.find(p=>p.id==='xianren');let invalid=0;for(const {group} of s.landmarks.groups)group.traverse(o=>{if(o.isMesh)for(const v of o.geometry.attributes.position.array)if(!Number.isFinite(v))invalid++;});return {inventoryEntries:s.data.landmarks.inventory.length,destinations:s.nav.places.length,invalidVertices:invalid,wellDepth:s.landmarks.well.top-s.landmarks.well.bottom,wellBottom:s.ground.collisionHeight(well.x,well.z),originalDemAtWell:s.ground.sourceHeight(well.x,well.z),regionGroups:document.querySelectorAll('.region-heading').length};});
 assert(report.landscapes.invalidVertices===0&&report.landscapes.inventoryEntries===19&&report.landscapes.destinations===15,'comprehensive landscape coverage and finite geometry');assert(Math.abs(report.landscapes.wellDepth-43)<.001&&report.landscapes.wellBottom<1,'metre-scale well and visual-floor collision');
 await page.locator('#place-search').fill('镜沙');assert(await page.locator('#place-list [data-place]:visible').count()===1,'landmark search');await page.locator('#place-search').fill('');await page.locator('#landscape-open').click();assert(await page.locator('#landscape-inventory li').count()===19,'inventory disclosure');await page.keyboard.press('Escape');
 for(const id of ['jingsha','xianren']){await page.locator(`[data-place="${id}"]`).click();await settle();await page.locator('#close-view').click();await settle();if(id==='jingsha')assert(await page.evaluate(()=>{const s=window.__pingtan;return s.camera.position.y<s.landmarks.cave.base+6.5;}),'cave close camera inside the cavity, below ceiling');await page.screenshot({path:`evidence/${id}-close.png`});report.performance.push(await perf(id==='jingsha'?'镜沙洞口近景':'仙人井近景'));}
 checks.push('Landscape search, 19-entry disclosure, metre-scale 43m well, close-view cameras, finite landmark meshes');
 await page.locator('[data-place="beigang"]').click();await settle();await page.locator('#stone-close').click();await settle();await page.locator('#quality').selectOption('high');await page.waitForTimeout(1600);await page.screenshot({path:'evidence/stone-close.png'});report.performance.push(await perf('北港石厝近景'));checks.push('Photo-reference sample, detailed roof, PBR surfaces, high quality');
 const solarBefore=await page.evaluate(()=>window.__pingtan.lighting.sun.position.toArray());await page.locator('#time').fill('8');await page.locator('#time').dispatchEvent('input');await page.waitForTimeout(350);assert((await page.evaluate(()=>window.__pingtan.lighting.sun.position.toArray())).some((v,i)=>Math.abs(v-solarBefore[i])>10),'sun slider');await page.screenshot({path:'evidence/morning.png'});await page.locator('#time').fill('14');await page.locator('#time').dispatchEvent('input');checks.push('Local-date time and solar direction');
 await page.locator('.toggle').click();assert(await page.locator('#labels').isHidden(),'labels hidden');await page.locator('.toggle').click();
 await page.locator('#fly').click();const p0=await page.evaluate(()=>window.__pingtan.camera.position.toArray());await page.locator('#viewport canvas').click({position:{x:850,y:520}});await page.keyboard.down('KeyW');await page.waitForTimeout(1000);await page.keyboard.up('KeyW');const p1=await page.evaluate(()=>window.__pingtan.camera.position.toArray());assert(Math.hypot(...p1.map((v,i)=>v-p0[i]))>1,'W movement');await page.keyboard.down('KeyQ');await page.waitForTimeout(700);await page.keyboard.up('KeyQ');
 report.flight=await page.evaluate(()=>{const s=window.__pingtan,p=s.camera.position;s.nav.safe(p.set(p.x,-30,p.z));return {mode:s.nav.mode,minimumClearance:p.y-s.ground.collisionHeight(p.x,p.z)};});assert(report.flight.minimumClearance>=2.49,'anti-ground collision');await page.screenshot({path:'evidence/flight.png'});await page.keyboard.press('KeyH');await settle();checks.push('Free flight, WASD, Q/E, H reset and minimum 2.5m terrain clearance');
 const mp=await page.evaluate(()=>window.__pingtan.ui.mapPoint(window.__pingtan.nav.places[0].x,window.__pingtan.nav.places[0].z)),r=await page.locator('#minimap').boundingBox();await page.mouse.click(r.x+mp[0]/320*r.width,r.y+mp[1]/380*r.height);await settle();assert(await page.evaluate(()=>window.__pingtan.nav.selected?.id==='beigang'),'map click');checks.push('Minimap landmark positioning');
 for(const q of ['low','medium','high']){await page.locator('#quality').selectOption(q);await page.waitForTimeout(1600);assert(await page.evaluate(q=>window.__pingtan.quality()===q,q),'quality '+q);report.performance.push(await perf('北港区域 / '+q));}
 const downloadPromise=page.waitForEvent('download');await page.locator('#screenshot').click();const download=await downloadPromise;await download.saveAs('evidence/export-scene.png');assert(fs.statSync('evidence/export-scene.png').size>1000,'scene export');checks.push('PNG export');
 console.log('Desktop interaction and quality checks completed');
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true}),phone=await mobileContext.newPage();await phone.goto(base,{waitUntil:'networkidle'});await phone.waitForFunction(()=>window.__pingtan?.ready,null,{timeout:90000});await phone.waitForTimeout(1000);
 report.mobile={kind:'Chromium touch/DPR emulation, same RTX4070, NOT physical phone',viewport:{width:390,height:844,dpr:2},defaultQuality:await phone.evaluate(()=>window.__pingtan.quality()),drawingPixelRatio:await phone.evaluate(()=>window.__pingtan.renderer.getPixelRatio())};assert(report.mobile.defaultQuality==='low','mobile low default');
 if(await phone.locator('#places-toggle').getAttribute('aria-expanded')==='true')await phone.locator('#places-toggle').tap();await phone.locator('#map-toggle').tap();await phone.screenshot({path:'evidence/mobile.png'});const mobileDistance=await phone.evaluate(()=>window.__pingtan.camera.position.distanceTo(window.__pingtan.nav.orbit.target));const cdp=await mobileContext.newCDPSession(phone);await cdp.send('Input.synthesizePinchGesture',{x:235,y:420,scaleFactor:1.3,relativeSpeed:600,gestureSourceType:'touch'});await phone.waitForTimeout(400);report.mobile.pinchChanged=Math.abs((await phone.evaluate(()=>window.__pingtan.camera.position.distanceTo(window.__pingtan.nav.orbit.target)))-mobileDistance)>1;assert(report.mobile.pinchChanged,'mobile pinch');
 await phone.locator('#places-toggle').tap();await phone.locator('[data-place="beigang"]').tap();await phone.waitForFunction(()=>!window.__pingtan.nav.transitioning);await phone.locator('#fly').tap();assert(await phone.locator('#touch-flight').isVisible(),'touch flight controls');const pm0=await phone.evaluate(()=>window.__pingtan.camera.position.toArray());const bt=await phone.locator('[data-move="forward"]').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bt.x+bt.width/2,y:bt.y+bt.height/2}]});await phone.waitForTimeout(600);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const pm1=await phone.evaluate(()=>window.__pingtan.camera.position.toArray());report.mobile.touchFlightChanged=Math.hypot(...pm1.map((v,i)=>v-pm0[i]))>1;assert(report.mobile.touchFlightChanged,'touch forward');checks.push('390×844 touch emulation, low profile, pinch, tap destination, touch flight');await mobileContext.close();
 // Deliberately missing critical data: readable error, not white screen.
 const failed=await context.newPage();await failed.route('**/data/terrain.json',route=>route.fulfill({status:404,body:'missing'}));await failed.goto(base);await failed.waitForSelector('#error-banner:not([hidden])');assert((await failed.locator('#error-message').textContent()).includes('terrain.json'),'critical failure names file');await failed.screenshot({path:'evidence/resource-failure.png'});await failed.close();
 const fallback=await context.newPage();await fallback.route('**/data/satellite-2016.webp',route=>route.fulfill({status:404,body:'missing'}));await fallback.goto(base);await fallback.waitForFunction(()=>window.__pingtan?.ready,null,{timeout:90000});assert(await fallback.locator('#error-banner').isVisible(),'imagery failure warns');assert(await fallback.evaluate(()=>!window.__pingtan.ground.material.map),'real terrain fallback');await fallback.close();checks.push('Required data failure names missing resource; optional imagery failure retains real geometry');
 assert(errors.length===0,'no normal-run console/page errors');assert(requests.length===0,'no normal-run request failures');assert(report.cameraClearance.every(c=>c.clearance>=2.5),'all presets above terrain');
}catch(e){failures.push(e.stack||e.message);}finally{fs.writeFileSync('evidence/test-results.json',JSON.stringify(report,null,2));await browser.close();}
console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
