"""Package the built scene and its corresponding source; exclude research-only photos."""
from pathlib import Path
import shutil, zipfile, json, sys
B=Path(__file__).resolve().parents[1]
T=B.parent/'tours/china/fujian/pingtan'
assert T.resolve().is_relative_to(B.parent.resolve()) and T.name=='pingtan'
if T.exists() and not (T/'PROJECT.txt').exists():
    raise RuntimeError('Existing target has no project marker; refusing to overwrite it.')
T.mkdir(parents=True,exist_ok=True)
(T/'PROJECT.txt').write_text('Pingtan geographic scene: generated by pingtan/scripts/package-static.py\n',encoding='utf-8')
shutil.copytree(B/'dist',T,dirs_exist_ok=True)
shutil.copy2(B/'scripts/static-server.mjs',T/'serve.mjs')
shutil.copy2(B/'public/docs/CODE-LICENSE.txt',T/'LICENSE')
S=T/'source';S.mkdir(exist_ok=True)
for name in ['index.html','package.json','package-lock.json','vite.config.js','README.md','.gitignore']:
    shutil.copy2(B/name,S/name)
for name in ['src','scripts','public','docs']:
    shutil.copytree(B/name,S/name,dirs_exist_ok=True)
shutil.copy2(B/'public/docs/CODE-LICENSE.txt',S/'LICENSE')
# Research-only government photos are deliberately absent.
R=S/'research';R.mkdir(exist_ok=True)
for name in ['north.osm','south.osm','northwest.osm','N25E119.hgt.gz','satellite-2016.jpg','eox-capabilities.xml','checksums.json','processing-results.json','query.overpass']:
    shutil.copy2(B/'research'/name,R/name)
for doc in [S/'docs/ACCEPTANCE.md',S/'public/docs/ACCEPTANCE.md']:
    doc.write_text(doc.read_text(encoding='utf-8').replace('../evidence/','../../evidence/'),encoding='utf-8')
E=T/'evidence';E.mkdir(exist_ok=True)
for p in (B/'evidence').iterdir():
    if p.is_file() and p.suffix in ['.png','.json'] and p.name!='photo-comparison-local.png':
        shutil.copy2(p,E/p.name)
(T/'START-HERE.md').write_text('''# 平潭三维地理场景\n\n在本目录运行 `node serve.mjs . 5187`，打开 http://127.0.0.1:5187/ 。只需 Node.js，无需 npm 安装或外网。也可用任何静态 HTTP 服务；不支持直接双击 file:// 入口。\n\n`index.html`、assets/data/textures 为完整运行资源。对应源代码、锁定依赖与原始许可数据在 source/：在 source/ 运行 `npm ci`、`npm run dev` 或 `npm run build`。\n\n验收与截图见 docs/ACCEPTANCE.md 和 evidence/；来源见 docs/SOURCES.md，精度与缺失见 docs/ACCURACY.md。统一景观覆盖、15处定位和19项状态见 docs/LANDSCAPES.md。版权参考照片未分发。\n\n采用真实 OSM 岸线、公开高程和 2016 卫星影像，1 单位=1 米；北港只有两处映射轮廓上的近似石厝，镜沙、仙人井等地貌为来源明确的参考近似，部分景观资料缺失。不是完整摄影测量实景模型。\n''',encoding='utf-8')
if '--copy-only' in sys.argv:
    print(json.dumps({'staticEntry':str(T/'index.html'),'copied':True},ensure_ascii=False));sys.exit(0)
archive=B/'pingtan-static.zip'
# Include the current build/source manifest. Historical generated files left in
# the preview directory are not silently added to this delivery archive.
manifest={T/p.relative_to(B/'dist') for p in (B/'dist').rglob('*') if p.is_file()}
manifest.update(T/n for n in ['PROJECT.txt','START-HERE.md','serve.mjs','LICENSE'])
for name in ['index.html','package.json','package-lock.json','vite.config.js','README.md','.gitignore','LICENSE']:
    manifest.add(S/name)
for name in ['src','scripts','public','docs']:
    manifest.update(S/name/p.relative_to(B/name) for p in (B/name).rglob('*') if p.is_file())
manifest.update(R/p.name for p in R.iterdir() if p.name in ['north.osm','south.osm','northwest.osm','N25E119.hgt.gz','satellite-2016.jpg','eox-capabilities.xml','checksums.json','processing-results.json','query.overpass'])
manifest.update(E/p.name for p in (B/'evidence').iterdir() if p.is_file() and p.suffix in ['.png','.json'] and p.name!='photo-comparison-local.png')
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
    for p in sorted(manifest):z.write(p,p.relative_to(T).as_posix())
with zipfile.ZipFile(archive) as z:
    names=z.namelist()
    assert 'index.html' in names and 'source/src/main.js' in names and 'data/geography.json' in names
    assert not any('beigang-' in n or 'photo-comparison-local' in n for n in names)
print(json.dumps({'staticEntry':str(T/'index.html'),'archive':str(archive),'zipBytes':archive.stat().st_size,'entries':len(names),'copyrightPhotosIncluded':False},ensure_ascii=False,indent=2))
