import * as T from 'three';
import {TessellateModifier} from 'three/addons/modifiers/TessellateModifier.js';
import {Builder} from './geometry.js';
import {random} from './materials.js';
export const inside=(p,r)=>{let c=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])c=!c}return c};
export function segmentDistance(x,z,a,b){const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz||1)));return {distance:Math.hypot(x-a[0]-dx*t,z-a[1]-dz*t),point:[a[0]+dx*t,a[1]+dz*t],t}}
export function makeGround(data){const waters=data.water.map(w=>({...w,box:[Math.min(...w.outer.map(p=>p[0])),Math.min(...w.outer.map(p=>p[1])),Math.max(...w.outer.map(p=>p[0])),Math.max(...w.outer.map(p=>p[1]))]}));
 function wet(x,z){return waters.some(w=>x>w.box[0]&&x<w.box[2]&&z>w.box[1]&&z<w.box[3]&&inside([x,z],w.outer)&&!w.holes.some(r=>inside([x,z],r)))}
 const hills=[[-800,-100,7,100],[-320,-680,6,70],[315,-30,6,60],[-190,160,5,75],[-600,-180,5,65],[400,-230,5,60],[-120,-500,4,80]];
 const segments=data.paths.flatMap(p=>p.points.slice(1).map((b,i)=>({a:p.points[i],b,width:p.width,bridge:p.bridge})));
 function routeDistance(x,z){let near={distance:Infinity,point:[x,z]};for(const s of segments){const boxPadding=7;if(x<Math.min(s.a[0],s.b[0])-boxPadding||x>Math.max(s.a[0],s.b[0])+boxPadding||z<Math.min(s.a[1],s.b[1])-boxPadding||z>Math.max(s.a[1],s.b[1])+boxPadding)continue;const r=segmentDistance(x,z,s.a,s.b);if(r.distance<near.distance)near={...r,segment:s}}return near}
 function base(x,z){let h=.62;for(const [a,b,height,r]of hills)h+=height*Math.exp(-((x-a)**2+(z-b)**2)/(r*r));h+=.1*Math.sin(x*.016)*Math.sin(z*.011);return h}
 const bridgeSegments=segments.filter(s=>s.bridge);function bridgeAt(x,z){return bridgeSegments.some(s=>segmentDistance(x,z,s.a,s.b).distance<1.7)}
 function height(x,z){if(bridgeAt(x,z))return .66;if(wet(x,z))return -1.6;let h=base(x,z);for(const s of data.sites){let dx=Math.abs(x-s.position[0]),dz=Math.abs(z-s.position[1]);const radius=s.kind==='western'?70:60;if(dx<radius&&dz<radius){let fade=Math.max(dx,dz)/radius;h=.62+(h-.62)*Math.min(1,Math.max(0,(fade-.65)/.35));}}return h}
 return {wet,height,base,waters,segments,routeDistance,bridgeAt};
}
function waterShape(w){const s=new T.Shape(w.outer.map(p=>new T.Vector2(p[0],-p[1])));for(const h of w.holes)s.holes.push(new T.Path(h.map(p=>new T.Vector2(p[0],-p[1]))));return s}
export function makeLandscape(data,m,ground,scene){const landShape=new T.Shape([new T.Vector2(-1900,-1500),new T.Vector2(1900,-1500),new T.Vector2(1900,1500),new T.Vector2(-1900,1500)]);for(const w of data.water)landShape.holes.push(new T.Path(w.outer.map(p=>new T.Vector2(p[0],-p[1]))));const shapes=[landShape,...data.water.flatMap(w=>w.holes.map(h=>new T.Shape(h.map(p=>new T.Vector2(p[0],-p[1])))))];let raw=new T.ShapeGeometry(shapes,8);raw.rotateX(-Math.PI/2);let terrain=new TessellateModifier(25,7).modify(raw);raw.dispose();const pos=terrain.attributes.position,colors=[];for(let i=0;i<pos.count;i++){let x=pos.getX(i),z=pos.getZ(i),y=ground.height(x,z);if(y<0)y=.62;pos.setY(i,y);let color=new T.Color();const r=random();color.setRGB(.72+r*.035,.76+r*.035,.59+r*.025);colors.push(color.r,color.g,color.b);terrain.attributes.uv.setXY(i,x/7,z/7)}terrain.setAttribute('color',new T.Float32BufferAttribute(colors,3));terrain.computeVertexNormals();let mesh=new T.Mesh(terrain,m.grass);mesh.receiveShadow=true;scene.add(mesh);
 const waterM=new T.MeshPhysicalMaterial({color:'#688b80',roughness:.34,metalness:.16,clearcoat:.42,clearcoatRoughness:.35,side:T.DoubleSide});const clockUniform={value:0};waterM.onBeforeCompile=shader=>{shader.uniforms.uTime=clockUniform;shader.vertexShader='uniform float uTime;\n'+shader.vertexShader.replace('#include <beginnormal_vertex>','#include <beginnormal_vertex>\nobjectNormal.x+=sin(position.x*.12+uTime*.3)*.055;objectNormal.z+=cos(position.z*.15+uTime*.27)*.055;')};
 const bank=new Builder(m);for(const w of data.water){let g=new T.ShapeGeometry(waterShape(w),12);g.rotateX(-Math.PI/2);const lake=new T.Mesh(g,waterM);lake.position.y=.015;scene.add(lake);for(const r of [w.outer,...w.holes]){const vs=[],uv=[],idx=[];for(let i=0;i<r.length;i++){const p=r[i],prev=r[(i+r.length-1)%r.length],next=r[(i+1)%r.length],dx=next[0]-prev[0],dz=next[1]-prev[1],len=Math.hypot(dx,dz)||1;vs.push(p[0],.03,p[1],p[0]-dz/len*.8,.65,p[1]+dx/len*.8);uv.push(i/2,0,i/2,1);if(i<r.length-1)idx.push(i*2,i*2+1,i*2+2,i*2+1,i*2+3,i*2+2)}let sg=new T.BufferGeometry();sg.setAttribute('position',new T.Float32BufferAttribute(vs,3));sg.setAttribute('uv',new T.Float32BufferAttribute(uv,2));sg.setIndex(idx);sg.computeVertexNormals();bank.add('earth',sg)}}scene.add(bank.finish());
 // Footpaths are clearly marked as virtual navigation, following map paths only as aids.
 let roadBuilder=new Builder(m);for(const p of data.paths){for(let i=1;i<p.points.length;i++){const a=p.points[i-1],b=p.points[i],len=Math.hypot(b[0]-a[0],b[1]-a[1]);if(len>150||len<.2)continue;let mid=[(a[0]+b[0])/2,(a[1]+b[1])/2];if(ground.wet(...mid)&&!p.bridge)continue;const yaw=Math.atan2(b[0]-a[0],b[1]-a[1]);roadBuilder.box(p.bridge?'bronze':'pave',p.width,p.bridge?.14:.055,len+.3,mid[0],p.bridge?.59:ground.height(...mid)+.03,mid[1],yaw)}}scene.add(roadBuilder.finish());
 const westernWall=new Builder(m);westernWall.box('wall',400,2.6,.7,500,1.9,-738);westernWall.box('wall',380,2.6,.7,960,1.9,-738);westernWall.box('wall',85,2.6,.7,736,1.9,-780);westernWall.box('wall',.7,2.6,42,693,1.9,-759);westernWall.box('wall',.7,2.6,42,779,1.9,-759);westernWall.box('brick',400,.18,.9,500,3.25,-738);westernWall.box('brick',380,.18,.9,960,3.25,-738);scene.add(westernWall.finish());
 return {waterM,clockUniform,terrain};
}
function leafTexture(){const c=document.createElement('canvas');c.width=c.height=512;const p=c.getContext('2d');p.clearRect(0,0,512,512);for(let i=0;i<2300;i++){let x=256+(random()-.5)*452,y=256+(random()-.5)*452;const len=Math.hypot(x-256,y-256);if(len>220)continue;p.save();p.translate(x,y);p.rotate(random()*Math.PI);p.fillStyle=['#c1c7a7','#a1ae84','#737f5c','#83956d','#a6b191'][i%5];p.beginPath();p.ellipse(0,0,random()*2.5+1.5,random()*4+2,0,0,Math.PI*2);p.fill();p.restore()}let t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
export function trees(data,m,ground,obstacles,scene){const points=[];let tries=0;while(points.length<2700&&tries++<28000){let x=-1300+random()*2550,z=-840+random()*1870;if(!inside([x,z],data.boundary)||ground.wet(x,z)||ground.routeDistance(x,z).distance<7)continue;if(data.sites.some(s=>Math.hypot(x-s.position[0],z-s.position[1])<(s.kind==='western'?39:40)))continue;if(z>180&&x>20&&x<850&&random()>.25)continue;points.push([x,ground.height(x,z),z])}
 for(let x=300;x<1230;x+=18){if(x>680&&x<810)continue;points.push([x,.62,-751])}
 for(let i=points.length-1;i>=0;i--){if(data.sites.some(s=>{const d=s.kind==='western'?76:125;return Math.hypot(points[i][0]-s.position[0]-d*.6,points[i][2]-s.position[1]-d)<15}))points.splice(i,1)}
 const texture=leafTexture(),foliage=new T.MeshStandardMaterial({map:texture,alphaTest:.4,side:T.DoubleSide,roughness:.98,depthWrite:true,color:'#b2bd8e'});let geo=new T.BufferGeometry();const v=[],uv=[],ind=[];for(let i=0;i<38;i++){const yaw=random()*Math.PI*2,pitch=(random()-.5)*1.4,cx=(random()-.5)*5,cy=4+random()*4,cz=(random()-.5)*5,w=2.7+random()*1.9;const q=new T.Quaternion().setFromEuler(new T.Euler(pitch,yaw,0));for(const [x,y,u,vv]of [[-w/2,-w/2,0,0],[w/2,-w/2,1,0],[w/2,w/2,1,1],[-w/2,w/2,0,1]]){let p=new T.Vector3(x,y,0).applyQuaternion(q);v.push(p.x+cx,p.y+cy,p.z+cz);uv.push(u,vv)}let a=i*4;ind.push(a,a+1,a+2,a,a+2,a+3)}geo.setAttribute('position',new T.Float32BufferAttribute(v,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setIndex(ind);geo.computeVertexNormals();const canopies=new T.InstancedMesh(geo,foliage,points.length),trunks=new T.InstancedMesh(new T.CylinderGeometry(.15,.3,5.5,6).translate(0,2.75,0),m.bark,points.length),dummy=new T.Object3D();for(let i=0;i<points.length;i++){dummy.position.set(...points[i]);dummy.scale.setScalar(.85+random()*.9);dummy.rotation.y=random()*Math.PI*2;dummy.updateMatrix();canopies.setMatrixAt(i,dummy.matrix);trunks.setMatrixAt(i,dummy.matrix);canopies.setColorAt(i,new T.Color().setHSL(.16+random()*.04,.22+random()*.17,.62+random()*.12))}canopies.castShadow=true;canopies.receiveShadow=true;trunks.castShadow=true;const cloudGeo=new T.SphereGeometry(1,14,10).scale(3.6,3.2,3.6).translate(0,6,0),farCanopies=new T.InstancedMesh(cloudGeo,new T.MeshStandardMaterial({color:'#738459',roughness:1}),points.length);for(let i=0;i<points.length;i++){const mx=new T.Matrix4();canopies.getMatrixAt(i,mx);farCanopies.setMatrixAt(i,mx);}farCanopies.visible=false;scene.add(canopies,trunks,farCanopies);return {canopies,trunks,farCanopies,total:points.length,texture};}
export function makeJets(specs,scene){if(!specs.length)return null;let v=[],times=[];for(const s of specs){for(let i=0;i<60;i++){const t=i/59;v.push(s.a[0]+(s.b[0]-s.a[0])*t,s.a[1]+(s.b[1]-s.a[1])*t+Math.sin(t*Math.PI)*s.h,s.a[2]+(s.b[2]-s.a[2])*t);times.push(t)}}let g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('phase',new T.Float32BufferAttribute(times,1));let mat=new T.ShaderMaterial({uniforms:{time:{value:0}},vertexShader:'uniform float time; attribute float phase; varying float a; void main(){a=.3+.7*sin(phase*60.-time*12.);vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=clamp(120./-p.z,1.,3.);}',fragmentShader:'varying float a;void main(){if(length(gl_PointCoord-.5)>.5)discard;gl_FragColor=vec4(.88,.92,.85,a*.64);}',transparent:true,depthWrite:false});let mesh=new T.Points(g,mat);scene.add(mesh);return {mesh,mat};}

