import * as THREE from 'three';
export const $=id=>document.getElementById(id);
export function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
export class UI {
 constructor(data,building,nav,camera,renderer){this.data=data;this.building=building;this.nav=nav;this.camera=camera;this.renderer=renderer;this.labels=true;this.labelNodes=[];this.selected=null;
 const selected=['wumen','taihemen','taihe','zhonghe','baohe','qianqing','kunning','qinan','shenwu','wenhua','wuying','huangji','yangxin','jingren','jingyang','chuxiu','xianfu'];
 for(const id of selected){const b=building.models.find(b=>b.id===id);if(!b)continue;const btn=document.createElement('button');btn.dataset.landmark=id;btn.innerHTML=`${b.name}<small>↗</small>`;btn.addEventListener('click',()=>{nav.locate(b);this.showInfo(b);});$('landmarks').append(btn);}
 for(const b of building.models){const el=document.createElement('button');el.className='label';el.textContent=b.name;el.addEventListener('click',()=>this.showInfo(b));$('viewport').append(el);this.labelNodes.push({b,el});}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);for(const p of building.picks)p.updateMatrixWorld();const hit=ray.intersectObjects(building.picks)[0];if(hit)this.showInfo(hit.object.userData.model);});
 $('labels').onclick=()=>{this.labels=!this.labels;$('labels').setAttribute('aria-pressed',this.labels);};$('orbit').onclick=()=>this.mode('orbit');$('walk').onclick=()=>this.mode('walk');$('home').onclick=()=>{nav.home();this.mode('orbit');};$('about').onclick=()=> $('sources').showModal();$('close-sources').onclick=()=> $('sources').close();$('sources').addEventListener('click',e=>{if(e.target===$('sources'))$('sources').close();});
 }
 mode(mode){this.nav.setMode(mode);$('orbit').classList.toggle('active',mode==='orbit');$('walk').classList.toggle('active',mode==='walk');$('crosshair').classList.toggle('hidden',mode!=='walk');$('hint').textContent=mode==='walk'?'WASD / ↑↓ 移动 · 拖动观察 · 双击锁定 · Shift 快走 · Esc 释放':'拖动旋转 · 滚轮缩放 · 右键平移';}
 showInfo(b){this.selected=b;$('info').classList.remove('hidden');$('info').innerHTML=`<button class="close" aria-label="关闭">×</button><p class="eyebrow">建筑资料 / ${b.id}</p><h2>${b.name}</h2><span class="badge">${b.status||'地图估算'}</span><p>${b.description||'尚未完成形制核对。'}</p><p class="fine">模型主体：${(b.w||0).toFixed(2)} × ${(b.d||0).toFixed(2)} 米<br>主体高度 ${(b.h||0).toFixed(2)} 米 · 台基 ${(b.base||0).toFixed(2)} 米<br>位置：x ${b.x.toFixed(2)} / z ${b.z.toFixed(2)}（地图估算）<br>室内未开放</p><a href="${b.sourceURL||`https://www.dpm.org.cn/explore/building/${b.sourceId}.html`}" target="_blank" rel="noopener">故宫博物院建筑资料 ↗</a><p class="fine"><a href="${b.footprintSource||b.source||'https://www.dpm.org.cn/Explore.html'}" target="_blank" rel="noopener">位置轮廓资料 ↗</a></p>`;$('info').querySelector('button').onclick=()=> $('info').classList.add('hidden');}
 update(){const width=innerWidth,height=innerHeight;for(const {b,el} of this.labelNodes){const p=new THREE.Vector3(b.x,(b.base||0)+(b.h||20)+4,b.z).project(this.camera);const distance=this.camera.position.distanceTo(new THREE.Vector3(b.x,0,b.z));const show=this.labels&&p.z<1&&p.z>-1&&Math.abs(p.x)<.94&&Math.abs(p.y)<.94&&(this.nav.mode==='orbit'||distance<170);el.style.display=show?'block':'none';if(show){el.style.left=`${(p.x*.5+.5)*width}px`;el.style.top=`${(-p.y*.5+.5)*height}px`;}}
 this.map();}
 map(){const canvas=$('map'),ctx=canvas.getContext('2d'),s=.255,ox=120,oz=150;const map=([x,z])=>[ox+x*s,oz+z*s];ctx.clearRect(0,0,240,300);ctx.fillStyle='#e9ebdf';ctx.fillRect(0,0,240,300);ctx.strokeStyle='#bcc6b5';ctx.lineWidth=1;ctx.strokeRect(ox-376.5*s,oz-480.5*s,753*s,961*s);
 ctx.fillStyle='#b4b39d';for(const b of this.data.buildings){ctx.beginPath();b.points.forEach((p,i)=>{const [x,z]=map(p);i?ctx.lineTo(x,z):ctx.moveTo(x,z);});ctx.fill('evenodd');}
 ctx.strokeStyle='#7a9d99';ctx.lineWidth=1.5;for(const w of this.data.water){if(w.name==='筒子河')continue;ctx.beginPath();w.points.forEach((p,i)=>{const [x,z]=map(p);i?ctx.lineTo(x,z):ctx.moveTo(x,z);});ctx.stroke();}
 ctx.setLineDash([3,3]);ctx.strokeStyle='#8f8574';const [ux,uz]=map([130,-233]);ctx.strokeRect(ux-6,uz-8,12,16);ctx.setLineDash([]);
 const p=this.camera.position,anchor=this.nav.mode==='walk'?[p.x,p.z]:[this.nav.orbit.target.x,this.nav.orbit.target.z],forward=this.camera.getWorldDirection(new THREE.Vector3()),angle=Math.atan2(forward.x,-forward.z),[x,z]=map(anchor);ctx.save();ctx.translate(x,z);ctx.rotate(angle);ctx.fillStyle='#a4563a';ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(-5,5);ctx.lineTo(0,2);ctx.lineTo(5,5);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#a4563a';ctx.beginPath();ctx.arc(x,z,2,0,Math.PI*2);ctx.fill();$('coords').textContent=`${this.nav.mode==='walk'?'步行位置':'鸟瞰焦点'} x ${anchor[0].toFixed(1)} / z ${anchor[1].toFixed(1)} m`;}
}
