import * as THREE from 'three';
import {OrbitControls} from 'three/addons/OrbitControls.js';
import {Geography,terrainGeometry,makeRoads,makeRoute,inside,smooth} from './geo.js';
import {buildHall} from './architecture.js';
import {WaterSystem} from './water.js';
import {Forest} from './forest.js';

const $=id=>document.getElementById(id),canvas=$('scene'),asset=new URL('../assets/',import.meta.url);
let renderer,scene,camera,controls,geo,forest,route,sun,data,water=null,mode='orbit',fly=null,showLabels=true,quality='high',selectedPoi=null,yaw=0,pitch=0,lastTime=performance.now(),shadowRevision=-1;
const keys=new Set(),labels=[],errors=[],frameTimes=[];let fpsClock=0,frames=0,elapsed=0;const originalDPR=Math.min(devicePixelRatio,1.65),direction=new THREE.Vector3(),point=new THREE.Vector3();
window.addEventListener('unhandledrejection',e=>fatal(e.reason));
function loading(n,message){$('load-progress').value=n;if(message)$('load-text').textContent=message;}
function fatal(e){console.error(e);errors.push(String(e?.message||e));$('loading').style.opacity='1';$('loading').style.display='flex';$('load-error').hidden=false;$('load-error').textContent='加载失败：'+(e?.message||e)+'。请检查本地服务和 assets 文件夹；刷新可重新尝试。';}
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),5500);}
async function fetchAsset(path,type='json'){const r=await fetch(new URL(path,asset));if(!r.ok)throw new Error(`${path} (${r.status})`);return type==='json'?r.json():r.arrayBuffer();}

const manager=new THREE.LoadingManager();manager.onError=url=>{errors.push('材质 '+url);toast('有一张材质未能加载，已使用基础颜色。详细信息见浏览器控制台。');};
const loader=new THREE.TextureLoader(manager);
async function tex(name,color=true){try{const t=await loader.loadAsync(new URL('textures/'+name,asset).href);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);if(color)t.colorSpace=THREE.SRGBColorSpace;return t;}catch(e){errors.push(name);return null;}}
async function material(name,color=0xffffff){const [map,normalMap,roughnessMap]=await Promise.all([tex(name+'_Diffuse.jpg'),tex(name+'_nor_gl.jpg',false),tex(name+'_Rough.jpg',false)]);return new THREE.MeshStandardMaterial({map,normalMap,roughnessMap,color,normalScale:new THREE.Vector2(.55,.55),roughness:.94});}
function environment(){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,512);g.addColorStop(0,'#78a9cd');g.addColorStop(.38,'#b6d0de');g.addColorStop(.5,'#d4dfdd');g.addColorStop(1,'#d4dfdd');x.fillStyle=g;x.fillRect(0,0,1024,512);const t=new THREE.CanvasTexture(c);t.mapping=THREE.EquirectangularReflectionMapping;t.colorSpace=THREE.SRGBColorSpace;const pmrem=new THREE.PMREMGenerator(renderer);const env=pmrem.fromEquirectangular(t);scene.environment=env.texture;scene.environmentIntensity=.7;scene.background=t;scene.backgroundBlurriness=.1;scene.fog=new THREE.Fog(0xbdced1,2500,9500);pmrem.dispose();}

async function init(){try{
 if(location.protocol==='file:')return;
 try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){throw new Error('浏览器无法创建 WebGL 2 渲染器，请启用硬件加速或使用新版 Edge / Chrome。');}
 renderer.setPixelRatio(originalDPR);renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
 scene=new THREE.Scene();environment();camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.15,15000);controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.075;controls.maxPolarAngle=Math.PI*.485;controls.minDistance=4;controls.maxDistance=6000;controls.target.set(-70,330,-120);camera.position.set(1730,1170,1420);controls.update();
 scene.add(new THREE.HemisphereLight(0xd2e1ec,0x888069,2.4));sun=new THREE.DirectionalLight(0xffe5be,3.1);sun.position.set(-600,700,600);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-95,right:95,top:95,bottom:-95,near:1,far:1900});sun.shadow.bias=-.00015;sun.shadow.normalBias=.05;sun.shadow.radius=2;scene.add(sun,sun.target);
 loading(8,'读取 Copernicus DSM 与 OpenStreetMap');const [meta,raw]=await Promise.all([fetchAsset('geo/scene.json'),fetchAsset('geo/height.f32','buffer')]);data=meta;if(raw.byteLength!==data.grid.nx*data.grid.nz*4)throw new Error('高程文件大小不匹配');geo=new Geography(meta,new Float32Array(raw));
 loading(18,'准备实拍 PBR 材质');const [ground,stone,bark,roof,rock]=await Promise.all([material('brown_mud_leaves_01'),material('cobblestone_floor_08',0xaaa99d),material('bark_brown_02'),material('grey_roof_tiles'),material('rock_boulder_dry')]);const terrainMat=ground.clone();terrainMat.vertexColors=true;terrainMat.map=ground.map;terrainMat.normalScale.set(.22,.22);terrainMat.roughnessMap=null;
 const g=data.grid;const terrain=new THREE.Mesh(terrainGeometry(geo,g.xmin,g.zmin,251,226,40,[-1120,1120,-880,880]),terrainMat);terrain.receiveShadow=true;scene.add(terrain);const parkTerrain=new THREE.Mesh(terrainGeometry(geo,-1120,-880,113,89,20,true),terrainMat);parkTerrain.receiveShadow=true;scene.add(parkTerrain);const focus=new THREE.Mesh(terrainGeometry(geo,620,-160,131,171,2),ground);focus.receiveShadow=true;scene.add(focus);
 loading(29,'贴合真实道路与水岸');const paths=makeRoads(geo,stone);scene.add(paths.mesh);route=makeRoute(geo);scene.add(route);
 water=new WaterSystem(geo,scene);
 loading(37,'重建勤政殿重点近景');const hall=buildHall(geo,{stone,bark,roof,rock});scene.add(hall.group);
 // Unverified buildings remain omitted; no generic boxes masquerade as landmarks.
 loading(43,'生成树冠替身与近景枝叶');forest=new Forest(geo,scene,renderer,bark);await forest.init(n=>loading(n,'组织秋色植被与分区 LOD'));
 loading(90,'连接景点、相机与步行控制');makeLabels();wireUI();forest.update(camera,true);resize();
 window.sceneReady=true;window.xiangshan={getState,flyTo,home,setMode,geo,data,renderer,camera,scene,controls,forest,water,errors,snapshot:()=>renderer.domElement.toDataURL('image/png')};
 loading(100,'准备就绪');requestAnimationFrame(animate);$('loading').style.opacity='0';setTimeout(()=>$('loading').style.display='none',1000);
 if(new URLSearchParams(location.search).has('poi'))flyTo(new URLSearchParams(location.search).get('poi'),0);
 }catch(e){fatal(e);}
}

function getState(){return {ready:!!window.sceneReady,flying:!!fly,mode,quality,camera:camera?.position.toArray(),target:controls?.target.toArray(),fps:frameTimes.length?1000/(frameTimes.reduce((a,b)=>a+b)/frameTimes.length):0,frameSamples:frameTimes.length,drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,trees:forest?.count,water:water?.getState(),errors,viewport:[innerWidth,innerHeight],pixelRatio:renderer?.getPixelRatio(),three:THREE.REVISION,userAgent:navigator.userAgent};}
function makeLabels(){for(const p of data.landmarks){const el=document.createElement('button');el.className='poi';el.textContent=p.name;el.setAttribute('aria-label','前往'+p.name);el.addEventListener('click',()=>flyTo(p.key));$('poi-labels').append(el);labels.push({p,el});}}
function updateLabels(){camera.getWorldDirection(direction);for(const {p,el} of labels){point.set(p.x,geo.height(p.x,p.z)+20,p.z);const d=point.distanceTo(camera.position);const dot=point.clone().sub(camera.position).dot(direction);point.project(camera);const visible=showLabels&&mode==='orbit'&&dot>0&&point.z<1&&d>70&&Math.abs(point.x)<.96&&point.y>-.62&&point.y<.8;el.hidden=!visible;if(visible){el.style.left=(point.x*.5+.5)*innerWidth+'px';el.style.top=(-point.y*.5+.5)*innerHeight+'px';}}
 const dir=camera.getWorldDirection(new THREE.Vector3());$('north-arrow').style.transform=`rotate(${Math.atan2(dir.x,-dir.z)}rad)`;
}
function transition(pos,target,duration=2.6){controls.enabled=false;controls.enableDamping=false;controls.update();controls.enableDamping=true;const destination=pos.clone();destination.y=Math.max(destination.y,geo.height(destination.x,destination.z)+1.8);fly={from:camera.position.clone(),to:destination,startTarget:controls.target.clone(),target:target.clone(),time:0,duration};if(duration===0){camera.position.copy(destination);controls.target.copy(target);controls.update();camera.position.y=Math.max(camera.position.y,geo.height(camera.position.x,camera.position.z)+1.8);fly=null;controls.enabled=mode==='orbit';}}
function home(){selectedPoi=null;setMode('orbit',false);document.querySelectorAll('[data-poi]').forEach(b=>b.classList.remove('active'));$('location-kicker').textContent='西山 · 秋色';$('location-name').textContent='层林之间';$('location-description').textContent='从山麓向西，沿真实步道读懂香山的高差。';$('evidence').textContent='真实地形 · 近似景观';$('altitude').textContent='1 单位 = 1 米';transition(new THREE.Vector3(1730,1170,1420),new THREE.Vector3(-70,330,-120));}
const descriptions={east:['由此入山','东门','OSM 入口定位。门楼形制仍待核实，当前保留真实通行位置。','入口位置有依据'],hall:['重点近景 · 殿前','勤政殿','灰瓦、红柱与殿前石桥；平面位置来自地图，建筑细节按照片近似。','照片近似 · 尺寸未实测'],lake:['山麓 · 水岸','静翠湖','沿真实水体轮廓观察山脚层次。水位与岸边细节为场景近似。','岸线有依据 · 水位近似'],villa:['南麓 · 历史地标','双清别墅','已确认入口位置和相邻道路。院落建筑尚未完成，不以通用模型代替。','入口已定位 · 院落未建'],peak:['西山 · 制高点','香炉峰','沿地图步道抵达山顶。DSM 采样约 569.8 米，地图标高为 575 米。','山形有依据 · 峰顶建筑未建']};
function flyTo(key,duration=2.7){const p=data.landmarks.find(p=>p.key===key);if(!p)return;selectedPoi=key;const desc=descriptions[key];$('location-kicker').textContent=desc[0];$('location-name').textContent=desc[1];$('location-description').textContent=desc[2];$('evidence').textContent=desc[3];$('altitude').textContent=`DSM ${p.dsm.toFixed(1)} m`;document.querySelectorAll('[data-poi]').forEach(b=>b.classList.toggle('active',b.dataset.poi===key));
 if(mode==='walk'){const road=geo.nearestRoad(p.x,p.z,true);camera.position.set(road.x,geo.walkY(road.x,road.z)+1.68,road.z);yaw=Math.atan2(p.x-road.x,-(p.z-road.z));pitch=0;setWalkLook();forest.update(camera,true);return;}
 let pos,target=new THREE.Vector3(p.x,geo.height(p.x,p.z)+4,p.z);if(key==='hall'){const a=geo.hallAngle;pos=new THREE.Vector3(p.x+Math.sin(a)*60+Math.cos(a)*5,geo.hallBase+8.5,p.z+Math.cos(a)*60-Math.sin(a)*5);const center=geo.hallWorld(0,10);target.set(center[0],geo.hallBase+2.5,center[1]);}else if(key==='lake'){const lake=geo.waters.find(w=>w.id===605775489);pos=new THREE.Vector3(p.x+11,lake.level+18,p.z+12);target.set(p.x-12,lake.level+3,p.z-9);}else if(key==='east'){pos=new THREE.Vector3(p.x+54,p.dsm+19,p.z+12);target.set(geo.hall.x,geo.hallBase+4,geo.hall.z);}else if(key==='peak'){pos=new THREE.Vector3(p.x-40,p.dsm+65,p.z+85);target.set(p.x+700,320,p.z+60);}else pos=new THREE.Vector3(p.x+72,p.dsm+43,p.z+45);
 transition(pos,target,duration);
}
function setWalkLook(){camera.rotation.order='YXZ';camera.rotation.set(pitch,-yaw,0);}
function setMode(next,notify=true){if(!geo)return;fly=null;mode=next;controls.enabled=next==='orbit';$('walk').classList.toggle('active',next==='walk');$('orbit').classList.toggle('active',next==='orbit');$('walk').setAttribute('aria-pressed',next==='walk');$('orbit').setAttribute('aria-pressed',next==='orbit');$('walk-pad').hidden=next!=='walk';keys.clear();
 if(next==='walk'){const origin=data.landmarks.find(l=>l.key===selectedPoi)||controls.target;const p=geo.nearestRoad(origin.x,origin.z,true);camera.position.set(p.x,geo.walkY(p.x,p.z)+1.68,p.z);const dx=p.segment.b[0]-p.segment.a[0],dz=p.segment.b[1]-p.segment.a[1];yaw=Math.atan2(dx,-dz);pitch=0;setWalkLook();$('controls-help').textContent='WASD / 方向键行走 · 拖动观察 · Shift 加速 · Esc 返回';if(notify)toast('已进入道路步行模式。视高 1.68 米；道路边界提供基本防越界约束。');}
 else{const look=camera.getWorldDirection(new THREE.Vector3());controls.target.copy(camera.position).addScaledVector(look,15);controls.update();document.exitPointerLock?.();$('controls-help').textContent='拖动旋转 · 滚轮缩放 · 右键平移';}
 forest?.update(camera,true);
}
function updateWalk(dt){let f=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),s=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);if(!f&&!s)return;const normal=Math.hypot(f,s),speed=(keys.has('ShiftLeft')?3.2:1.5)*dt;f=f/normal*speed;s=s/normal*speed;const x=camera.position.x+Math.sin(yaw)*f+Math.cos(yaw)*s,z=camera.position.z-Math.cos(yaw)*f+Math.sin(yaw)*s;const p=geo.nearestRoad(x,z);let allowed=geo.canWalk(x,z);for(const b of data.buildings)if(b.id===533115769&&inside(x,z,b.points))allowed=false;
 if(allowed){camera.position.x=x;camera.position.z=z;camera.position.y=THREE.MathUtils.lerp(camera.position.y,geo.walkY(x,z)+1.68,Math.min(1,dt*14));}setWalkLook();}
function resize(){if(!renderer||!camera)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
function wireUI(){window.addEventListener('resize',resize);$('home').onclick=home;$('orbit').onclick=()=>setMode('orbit');$('walk').onclick=()=>setMode('walk');$('info').onclick=()=>$('data-dialog').showModal();$('close-info').onclick=()=>$('data-dialog').close();$('data-dialog').addEventListener('click',e=>{if(e.target===$('data-dialog'))$('data-dialog').close();});document.querySelectorAll('[data-poi]').forEach(b=>b.onclick=()=>flyTo(b.dataset.poi));$('labels').onclick=()=>{showLabels=!showLabels;$('labels').setAttribute('aria-pressed',showLabels);};$('route').onclick=()=>{route.visible=!route.visible;$('route').setAttribute('aria-pressed',route.visible);if(route.visible)toast('图示路线由 OSM 连通步道计算，平面长度约 1.89 km；不是实时通行或安全导航。');};$('quality').onclick=()=>{quality=quality==='high'?'low':'high';renderer.setPixelRatio(quality==='high'?originalDPR:Math.min(1,originalDPR*.7));renderer.shadowMap.enabled=quality==='high';renderer.shadowMap.needsUpdate=true;forest.nearRange=quality==='high'?58:34;forest.nearBudget=quality==='high'?112:56;forest.update(camera,true);$('quality').textContent=quality==='high'?'高':'省';toast(quality==='high'?'高画质：近景树木与柔和阴影':'省电画质：减少近景细节并关闭动态阴影');};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('当前浏览器不支持全屏，可使用浏览器菜单调整。');}};
 window.addEventListener('keydown',e=>{if($('data-dialog').open)return;if(e.code==='Escape'&&mode==='walk'){setMode('orbit');return;}if(mode==='walk'&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft'].includes(e.code)){keys.add(e.code);e.preventDefault();}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();lastTime=performance.now();});
 let drag=false,px=0,py=0;canvas.addEventListener('pointerdown',e=>{if(mode==='walk'){drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId);}else if(fly){fly=null;controls.enabled=true;}});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('pointermove',e=>{if(mode==='walk'&&drag){yaw+=(e.clientX-px)*.003;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-py)*.003,-1.3,1.3);px=e.clientX;py=e.clientY;setWalkLook();}});
 document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fatal(new Error('显卡渲染上下文中断，请刷新页面或切换省电画质后重试。'));});
}
function animate(time){requestAnimationFrame(animate);const ms=time-lastTime;lastTime=time;const dt=Math.min(ms/1000,.15);elapsed+=dt;if(document.hidden)return;
 if(fly){fly.time+=dt;const t=Math.min(1,fly.time/fly.duration),s=smooth(t);camera.position.lerpVectors(fly.from,fly.to,s);controls.target.lerpVectors(fly.startTarget,fly.target,s);camera.position.y+=Math.sin(t*Math.PI)*Math.min(220,fly.from.distanceTo(fly.to)*.22);const clearance=geo.height(camera.position.x,camera.position.z)+2;camera.position.y=Math.max(camera.position.y,clearance);controls.update();if(t===1){fly=null;controls.enabled=mode==='orbit';forest.update(camera,true);}}
 else if(mode==='walk')updateWalk(dt);else {controls.update();camera.position.y=Math.max(camera.position.y,geo.height(camera.position.x,camera.position.z)+1.8);}
 forest.update(camera);const focus=mode==='walk'?camera.position:controls.target;if(sun.target.position.distanceToSquared(focus)>.01||shadowRevision!==forest.revision){renderer.shadowMap.needsUpdate=true;shadowRevision=forest.revision;}sun.target.position.copy(focus);sun.position.copy(focus).add(new THREE.Vector3(-590,640,590));sun.target.updateMatrixWorld();
 water.update(camera,elapsed,quality);updateLabels();renderer.render(scene,camera);
 if(ms>0&&ms<1000){frameTimes.push(ms);if(frameTimes.length>300)frameTimes.shift();}frames++;fpsClock+=dt;if(fpsClock>.9){$('performance').textContent=`${Math.round(1000/(frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length))} FPS · ${quality==='high'?'高画质':'省电'} · 1 unit = 1 m`;$('performance').title='当前浏览器滚动帧率，不代表其他设备性能';fpsClock=0;frames=0;}
}
init();
