"use client";
import { useEffect, useRef } from "react";
import { CircleDot, TowerControl, X, Copy, Check, Clock, MapPin, ExternalLink } from "lucide-react";
import { PokemonArt } from "./pokemon-art";
import type { Bounds } from "@/lib/pokemon/model";
import { pogoMapLink } from "@/lib/pokemon/pogomap";
import { FACILITY_SOURCE_NAMES, LAYER_LABELS, FACILITY_FEEDS, FEED_LABELS, gymDirectoryRecords, activeActivities, raidPhase, remainingText, TEAM_NAMES, tierLabel, type FacilityResults, type FeedResult, type ResultKind, type Layers, type Gym, type Stop, type StopActivity } from "@/lib/pokemon/facilities";

export function VenueIcon({kind,team}:{kind:"gym"|"stop"|"rocket";team?:number|null}) {
  return <span className={`venue-icon ${kind} team-${team ?? "unknown"}`} aria-hidden="true">{kind==="gym"?<TowerControl size={27}/>:kind==="stop"?<CircleDot size={27}/>:<b>R</b>}</span>;
}
export function LayerBar({layers,counts,onToggle}:{layers:Layers;counts:Record<ResultKind,number>;onToggle:(kind:ResultKind)=>void}) {
  return <nav className="layer-bar" aria-label="地图图层"><span className="layer-caption">显示图层</span>{(Object.keys(LAYER_LABELS) as ResultKind[]).map(kind=><label key={kind} className={`layer-switch ${kind}`}><input type="checkbox" aria-label={`${LAYER_LABELS[kind]}图层`} checked={layers[kind]} onChange={()=>onToggle(kind)}/><span>{LAYER_LABELS[kind]}</span><b>{counts[kind]}</b></label>)}</nav>;
}
const feedStatus:Record<string,string>={idle:"等待更新",loading:"更新中",success:"缓存就绪",partial:"部分快照",error:"更新失败",authorization:"需要授权","rate-limit":"来源限流",uncovered:"数据源未覆盖"};
export function FacilityStatus({facilities,nyc,pgc}:{facilities:FacilityResults;nyc:boolean;pgc:boolean}) {
  return <details className="facility-status"><summary>设施数据范围与状态{FACILITY_FEEDS.some(feed=>["error","authorization","rate-limit"].includes(facilities[feed].status))&&nyc?<span className="facility-error-badge">部分来源不可用</span>:null}</summary><div className="facility-status-body">{nyc&&<><p>PogoMap.info 提供纽约市社区道馆目录；NYC PokéMap 提供团体战、补给站任务与活动。道馆目录及团体战在打开页面时读取一次，独立于五分钟刷新；任务和活动定时更新。目录不保证完整，读取失败时明确标注原因和固定参考日期。社区队伍不视为实时占领情况；照片、守馆宝可梦和空位未知。</p><div className="facility-feed-list">{FACILITY_FEEDS.map(feed=>{const r=facilities[feed];return <div key={feed}><strong>{FEED_LABELS[feed]}</strong><span className={`inline-state ${r.status}`}>{feed==="pogoGyms"&&r.status==="authorization"?"服务端访问被拒绝":feedStatus[r.status]} · {r.records.length} 条</span><time>{r.updatedAt?`来源更新 ${new Date(r.updatedAt).toLocaleTimeString("zh-CN",{hour12:false})}`:"来源更新时间未知"}{r.fetchedAt?` · 取得 ${new Date(r.fetchedAt).toLocaleTimeString("zh-CN",{hour12:false})}`:""}</time>{r.referenceRecords?.length&&!r.records.length&&<span className="stale-label">参考快照 {r.referenceRecords.length} 条 · {r.referenceAt?new Date(r.referenceAt).toLocaleString("zh-CN",{hour12:false}):"采集时间未知"}</span>}{r.stale&&<span className="stale-label">使用上次缓存</span>}{r.message&&<p>{r.message}</p>}</div>;})}</div></>}{pgc&&<p>纽约市外：四个新增城市的团体战、任务与活动，以及旧金山试点任务，见“数据源设置”。其他范围未取得设施快照，可通过 Gym 页的 PogoMap 入口查看官网社区目录。PogoMap 未提供已核实的全球全量接口；PGC 未发现已核实的设施接口。</p>}<p>名称和坐标均一致、且匹配唯一时，道馆合并为一个标记，并分别保留社区场所与团体战来源。火箭队与补给站共用一个位置标记；活动结束后自动移除 R。宝可梦的 IV / CP 筛选仅作用于宝可梦。</p></div></details>;
}
export function GymDirectoryStatus({directory,bounds,nyc}:{directory:FeedResult<Gym>;bounds:Bounds|null;nyc:boolean}) {
  const reference = nyc && !directory.records.length && gymDirectoryRecords(directory).length > 0;
  const status = directory.status === "authorization" ? "服务端访问被拒绝" : directory.status === "partial" ? "社区目录已取得" : feedStatus[directory.status];
  return <div className="gym-directory-status" aria-label="PogoMap 道馆来源状态"><div><strong>PogoMap.info</strong><span className={`inline-state ${nyc?directory.status:"uncovered"}`}>{nyc?status:"当前地区快照未取得"}</span></div><p>{nyc?reference?`本次读取失败，显示固定参考快照。${directory.message}`:directory.message||"本次打开读取一次，地图移动和刷新按钮使用现有目录":"地图内尚无此地区道馆快照，可查看官网。"}</p><div className="gym-directory-footer"><small>{!nyc?"此地区目录尚未取得":reference?`参考采集 ${new Date(directory.referenceAt!).toLocaleString("zh-CN",{hour12:false})} · 不保证完整` : directory.fetchedAt?`目录取得 ${new Date(directory.fetchedAt).toLocaleString("zh-CN",{hour12:false})} · 打开时读取一次`:"目录尚未取得"}</small><a href={pogoMapLink(bounds)} target="_blank" rel="noreferrer">在 PogoMap 查看此区域<ExternalLink size={12}/></a></div></div>;
}
export function ResultTabs({kind,counts,onChange}:{kind:ResultKind;counts:Record<ResultKind,number>;onChange:(kind:ResultKind)=>void}) {
  return <div className="result-tabs" role="tablist" aria-label="结果类型">{(Object.keys(LAYER_LABELS) as ResultKind[]).map(k=><button role="tab" aria-selected={kind===k} key={k} onClick={()=>onChange(k)}>{k==="gym"?"Gym":k==="stop"?"Stop":LAYER_LABELS[k]}<b>{counts[k]}</b></button>)}</div>;
}
const activityName=(a:StopActivity)=>a.activity==="rocket"?`${a.opponent??"角色未知"} · ${a.typeName??"属性未知"}`:a.activity==="kecleon"?"变隐龙活动":a.activity==="gold"?"金币活动":a.activity==="showcase"?"展示赛":a.activity==="npc"?"NPC 活动":"活动类型未知";
function gymSummary(g:Gym,now:number) {
  if (g.source==="pogomap"&&!g.raidRecord) return `${g.referenceAt?"参考 · ":""}${g.community?.elite?"社区精英道馆":"社区道馆"} · 团体战未知`;
  const phase=raidPhase(g,now);
  return phase==="ended"?"本次团体战已结束":phase==="egg"?`${tierLabel(g.raid.tier)} · 待孵化`:phase==="pending"?"已到孵化时间 · 首领待更新":`${g.raid.name??"首领未知"} · ${tierLabel(g.raid.tier)}`;
}
export function VenueListContent({kind,gyms,stops,query,onQuery,onSelect,selectedId,now,nyc,status}:{kind:"gym"|"stop"|"rocket";gyms:Gym[];stops:Stop[];query:string;onQuery:(query:string)=>void;onSelect:(record:Gym|Stop)=>void;selectedId:string|null;now:number;nyc:boolean;status:string}) {
  const records=kind==="gym"?gyms:stops;
  return <><div className="venue-search"><label htmlFor="venue-query">地点名称</label><input id="venue-query" placeholder="在缓存中筛选地点" value={query} onChange={e=>onQuery(e.target.value)}/></div><div className="result-scroll" role="tabpanel" aria-label={`${LAYER_LABELS[kind]}结果`}>{records.length?records.map(p=>{
    const gym="raid" in p?p:null,stop="quests" in p?p:null,activity=stop?activeActivities(stop,now).find(a=>kind!=="rocket"||a.activity==="rocket"):null;
    return <button key={p.id} className={`venue-row ${selectedId===p.id?"selected":""}`} onClick={()=>onSelect(p)}>{gym&&raidPhase(gym,now)==="active"&&gym.raid.dex?<PokemonArt pokemon={gym.raid}/>:<VenueIcon kind={kind} team={gym?.team}/>}<div className="spawn-info"><div className="spawn-title"><strong>{p.name??"地点名称未知"}</strong><span className={`source-tag ${p.source}`}>{p.source==="pogomap"?gym?.referenceAt?"Pogo 参考":"Pogo":FACILITY_SOURCE_NAMES[p.source]}</span></div><p className="venue-row-summary">{gym?gymSummary(gym,now):activity?activityName(activity):`${stop?.quests.filter(q=>q.expiresAt===null||q.expiresAt>now).length??0} 项已报告任务`}</p><span className="spawn-expiry"><Clock size={12}/>{gym?gym.source==="pogomap"&&!gym.raidRecord?"社区报告 · 实时队伍未知":`${TEAM_NAMES[gym.team??-1]??"队伍未知"} · ${remainingText(raidPhase(gym,now)==="egg"?gym.raid.startsAt:gym.raid.endsAt,now)}`:activity?remainingText(activity.endsAt,now):"任务结束时间未知"}</span></div></button>;
  }):<div className="empty-state"><MapPin size={30}/><strong>{!nyc?"此地区设施数据尚不可用":["error","authorization","rate-limit"].includes(status)?"此类来源暂不可用":"当前视野没有此类记录"}</strong><p>{!nyc?"当前未取得此地区设施快照。":kind==="gym"?"社区目录不保证完整，团体战只含来源报告的记录；空列表不代表此处没有道馆。":"移动地图或调整地点名称筛选；上方可查看来源状态。"}</p></div>}</div><footer className="results-footer"><span>视野内 {records.length} 个{kind==="rocket"?"入侵地点":"地点"}</span><span>{kind==="gym"?"社区目录 / 团体战":"任务 / 活动目录"}</span></footer></>;
}
const absolute=(t:number|null)=>t===null?"未知":new Date(t).toLocaleString("zh-CN",{hour12:false});
export function VenueDetail({kind,record,now,onClose,onCopy,copied,fetchedAt=null}:{kind:"gym"|"stop"|"rocket";record:Gym|Stop;now:number;onClose:()=>void;onCopy:()=>void;copied:boolean;fetchedAt?:number|null}) {
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    const element = dialog.current;
    if (element && !element.open) element.showModal();
    return () => { if (element?.open) element.close(); };
  }, []);
  const gym="raid" in record?record:null,stop="quests" in record?record:null;
  const activities=stop?activeActivities(stop,now).filter(a=>kind!=="rocket"||a.activity==="rocket"):[];
  return <dialog ref={dialog} className="venue-detail-dialog" aria-label={`${LAYER_LABELS[kind]}详情`} onCancel={event=>{event.preventDefault();onClose();}}><header className="venue-dialog-header"><div className="venue-detail-heading"><VenueIcon kind={kind} team={gym?.team}/><div><span>{LAYER_LABELS[kind]}</span><h3>{record.name??"地点名称未知"}</h3></div></div><button className="icon-button" aria-label="关闭设施详情" onClick={onClose} autoFocus><X size={22}/></button></header><div className="venue-detail-scroll">
    {gym?.community&&<section className="gym-community-detail"><strong>社区道馆资料{gym.referenceAt?" · 参考快照":""}</strong>{gym.referenceAt?<p className="venue-note">参考采集：{absolute(gym.referenceAt)}。此资料不会随刷新重置采集时间，不代表当前游戏状态。</p>:fetchedAt&&<p className="venue-note">本次目录取得：{absolute(fetchedAt)}。道馆目录仅在打开页面时读取一次。</p>}<dl className="venue-fields"><dt>精英道馆标记</dt><dd>{gym.community.elite===null?"未知":gym.community.elite?"是（社区标记）":"否"}</dd><dt>赞助 / 营地</dt><dd>{gym.community.sponsored===null?"未知":gym.community.sponsored?"是":"否"}</dd><dt>来源核实标记</dt><dd>{gym.community.verified===null?"未知":gym.community.verified?"已标记核实":"未标记核实"}</dd><dt>社区报告队伍</dt><dd>{gym.community.reportedTeam??"未知"}</dd></dl><p className="venue-note">PogoMap 社区维护；报告队伍与精英标记不保证当前游戏状态。照片、守馆宝可梦、空位未知。</p><a href={gym.community.url} target="_blank" rel="noreferrer">查看 PogoMap 道馆原记录<ExternalLink size={13}/></a></section>}
    {gym&&(gym.source!=="pogomap"||gym.raidRecord)?<><div className="raid-detail">{gym.raid.dex&&raidPhase(gym,now)==="active"?<PokemonArt pokemon={gym.raid}/>:null}<div><strong>{gymSummary(gym,now)}</strong><p>来源观测队伍：{TEAM_NAMES[gym.team??-1]??"未知"}</p><p>CP：{gym.raid.cp??"未知"} · 形态：{gym.raid.form??"未知"}</p></div></div><dl className="venue-fields"><dt>开始（本地时间）</dt><dd>{absolute(gym.raid.startsAt)}</dd><dt>结束（本地时间）</dt><dd>{absolute(gym.raid.endsAt)}</dd><dt>{raidPhase(gym,now)==="egg"?"距孵化":"距结束"}</dt><dd>{remainingText(raidPhase(gym,now)==="egg"?gym.raid.startsAt:gym.raid.endsAt,now)}</dd></dl><p className="venue-note">团体战来源：{FACILITY_SOURCE_NAMES[gym.raidRecord?.source??gym.source]}。{gym.raidRecord?`原始 ID：${gym.raidRecord.rawId??"未知"}；内部记录键：${gym.raidRecord.id}。`:""}孵化后首领尚未取得时显示待更新。</p></>:gym?<div className="raid-detail"><div><strong>实时团体战：未知</strong><p>未取得能与该道馆唯一匹配的团体战记录。</p></div></div>:null}
    {activities.map(a=><section className="stop-activity" key={a.id}><strong>{activityName(a)}</strong><p>{a.gender?`性别：${a.gender} · `:""}{remainingText(a.endsAt,now)}</p>{a.radar&&<p>需要：{a.radar}</p>}<p>开始：{absolute(a.startsAt)}<br/>结束：{absolute(a.endsAt)}</p><small>来源：{FACILITY_SOURCE_NAMES[a.source]} · 原始 ID：{a.rawId??"未知"}</small>{a.activity==="unknown"&&<p>来源角色编号：{a.characterCode??"未知"} · 类型：{a.typeCode??"未知"}</p>}</section>)}
    {stop&&kind==="stop"&&<section className="stop-quests"><h4>来源报告的任务</h4>{stop.quests.filter(q=>q.expiresAt===null||q.expiresAt>now).length?stop.quests.filter(q=>q.expiresAt===null||q.expiresAt>now).map(q=><div key={q.id}><strong>{q.description??"任务未知"}</strong><p>奖励：{q.reward??"未知"}</p><small>结束时间：{absolute(q.expiresAt)} · 来源：{FACILITY_SOURCE_NAMES[q.source]} · 原始 ID：{q.rawId??"未知"}</small></div>):<p>任务未知</p>}{stop.directory&&<p className="venue-note">PogoMap 静态社区 Stop · 原始 ID：{stop.rawId??"未知"}。本次打开读取一次，实时活动未知。</p>}<p className="venue-note">仅展示取得的任务与活动。补给站照片、诱饵等字段未由当前接口提供。</p></section>}
  </div><footer className="venue-dialog-footer"><div className="detail-coords"><span>{record.lat.toFixed(6)}, {record.lng.toFixed(6)}</span><button onClick={onCopy}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?"已复制":"复制"}</button></div><p className="detail-source">来源：{FACILITY_SOURCE_NAMES[record.source]}<br/>原始 ID：{record.rawId??"未知（按来源与坐标合并地点）"}</p></footer></dialog>;
}
