import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
let playwright;
try{playwright=await import('playwright');}catch{playwright=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE||path.resolve(root,'../../../../pingtan/node_modules/playwright/index.mjs')).href);}
const {chromium}=playwright;
const base=process.env.TEST_URL||'http://127.0.0.1:5190/',errors=[],failedRequests=[],checks=[],failures=[];
const report={dateLocal:'2026-10-07 Asia/Shanghai',timestampUTC:new Date().toISOString(),base,errors,failedRequests,checks,failures,performance:[],device:{os:os.type()+' '+os.release(),cpu:os.cpus()[0]?.model,ramGB:Math.round(os.totalmem()/2**30)},limitations:'Headless Chromium on this Windows host. Mobile results are touch emulation; not measurements of a real phone. Geographic accuracy is not established by software tests.'};
fs.mkdirSync(path.join(root,'evidence'),{recursive:true});
const executable=process.env.CHROMIUM_PATH||'C:/Users/YUE/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe';
const browser=await chromium.launch({headless:true,executablePath:fs.existsSync(executable)?executable:undefined,args:['--enable-webgl','--ignore-gpu-blocklist']});
report.browser=await browser.version();
const context=await browser.newContext({viewport:{width:1440,height:960},deviceScaleFactor:1});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>failedRequests.push(r.url()+': '+r.failure()?.errorText));
const assert=(value,name)=>{checks.push({name,passed:!!value});if(!value)failures.push(name);};
const settle=async()=>{await page.waitForFunction(()=>window.__sanfang&&!window.__sanfang.nav.transitioning);await page.waitForTimeout(650);};
async function shot(name){await page.screenshot({path:path.join(root,'evidence',name)});}
async function canvasShot(name){const data=await page.evaluate(()=>{const s=window.__sanfang;s.renderer.render(s.scene,s.camera);return document.querySelector('#view').toDataURL('image/png');});fs.writeFileSync(path.join(root,'evidence',name),Buffer.from(data.split(',')[1],'base64'));}
async function perf(label){report.performance.push(await page.evaluate(async label=>{const values=[];let previous=performance.now(),start=previous;await new Promise(resolve=>{function frame(now){values.push(now-previous);previous=now;if(now-start<3000)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});values.shift();values.sort((a,b)=>a-b);const mean=values.reduce((a,b)=>a+b,0)/values.length,s=window.__sanfang;return {label,sampleSeconds:3,frames:values.length,meanFrameMs:+mean.toFixed(2),observedRafFps:+(1000/mean).toFixed(1),p95FrameMs:+values[Math.floor(values.length*.95)].toFixed(2),drawCalls:s.renderer.info.render.calls,triangles:s.renderer.info.render.triangles,geometries:s.renderer.info.memory.geometries,textures:s.renderer.info.memory.textures,pixelRatio:s.renderer.getPixelRatio(),quality:s.quality()};},label));}
try{
 const start=Date.now();await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__sanfang?.ready,null,{timeout:90000});report.readyMs=Date.now()-start;
 report.scene=await page.evaluate(()=>{const s=window.__sanfang,gl=s.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),buildings:s.data.summary.buildings,sampleBuildings:s.data.summary.sampleBuildings,roads:s.data.summary.roads,viewport:[innerWidth,innerHeight],revision:s.renderer.info.render.triangles};});
 assert(await page.locator('#loading').isHidden(),'critical local resources load');await shot('01-overview.png');await canvasShot('overview-scene.png');await perf('均衡 · 全区鸟瞰');
 await page.locator('#walk').click();await settle();assert(await page.evaluate(()=>window.__sanfang.camera.position.y===1.65),'walking camera at 1.65 m');assert(await page.evaluate(()=>{const s=window.__sanfang;return !s.collision.blocked(s.camera.position.x,s.camera.position.z);}), 'tree viewpoint has collision clearance');await shot('02-heart-tree-eye.png');await canvasShot('heart-tree-scene.png');await perf('均衡 · 样板爱心树附近');
 const before=await page.evaluate(()=>window.__sanfang.camera.position.toArray());await page.locator('#view').focus();await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.up('w');const after=await page.evaluate(()=>window.__sanfang.camera.position.toArray());assert(Math.hypot(after[0]-before[0],after[2]-before[2])>.5,'W key moves at walking speed');
 await page.locator('[data-place="ye"]').click();await settle();await shot('03-ye-residence-eye.png');await canvasShot('ye-residence-scene.png');
 await page.locator('[data-place="north"]').click();await settle();await shot('04-north-gate-eye.png');await canvasShot('north-gate-scene.png');
 await page.locator('[data-place="yijin"]').click();await settle();await shot('05-yijin-eye.png');
 // A real façade collision, tested over multiple motion frames, not only by
 // duplicating the same collision formula in a second unit test.
 const collide=await page.evaluate(()=>{const s=window.__sanfang,b=s.data.buildings.find(b=>b.id==='985162844'),a=b.footprint[1],q=b.footprint[2],p=[(a[0]+q[0])/2,(a[1]+q[1])/2];s.nav.transition=null;s.nav.mode='walk';s.nav.orbit.enabled=false;s.camera.position.set(p[0]+1.7,1.65,p[1]);s.nav.yaw=Math.PI/2;s.nav.pitch=0;s.nav.look(0,0);return p;});
 await page.locator('#view').focus();await page.keyboard.down('w');await page.waitForTimeout(2400);await page.keyboard.up('w');report.collision=await page.evaluate(()=>{const s=window.__sanfang;return {position:s.camera.position.toArray(),blocked:s.collision.blocked(s.camera.position.x,s.camera.position.z)};});assert(!report.collision.blocked,'W movement stops outside a mapped wall');assert(report.collision.position[0]>collide[0]+.25,'wall clearance remains above body radius');
 await page.locator('#labels-toggle').click();assert(await page.locator('#labels').isHidden(),'labels toggle');await page.locator('#labels-toggle').click();
 await page.locator('#evidence-toggle').click();assert(await page.locator('#evidence-toggle').getAttribute('aria-pressed')==='true','evidence overlay');await page.locator('#evidence-toggle').click();
 await page.locator('#quality').selectOption('high');await page.evaluate(()=>window.__sanfang.jump('tree','walk'));await settle();await perf('精细 · 样板');await page.locator('#quality').selectOption('low');await perf('节能 · 样板');
 const exported=page.waitForEvent('download');await page.locator('#capture').click();const download=await exported;await download.saveAs(path.join(root,'evidence/08-export.png'));assert(fs.statSync(path.join(root,'evidence/08-export.png')).size>30000,'scene PNG export contains rendered image');
 await page.locator('#aerial').click();await settle();await page.locator('#minimap').click({position:{x:105,y:105}});await settle();assert(await page.evaluate(()=>window.__sanfang.nav.orbit.target.distanceTo(new (window.__sanfang.camera.position.constructor)(-45,0,50))>10),'minimap destination changes camera target');
 await page.locator('#info-toggle').click();assert(await page.locator('#info').isVisible(),'source panel');await page.locator('#info-close').click();
 const phoneContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const phone=await phoneContext.newPage();await phone.goto(base);await phone.waitForFunction(()=>window.__sanfang?.ready);assert(await phone.evaluate(()=>window.__sanfang.quality()==='low'),'touch device defaults to low profile');await phone.locator('#walk').tap();await phone.waitForFunction(()=>!window.__sanfang.nav.transitioning);assert(await phone.locator('#touch-controls').isVisible(),'touch movement controls visible');const bounds=await phone.locator('[data-move="forward"]').boundingBox(),cdp=await phoneContext.newCDPSession(phone),p0=await phone.evaluate(()=>window.__sanfang.camera.position.toArray());await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2}]});await phone.waitForTimeout(700);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const p1=await phone.evaluate(()=>window.__sanfang.camera.position.toArray());assert(Math.hypot(p1[0]-p0[0],p1[2]-p0[2])>.25,'touch forward moves');assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile has no horizontal overflow');await phone.screenshot({path:path.join(root,'evidence/06-mobile.png')});await phoneContext.close();
 const failed=await context.newPage();await failed.route('**/data/site.json',r=>r.fulfill({status:404,body:'missing'}));await failed.goto(base);await failed.waitForSelector('#error:not([hidden])');assert((await failed.locator('#error-message').textContent()).includes('site.json'),'missing resource error names file');await failed.screenshot({path:path.join(root,'evidence/07-resource-failure.png')});await failed.close();
 const fallback=await context.newPage();await fallback.route('**/textures/plaster-color.webp',r=>r.fulfill({status:404,body:'missing'}));await fallback.goto(base);await fallback.waitForFunction(()=>window.__sanfang?.ready);assert(await fallback.locator('#warning').isVisible(),'optional PBR failure keeps scene and shows warning');await fallback.close();
 assert(errors.length===0,'no normal-run JavaScript or console errors');assert(failedRequests.length===0,'no normal-run network resource failures');
}catch(error){failures.push(error.stack||error.message);}finally{fs.writeFileSync(path.join(root,'evidence/test-results.json'),JSON.stringify(report,null,2));await browser.close();}
console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
