// Extract display metadata from the original library; never modify game resources.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const lib = fs.readFileSync(path.join(root, 'assets/dictionary-original.lib'));
const decoder = new TextDecoder('gbk');
function item(id, index = 0) {
  const p = lib.readUInt32LE((id - 1) * 4), count = lib.readUInt16LE(p + 6), size = lib.readUInt32LE(p + 8);
  if (index >= count) throw Error('Resource index out of range');
  const offset = size ? 14 + index * size : lib.readUInt32LE(p + 14 + index * 8);
  const length = size || lib.readUInt32LE(p + 18 + index * 8);
  return lib.subarray(p + offset, p + offset + length);
}
const grid = Array.from(item(2, 13)); // C_MAP, item 14 of IFACE_CONID
if (grid.length !== 108 || grid.filter(Boolean).length !== 38) throw Error('Unexpected original city grid');
const names = [62,70,71,72].map(id => Array.from({ length: 200 }, (_, i) => decoder.decode(item(id, i)).replace(/\0/g, '')));
const cityNames = Array.from({ length: 38 }, (_, i) => decoder.decode(item(58, i)));
const links = Array.from({ length: 38 }, (_, i) => Array.from(item(59).subarray(i * 16, i * 16 + 8)).filter(Boolean).map(id => id - 1));
const pictures = {};
for (const id of [47,48,49,50,51,54,55,56,69,75]) {
  const p = item(id), w = p.readUInt16LE(0), h = p.readUInt16LE(2), count = p.readUInt16LE(4), mask = p[6];
  pictures[id] = { w, h, count, mask, bits: p.subarray(7).toString('base64') };
}
const unique = new Map();
for (let period = 0; period < 4; period++) {
  const cities = item(57, period);
  for (let i = 0; i < 38; i++) {
    const owner = cities.readUInt16LE(i * 37 + 1);
    if (!owner || owner > 200) continue;
    const p = item(48 + period).subarray(7 + (owner - 1) * 72, 7 + owner * 72);
    unique.set(p.toString('hex'), { name: names[period][owner - 1], period, index: owner - 1 });
  }
}
const rulers = [...unique.values()];
const portraitSheets = [
  { file: 'rulers-1.png', start: 0, count: 12, columns: 3, rows: 4 },
  { file: 'rulers-2.png', start: 12, count: 12, columns: 3, rows: 4 },
  { file: 'rulers-3.png', start: 24, count: 9, columns: 3, rows: 3 }
];
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'assets/hd/general-portraits.json'), 'utf8'));
for (const sheet of manifest.sheets) {
  if (sheet.subjects.length > sheet.columns * sheet.rows) throw Error('Portrait sheet exceeds its grid');
  const start = unique.size;
  for (const subject of sheet.subjects) {
    const { name, period } = subject;
    const index = subject.index ?? names[period]?.indexOf(name) ?? -1;
    if (index < 0 || index >= 200 || names[period]?.[index] !== name) throw Error(`Unknown portrait: ${name}, period ${period}`);
    const key = item(48 + period).subarray(7 + index * 72, 7 + (index + 1) * 72).toString('hex');
    if (unique.has(key)) throw Error(`Duplicate portrait: ${name}`);
    unique.set(key, { name, period, index });
  }
  portraitSheets.push({ file: sheet.file, start, count: sheet.subjects.length, columns: sheet.columns, rows: sheet.rows });
}
const keys = [...unique.keys()], portraitSlots = {};
for (let id = 48; id <= 51; id++) portraitSlots[id] = Array.from({ length: 200 }, (_, i) => keys.indexOf(item(id).subarray(7 + i * 72, 7 + (i + 1) * 72).toString('hex')));
if (manifest.complete) {
  for (const [resource, slots] of Object.entries(portraitSlots)) {
    if (slots.some(slot => slot < 0)) throw Error(`Incomplete portrait coverage in resource ${resource}`);
  }
  for (const sheet of portraitSheets) {
    if (!fs.existsSync(path.join(root, 'assets/hd', sheet.file))) throw Error(`Missing portrait sheet: ${sheet.file}`);
  }
}
const data = { width: 12, height: 9, grid, links, names, cityNames, pictures, portraitSlots, portraitSheets, rulers, portraits: [...unique.values()],
  memory: { cities: 2704560, cityStride: 37, ownerOffset: 1, player: 2666546, period: 2666551, mapWidth: 2653005, mapHeight: 2653006 } };
fs.writeFileSync(path.join(root, 'assets/map-art-data.js'), '// Generated by tools/build-map-art.cjs from original resources.\nwindow.BayeMapData = ' + JSON.stringify(data) + ';\n');
console.log(`Extracted ${grid.filter(Boolean).length} city coordinates and ${unique.size} remastered portraits (${rulers.length} starting rulers).`);
