import {chromium} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
const out=path.resolve('evidence');fs.mkdirSync(out,{recursive:true});
const executable=process.env.PALACE_CHROME||'C:/Users/YUE/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe';
const browser=await chromium.launch({headless:true,...(fs.existsSync(executable)?{executablePath:executable}:{}),args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[],failed=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()}));
async function check(name,condition,details){checks.push({name,pass:!!condition,details});if(!condition)console.log('FAIL',name,details);}
try{
 await page.goto(process.env.PALACE_URL||'http://127.0.0.1:5178/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__palace?.ready,{timeout:60000});await page.waitForTimeout(1500);
 const env=await page.evaluate(()=>{const {renderer}=window.__palace,g=renderer.getContext(),ext=g.getExtension('WEBGL_debug_renderer_info');return{userAgent:navigator.userAgent,viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,renderer:ext?g.getParameter(ext.UNMASKED_RENDERER_WEBGL):g.getParameter(g.RENDERER),vendor:ext?g.getParameter(ext.UNMASKED_VENDOR_WEBGL):g.getParameter(g.VENDOR),webgl:g.getParameter(g.VERSION),layout:window.__palace.data.buildings.length};});
 await page.screenshot({path:path.join(out,'01-full-site.png')});
 const views=[['taihe','02-taihe'],['wumen','03-wumen'],['qianqing','04-qianqing'],['qinan','05-garden'],['huangji','06-east'],['wuying','07-west']];
 for(const [id,file]of views){await page.locator(`[data-landmark="${id}"]`).click();await page.waitForTimeout(700);await page.locator('#info .close').click();await page.screenshot({path:path.join(out,file+'.png')});}
 await page.evaluate(()=>{const p=window.__palace,b=p.building.models.find(b=>b.id==='corner-1--1');p.nav.locate(b);});await page.waitForTimeout(500);await page.screenshot({path:path.join(out,'10-northeast-corner.png')});
 await check('地标快速定位与资料卡',await page.evaluate(()=>window.__palace.ui.selected.name==='武英殿'));
 await page.locator('#labels').click();await check('标签切换',await page.evaluate(()=>!window.__palace.ui.labels));await page.locator('#labels').click();
 const before=await page.evaluate(()=>window.__palace.camera.position.toArray());await page.mouse.move(700,400);await page.mouse.down();await page.mouse.move(780,420,{steps:10});await page.mouse.up();await page.mouse.wheel(0,-150);await page.waitForTimeout(500);const after=await page.evaluate(()=>window.__palace.camera.position.toArray());await check('鸟瞰旋转缩放',JSON.stringify(before)!==JSON.stringify(after),{before,after});
 await page.locator('#home').click();await page.locator('[data-landmark="taihe"]').click();await page.locator('#info .close').click();await page.locator('#walk').click();await page.waitForTimeout(300);const walkBefore=await page.evaluate(()=>window.__palace.camera.position.toArray());await page.keyboard.down('KeyW');await page.waitForTimeout(1100);await page.keyboard.up('KeyW');const walkAfter=await page.evaluate(()=>window.__palace.camera.position.toArray());await check('WASD步行',Math.hypot(walkAfter[0]-walkBefore[0],walkAfter[2]-walkBefore[2])>.3,{walkBefore,walkAfter});
 await page.mouse.move(710,350);await page.mouse.down();await page.mouse.move(800,370,{steps:5});await page.mouse.up();await check('鼠标观察',await page.evaluate(()=>Math.abs(window.__palace.nav.yaw)>.01));await page.screenshot({path:path.join(out,'08-walking.png')});
 const collision=await page.evaluate(()=>{const p=window.__palace,{nav}=p,ta=p.building.models.find(b=>b.id==='taihe');return{building:nav.canStand(ta.x,ta.z,8.13,false),wall:nav.canStand(376,0,0,false),water:nav.canStand(400,0,0,false),outside:nav.canStand(800,0,0,false),courtyard:nav.canStand(-3,180,0,false),eyeHeight:p.camera.position.y-nav.ground(p.camera.position.x,p.camera.position.z),ramps:p.landscape.ramps.length,bridges:p.landscape.bridges.length};});await check('建筑/城墙/水体/边界约束',!collision.building&&!collision.wall&&!collision.water&&!collision.outside,collision);await check('视高与台阶/桥梁',Math.abs(collision.eyeHeight-1.68)<.01&&collision.ramps>0&&collision.bridges===5,collision);
 const results=[];for(const quality of ['low','medium','high']){await page.locator('#quality').selectOption(quality);await page.locator('#home').click();await page.waitForTimeout(400);const result=await page.evaluate(async()=>{const p=window.__palace;let stamps=[];await new Promise(resolve=>{const start=performance.now();function frame(t){stamps.push(t);if(t-start<1600)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});let deltas=stamps.slice(1).map((v,i)=>v-stamps[i]);const avg=deltas.reduce((a,b)=>a+b,0)/deltas.length;deltas.sort((a,b)=>a-b);return{quality:p.quality(),frames:deltas.length,meanFrameMs:avg,fps:1000/avg,p95FrameMs:deltas[Math.floor(deltas.length*.95)],calls:p.renderer.info.render.calls,triangles:p.renderer.info.render.triangles,geometries:p.renderer.info.memory.geometries,textures:p.renderer.info.memory.textures,pixelRatio:p.renderer.getPixelRatio(),buffer:[p.renderer.domElement.width,p.renderer.domElement.height]};});results.push(result);}
 await check('低中高画质切换',results.map(r=>r.quality).join(',')==='low,medium,high');await page.locator('#gray').click();await page.screenshot({path:path.join(out,'09-graybox.png')});await page.locator('#gray').click();await page.locator('#quality').selectOption('medium');await page.locator('#about').click();await check('资料对话框',await page.locator('#sources').isVisible());await page.locator('#close-sources').click();
 await check('无页面/控制台错误',errors.length===0,errors);await check('无资源加载失败',failed.length===0,failed);
 const report={timestamp:new Date().toISOString(),environment:env,checks,performance:results,errors,failed,limitations:['自动化使用独立headless Chromium；不代表用户前台浏览器硬件帧率','硬件渲染器与软件渲染情况见environment.renderer；未做GPU计时查询','性能取各画质全域固定视角约1.6秒，未覆盖长时间遍历'],passed:checks.every(x=>x.pass)};
 fs.writeFileSync(path.join(out,'test-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
