import fs from 'node:fs';
const raw=JSON.parse(fs.readFileSync('research/osm.json','utf8'));
const origin=[116.298,40.006];
const xy=p=>[+( (p.lon-origin[0])*111320*Math.cos(origin[1]*Math.PI/180)).toFixed(2),+(-(p.lat-origin[1])*111320).toFixed(2)];
const pointInside=(p,r)=>{let inR=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inR=!inR}return inR};
const boundary=raw.elements.find(e=>e.type==='way'&&e.id===24827108).geometry.map(xy);
function join(parts){let rings=[];while(parts.length){let r=parts.shift().slice();let found=true;while(found&&!(r[0][0]===r.at(-1)[0]&&r[0][1]===r.at(-1)[1])){found=false;for(let i=0;i<parts.length;i++){let a=parts[i];const eq=(a,b)=>a[0]===b[0]&&a[1]===b[1];if(eq(r.at(-1),a[0])){r.push(...a.slice(1));parts.splice(i,1);found=true;break}if(eq(r.at(-1),a.at(-1))){r.push(...a.slice(0,-1).reverse());parts.splice(i,1);found=true;break}}}if(r.length>3)rings.push(r)}return rings}
const memberIds=new Set(raw.elements.filter(e=>e.type==='relation'&&e.tags?.natural==='water').flatMap(e=>e.members.map(m=>m.ref)));
let waters=[];
for(const e of raw.elements.filter(e=>e.tags?.natural==='water')){
 if(e.type==='way'&&!memberIds.has(e.id)&&e.geometry){let ring=e.geometry.map(xy);if(pointInside(ring[Math.floor(ring.length/2)],boundary))waters.push({id:e.id,name:e.tags.name||'园内水系',outer:ring,holes:[]})}
 if(e.type==='relation'&&e.members){const outer=join(e.members.filter(m=>m.role==='outer'&&m.geometry).map(m=>m.geometry.map(xy))),holes=join(e.members.filter(m=>m.role==='inner'&&m.geometry).map(m=>m.geometry.map(xy)));for(const ring of outer){if(pointInside(ring[Math.floor(ring.length/2)],boundary))waters.push({id:e.id,name:e.tags.name||'园内水系',outer:ring,holes:holes.filter(h=>pointInside(h[0],ring))})}}
}
const wanted=['正大光明','勤政亲贤','九洲清晏','镂月开云','天然图画','碧桐书院','慈云普护','上下天光','杏花春馆','坦坦荡荡','茹古涵今','万方安和','武陵春色','山高水长','濂溪乐处','映水兰香','多稼如云','北远山村','方壶胜境','平湖秋月','蓬岛瑶台','接秀山房','别有洞天','涵虚朗鉴','廓然大公','坐石临流','曲院风荷','洞天深处','海岳开襟','含经堂','长春园宫门','如园','鉴园','思永斋','玉玲珑馆','映清斋','谐奇趣','养雀笼','方外观','远瀛观','观水法','线法山','线法画','大水法'];
const dimensions={'正大光明':[36,18],'勤政亲贤':[28,15],'九洲清晏':[32,18],'方壶胜境':[28,22],'蓬岛瑶台':[22,17],'含经堂':[42,20],'海岳开襟':[21,21],'万方安和':[8,42],'远瀛观':[29,14],'谐奇趣':[32,16],'大水法':[22,8],'观水法':[22,8],'养雀笼':[28,8],'方外观':[16,12],'线法山':[12,12],'线法画':[18,8]};
let sites=wanted.map(name=>{let e=raw.elements.find(e=>e.type==='node'&&e.tags?.name===name);if(!e)return null;const western=['谐奇趣','养雀笼','方外观','远瀛观','观水法','线法山','线法画','大水法'].includes(name);return {id:String(e.id),name,position:xy(e),lon:e.lon,lat:e.lat,osmId:e.id,zone:western?'西洋楼':e.lon>116.302?'长春园':'圆明园',kind:western?'western':'chinese',size:dimensions[name]||[18,12],exterior:western?'B · 同期图像支持，几何推算':'C · 跨年图像约束，1786状态推测',interior:'D · 未复原，内部关闭',color:'C · 材料与色彩推测',furnishing:'D · 无同期清单，未布置',sources:western?['dpm1786','westernResearch','osm']:['forty1745','riverPlan','osm'],status:'历史外观近似；现代对应点为遗址或基址',note:western?'以1786铜版图的轮廓与构图关系为约束，细部和米制尺寸仍为推算。':'仅复原可从四十景图辨识的主要建筑形制；不能确认1786逐栋状态，标为推测性外观。'}}).filter(Boolean);
const custom=[{name:'海晏堂',lon:116.30502,lat:40.01191,kind:'western',size:[40,18],sources:['dpm1786','westernResearch','osm'],note:'位置由西洋楼平面图与蓄水楼点位估算；面西，十一间及后部蓄水设施有文字依据。兽首和喷水时钟未作精雕。'}, {name:'黄花阵',lon:116.30235,lat:40.01275,kind:'maze',size:[52,52],sources:['dpm1786','westernResearch'],note:'同期图像支持迷宫与中央亭；本项目墙路不是经测绘确认的原始迷宫图。'}, {name:'正觉寺',lon:116.2994,lat:39.99895,kind:'chinese',zone:'绮春园',size:[20,13],sources:['qichun','zhengjue'],note:'1773年已建；位置为官方地图估计，主体外观为类型化推测，不采用现代重建细部。'}];
for(const e of custom)sites.push({id:e.name,zone:e.zone||'西洋楼',position:xy(e),exterior:e.kind==='chinese'?'C · 同期形制未充分核实':'B · 同期图像支持，几何推算',interior:'D · 未复原，内部关闭',color:'C · 色彩推测',furnishing:'D · 未布置',status:'历史外观近似；现实对应区为遗址、基址或修复建筑',...e});
for(const s of sites){if(s.name==='海岳开襟'){s.sources=['haiyue1782','riverPlan','osm'];s.exterior='B · 1782修缮记录约束，细部推测';s.note='依据1782修缮记录的乾隆形制：双层圆坛、三重檐正楼、方亭及四向门。尺度文献存在约62.6–80米口径差异，本模型采用近似值。弧廊、内檐及24棵白皮松尚未精确复原。'}if(s.name==='万方安和'){s.sources=['wanfang','forty1745','osm'];s.note='卍字平面及卷棚屋顶有图像、御制诗和样式雷研究支持；本模型屋面交接、33间分室与卷棚曲线仍被简化。'}}
for(const s of sites){if(s.name==='黄花阵'){s.status='历史万花阵外观示意；现代阵墙和欧式圆亭为1987/1989修复部分';s.sources.push('mazeCurrent');s.exterior='C · 图像约束，阵墙路线未核实';s.note='亦称万花阵；原址现代修复不作为1786构件复制。本项目只表示迷宫和中央欧式圆亭的空间意向，原始墙路和雕刻未精确复原。'}if(s.name==='远瀛观'){s.status='历史完整建筑外观近似；现代仅存雕花石柱及散落石构';s.sources.push('western2026')}if(s.name==='线法画'){s.exterior='C · 布景墙意向，绘画缺失';s.note='以八字形夯土布景墙营造透视效果；本项目仅表示墙体意向，原壁画、准确透视和细部未复原。';s.status='历史布景位置示意；现代地面痕迹无存（研究记录）';s.sources.push('western2026')}if(s.name==='线法山'){s.exterior='C · 山体、台阶与柱列意向简化';s.note='山体、台阶与柱列均为意向示意；原始山形、高程及柱列精确配置缺少可配准资料。';s.sources.push('western2026')}if(s.name==='正觉寺')s.status='1773寺庙历史外观推测；现代寺庙有保护修复与复建部分';}
// Modern roads are navigation scaffolding only, never asserted as historical paths.
let paths=raw.elements.filter(e=>e.type==='way'&&e.tags?.highway==='footway'&&e.geometry).map(e=>({id:e.id,points:e.geometry.map(xy),width:4,bridge:e.tags.bridge==='yes'})).filter(p=>p.points.some(x=>pointInside(x,boundary)));
const result={epoch:1786,season:'初秋晴天',origin,units:'metres',axes:{x:'east',y:'up',z:'south'},verticalDatum:'relative: model ground 0.6m; water 0m; no surveyed absolute elevations',boundary,water:waters,paths,sites,notes:['园界为当代OSM辅助范围，非1786精确边界。','水系是与历史河道图核对大体关系后的现代轮廓代理；1786岸线尚未配准，整体属于推测性地景。','所有道路为虚拟游览辅助线，非1786历史道路测绘。','绮春园除可确证1773已建的正觉寺外，缺少1786分期边界与地盘数据，不补齐后期建筑。']};
fs.writeFileSync('public/data/layout.json',JSON.stringify(result));
console.log({sites:sites.length,waters:waters.length,paths:paths.length,waterVertices:waters.reduce((a,w)=>a+w.outer.length+w.holes.flat().length,0)});
