import {chromium} from 'playwright';
import fs from 'node:fs';
const out='evidence';fs.mkdirSync(out,{recursive:true});
const executable='C:/Users/YUE/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe';
const browser=await chromium.launch({headless:true,...(fs.existsSync(executable)?{executablePath:executable}:{}),args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});const errors=[],failed=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()?.errorText}));
function check(name,pass,details){checks.push({name,pass:!!pass,details});if(!pass)console.log('FAIL',name,details);}
async function pose(){return page.evaluate(()=>window.__tiantan.camera.position.toArray());}
async function shot(name){await page.waitForTimeout(300);await page.screenshot({path:`${out}/${name}.png`});}
try{
 await page.goto(process.env.TIANTAN_URL||'http://127.0.0.1:5180/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__tiantan?.ready,{timeout:90000});await page.waitForTimeout(500);
 const environment=await page.evaluate(()=>{const p=window.__tiantan,g=p.renderer.getContext(),ext=g.getExtension('WEBGL_debug_renderer_info');return{userAgent:navigator.userAgent,renderer:ext?g.getParameter(ext.UNMASKED_RENDERER_WEBGL):g.getParameter(g.RENDERER),webgl:g.getParameter(g.VERSION),viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,origin:p.world.data.origin,trees:p.world.treeCount,ways:p.world.data.ways.length};});
 check('页面与米制地图加载',await page.locator('#loading').isHidden()&&environment.ways>500,environment);
 check('WebGL 实际绘制',await page.evaluate(()=>{const p=window.__tiantan;return p.renderer.info.render.calls>0&&p.renderer.info.render.triangles>500000;}));
 await shot('01-prayer-aerial');
 const before=await pose();await page.mouse.move(760,470);await page.mouse.down();await page.mouse.move(900,520,{steps:10});await page.mouse.up();await page.mouse.wheel(0,-240);await page.waitForTimeout(250);const after=await pose();check('鸟瞰旋转与缩放',JSON.stringify(before)!==JSON.stringify(after),{before,after});
 await page.locator('#reset').click();check('重置回祈年殿视角',await page.evaluate(()=>Math.abs(window.__tiantan.controls.target.x)<2&&Math.abs(window.__tiantan.controls.target.z)<2));
 const center=await page.evaluate(()=>{const p=window.__tiantan;p.camera.updateMatrixWorld();const v=p.world.pickables.find(o=>o.userData.landmark.id==='qinian').position.clone().project(p.camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};});await page.mouse.click(center.x,center.y);const clicked=await page.locator('#info').isVisible()&&await page.locator('#info h2').textContent().then(t=>t.includes('祈年殿'));check('点击建筑显示简介',clicked,center);if(clicked)await page.locator('#close-info').click();
 await page.locator('#all').click();await shot('02-whole-park');check('全园鸟瞰',await page.evaluate(()=>window.__tiantan.camera.position.y>1000));
 for(const [id,name]of [['qinian','03-prayer-near'],['vault','04-vault'],['altar','05-altar'],['bridge','06-bridge'],['palace','07-palace'],['music','08-music']]){await page.locator(`[data-spot="${id}"]`).click();check(`${id} 快捷跳转及资料`,await page.locator('#info').isVisible()&&await page.locator('#info h2').textContent().then(t=>t.length>0));await page.locator('#close-info').click();await shot(name);}
 await page.locator('[data-spot="qinian"]').click();await page.locator('#close-info').click();await page.locator('#walk').click();check('步行视高与模式',await page.evaluate(()=>{const p=window.__tiantan;return p.mode==='walk'&&Math.abs(p.camera.position.y-p.world.ground(p.camera.position.x,p.camera.position.z)-1.7)<.001;}));
 let wb=await pose();await page.keyboard.down('KeyW');await page.waitForTimeout(800);await page.keyboard.up('KeyW');let wa=await pose();check('WASD 实际移动',Math.hypot(wb[0]-wa[0],wb[2]-wa[2])>1,{wb,wa});
 await page.mouse.move(730,430);await page.mouse.down();await page.mouse.move(830,450,{steps:6});await page.mouse.up();check('鼠标改变步行视角',await page.evaluate(()=>Math.abs(window.__tiantan.yaw)>.01));await shot('09-walking');
 const collision=await page.evaluate(()=>{const w=window.__tiantan.world;const q=w.landmarks[0],v=w.landmarks[1],a=w.landmarks[2],s=w.wallSegments.find(s=>s.h===3.72),wx=(s.a[0]+s.b[0])/2,wz=(s.a[1]+s.b[1])/2;return{building:w.canStand(q.x,q.z),echoBuilding:w.canStand(v.x,v.z),outside:w.canStand(2000,2000),echoWall:w.canStand(wx,wz),step:w.ground(0,44),altarTop:w.ground(a.x,a.z),bridgeNorth:w.ground(w.bridge.center(138),138),bridgeSouth:w.ground(w.bridge.center(498),498)};});
 check('建筑、回音壁与边界碰撞',!collision.building&&!collision.echoBuilding&&!collision.outside&&!collision.echoWall,collision);
 check('三级台面、桥坡与台阶高度',Math.abs(collision.altarTop-5.17)<.01&&Math.abs(collision.bridgeNorth-4)<.01&&Math.abs(collision.bridgeSouth)<.2&&collision.step>4,collision);
 const route=await page.evaluate(()=>{const w=window.__tiantan.world;function pass(x,z,x1,z1){let y=w.ground(x,z),n=Math.ceil(Math.hypot(x1-x,z1-z)/.12);for(let i=1;i<=n;i++){let xx=x+(x1-x)*i/n,zz=z+(z1-z)*i/n;if(!w.canStand(xx,zz,y))return{x:xx,z:zz};y=w.ground(xx,zz);}return true;}const e=w.landmarks[1],a=w.landmarks[2];return{bridge:pass(21,498,7,138),gate:pass(7,138,7,80),prayerSteps:pass(0,62,0,14),vaultSteps:pass(e.x,e.z+47,e.x,e.z+14),altarSteps:pass(a.x,a.z+43,a.x,a.z+2)};});check('主要游线可通行',Object.values(route).every(x=>x===true),route);
 await page.locator('#orbit').click();await page.locator('#sources').click();check('资料说明面板',await page.locator('#source-dialog').isVisible());await page.locator('#close-sources').click();
 await page.setViewportSize({width:390,height:844});await page.locator('#reset').click();await page.waitForTimeout(250);check('窄窗口 WebGL 与控件响应',await page.evaluate(()=>window.__tiantan.renderer.domElement.width>0&&document.querySelector('#spots button').getBoundingClientRect().width>0));await shot('10-mobile');await page.setViewportSize({width:1440,height:960});
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const mobile=await mobileContext.newPage();await mobile.goto(process.env.TIANTAN_URL||'http://127.0.0.1:5180/',{waitUntil:'domcontentloaded'});await mobile.waitForFunction(()=>window.__tiantan?.ready,{timeout:90000});const mobileBefore=await mobile.evaluate(()=>window.__tiantan.camera.position.toArray());const cdp=await mobile.context().newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:190,y:460}]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:190+i*7,y:460+i*3}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.waitForTimeout(300);const mobileAfter=await mobile.evaluate(()=>window.__tiantan.camera.position.toArray());check('移动设备触控鸟瞰旋转',JSON.stringify(mobileBefore)!==JSON.stringify(mobileAfter),{before:mobileBefore,after:mobileAfter});await mobileContext.close();
 const perf=[];for(const quality of ['low','medium','high']){await page.locator('#quality').selectOption(quality);await page.locator('#all').click();await page.waitForTimeout(300);perf.push(await page.evaluate(async()=>{const p=window.__tiantan;const stamps=[];await new Promise(resolve=>{const start=performance.now();const f=t=>{stamps.push(t);if(t-start<1500)requestAnimationFrame(f);else resolve();};requestAnimationFrame(f);});const d=stamps.slice(1).map((s,i)=>s-stamps[i]).sort((a,b)=>a-b),mean=d.reduce((a,b)=>a+b,0)/d.length;return{quality:p.quality,frames:d.length,meanFrameMs:mean,fps:1000/mean,p95FrameMs:d[Math.floor(d.length*.95)],drawCalls:p.renderer.info.render.calls,triangles:p.renderer.info.render.triangles,geometries:p.renderer.info.memory.geometries,textures:p.renderer.info.memory.textures,pixelRatio:p.renderer.getPixelRatio(),buffer:[p.renderer.domElement.width,p.renderer.domElement.height]};}));}
 check('三级画质切换',perf.map(p=>p.quality).join(',')==='low,medium,high',perf.map(p=>p.quality));
 check('无页面错误或失败资源',errors.length===0&&failed.length===0,{errors,failed});
 const report={timestamp:new Date().toISOString(),environment,checks,performance:perf,errors,failed,limitations:['独立 headless Chromium 与软件/硬件渲染器以 environment.renderer 为准','全园鸟瞰静止视角约 1.5 秒样本；不代表所有设备或长时间游览帧率'],passed:checks.every(x=>x.pass)};
 fs.writeFileSync(`${out}/test-results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.passed)process.exitCode=1;
}finally{await browser.close();}
