import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {inside,distanceToSegment} from './geometry.js';
import {surfaceHeight} from './terrain.js';
export class Navigation {
 constructor(camera,canvas,buildings,landscape,onMessage){this.camera=camera;this.canvas=canvas;this.buildings=buildings;this.landscape=landscape;this.onMessage=onMessage;this.mode='orbit';this.yaw=0;this.pitch=0;this.keys=new Set();this.drag=false;this.height=1.68;this.orbit=new OrbitControls(camera,canvas);this.orbit.enableDamping=true;this.orbit.dampingFactor=.07;this.orbit.maxPolarAngle=Math.PI/2-.015;this.orbit.minDistance=10;this.orbit.maxDistance=2100;this.orbit.target.set(0,0,0);this.grid=new Map();
 const obstacles=[...buildings.colliders,...landscape.colliders];for(const c of obstacles){const p=c.points||[c.a,c.b],r=(c.radius||0)+1;const xs=p.map(p=>p[0]),zs=p.map(p=>p[1]);for(let i=Math.floor((Math.min(...xs)-r)/30);i<=Math.floor((Math.max(...xs)+r)/30);i++)for(let j=Math.floor((Math.min(...zs)-r)/30);j<=Math.floor((Math.max(...zs)+r)/30);j++){const key=`${i},${j}`;if(!this.grid.has(key))this.grid.set(key,[]);this.grid.get(key).push(c);}}
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;this.keys.add(e.code);if(this.mode==='walk'&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>{this.keys.clear();this.drag=false;});canvas.addEventListener('pointerdown',e=>{if(this.mode==='walk'&&e.button===0)this.drag=true;});window.addEventListener('pointerup',()=>this.drag=false);document.addEventListener('mousemove',e=>{if(this.mode==='walk'&&(this.drag||document.pointerLockElement===canvas)){this.yaw-=e.movementX*.0025;this.pitch=THREE.MathUtils.clamp(this.pitch-e.movementY*.0025,-1.25,1.25);this.look();}});canvas.addEventListener('dblclick',()=>{if(this.mode==='walk')canvas.requestPointerLock?.();});document.addEventListener('pointerlockerror',()=>onMessage('鼠标锁定不可用，可按住左键观察。'));
 }
 ground(x,z){return surfaceHeight(x,z,this.buildings.platforms,this.landscape.ramps,this.landscape.bridges);}
 canStand(x,z,currentHeight=this.ground(x,z),transit=true){if(Math.abs(x)>370||z<-477||z>556||(z>480&&Math.abs(x)>92))return false;const h=this.ground(x,z);if(transit&&Math.abs(h-currentHeight)>.36)return false;
 for(const c of this.grid.get(`${Math.floor(x/30)},${Math.floor(z/30)}`)||[]){if(c.height<=h+.1)continue;if(c.a){if(distanceToSegment(x,z,c.a,c.b)<(c.radius||0)+.36)return false;}else{if(inside(x,z,c.points)&&!c.holes.some(p=>inside(x,z,p)))return false;for(let i=1;i<c.points.length;i++)if(distanceToSegment(x,z,c.points[i-1],c.points[i])<.36)return false;}}
 const bridge=this.landscape.bridges.some(b=>Math.abs(x-b.x)<b.w/2-.3&&Math.abs(z-b.z)<b.d/2+.2);
 if(!bridge)for(const water of this.landscape.waterAreas){if(water.rect){const [a,b,c,d]=water.rect;if(x>a&&x<b&&z>c&&z<d)return false;}else if(water.points?inside(x,z,water.points):distanceToSegment(x,z,water.a,water.b)<water.radius+.35)return false;}
 return true;}
 safePoint(x,z){for(let radius=0;radius<100;radius+=2)for(let angle=0;angle<Math.PI*2;angle+=Math.PI/8){const a=x+Math.sin(angle)*radius,b=z+Math.cos(angle)*radius;if(this.canStand(a,b,0,false))return [a,b];}return[-3,180];}
 setMode(mode){if(this.mode===mode)return;document.exitPointerLock?.();this.mode=mode;this.orbit.enabled=mode==='orbit';this.keys.clear();if(mode==='walk'){const p=this.safePoint(this.orbit.target.x,this.orbit.target.z+70);this.camera.position.set(p[0],this.ground(...p)+this.height,p[1]);this.yaw=0;this.pitch=0;this.look();this.onMessage('WASD 移动 · 按住左键观察 · 双击锁定鼠标 · Esc 释放');}else{const p=this.camera.position.clone();this.orbit.target.set(p.x,0,p.z-40);this.camera.position.set(p.x+85,110,p.z+120);this.orbit.update();}}
 look(){this.camera.rotation.order='YXZ';this.camera.rotation.set(this.pitch,this.yaw,0);}
 locate(b){if(this.mode==='walk'){const p=this.safePoint(b.x,b.z+(b.d||25)/2+22);this.camera.position.set(p[0],this.ground(...p)+this.height,p[1]);this.yaw=0;this.pitch=.08;this.look();}else{this.orbit.target.set(b.x,b.base+6,b.z);this.camera.position.set(b.x+75,95,b.z+120);this.orbit.update();}}
 home(){if(this.mode==='walk')this.setMode('orbit');this.orbit.target.set(0,0,0);this.camera.position.set(690,920,1070);this.orbit.update();}
 update(dt){if(this.mode==='orbit'){this.orbit.update();return;}const f=(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)-(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0),s=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0);if(this.keys.has('ArrowLeft'))this.yaw+=dt;if(this.keys.has('ArrowRight'))this.yaw-=dt;const len=Math.hypot(f,s)||1,speed=(this.keys.has('ShiftLeft')?3.8:1.5)*dt;const dx=(-Math.sin(this.yaw)*f+Math.cos(this.yaw)*s)/len*speed,dz=(-Math.cos(this.yaw)*f-Math.sin(this.yaw)*s)/len*speed,p=this.camera.position,old=this.ground(p.x,p.z);
 // Substeps bound tunneling even when a frame stalls. X/Z separation allows wall sliding.
 const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.12));for(let i=0;i<steps;i++){if(this.canStand(p.x+dx/steps,p.z,this.ground(p.x,p.z)))p.x+=dx/steps;if(this.canStand(p.x,p.z+dz/steps,this.ground(p.x,p.z)))p.z+=dz/steps;}p.y=this.ground(p.x,p.z)+this.height;this.look();}
}
